from exercises.base import ExerciseDefinition
from enums import MuscleGroup, EquipmentType, MechanicsType, MajorMuscleGroup, ForceType, LevelType, CategoryType

ABDUCTORS_EXERCISES = {
    "Lying_Crossover": ExerciseDefinition(
        id="Lying_Crossover",
        display_name="Lying Crossover",
        level=LevelType.EXPERT,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.ABDUCTORS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.STATIC,
        instructions="['Lie on your back with your legs extended.', 'Cross one leg over your body with the knee bent, attempting to touch the knee to the ground. Your partner should kneel beside you, holding your shoulder down with one hand and controlling the crossed leg with the other. this will be your starting position.', 'Attempt to raise the bent knee off of the ground as your partner prevents any actual movement.', 'After 10-20 seconds, relax the leg as your partner gently presses the knee towards the floor. Repeat with the other side.']",
        images=['Lying_Crossover/0.jpg', 'Lying_Crossover/1.jpg'],
    ),
    "Thigh_Abductor": ExerciseDefinition(
        id="Thigh_Abductor",
        display_name="Thigh Abductor",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.ABDUCTORS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.MACHINE,
        secondary_muscles=[MuscleGroup.GLUTES],
        instructions="['To begin, sit down on the abductor machine and select a weight you are comfortable with. When your legs are positioned properly, grip the handles on each side. Your entire upper body (from the waist up) should be stationary. This is the starting position.', 'Slowly press against the machine with your legs to move them away from each other while exhaling.', 'Feel the contraction for a second and begin to move your legs back to the starting position while breathing in. Note: Remember to keep your upper body stationary to prevent any injuries from occurring.', 'Repeat for the recommended amount of repetitions.']",
        images=['Thigh_Abductor/0.jpg', 'Thigh_Abductor/1.jpg'],
    ),
    "Monster_Walk": ExerciseDefinition(
        id="Monster_Walk",
        display_name="Monster Walk",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.ABDUCTORS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        instructions="['Place a band around both ankles and another around both knees. There should be enough tension that they are tight when your feet are shoulder width apart.', 'To begin, take short steps forward alternating your left and right foot.', 'After several steps, do just the opposite and walk backward to where you started.']",
        images=['Monster_Walk/0.jpg', 'Monster_Walk/1.jpg'],
    ),
    "Standing_Hip_Circles": ExerciseDefinition(
        id="Standing_Hip_Circles",
        display_name="Standing Hip Circles",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.ABDUCTORS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        secondary_muscles=[MuscleGroup.ADDUCTORS],
        instructions="['Begin standing on one leg, holding to a vertical support.', 'Raise the unsupported knee to 90 degrees. This will be your starting position.', 'Open the hip as far as possible, attempting to make a big circle with your knee.', 'Perform this movement slowly for a number of repetitions, and repeat on the other side.']",
        images=['Standing_Hip_Circles/0.jpg', 'Standing_Hip_Circles/1.jpg'],
    ),
    "Hip_Circles_prone": ExerciseDefinition(
        id="Hip_Circles_prone",
        display_name="Hip Circles (prone)",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.ABDUCTORS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        secondary_muscles=[MuscleGroup.ADDUCTORS],
        instructions="['Position yourself on your hands and knees on the ground. Maintaining good posture, raise one bent knee off of the ground. This will be your starting position.', 'Keeping the knee in a bent position, rotate the femur in an arc, attempting to make a big circle with your knee.', 'Perform this slowly for a number of repetitions, and repeat on the other side.']",
        images=['Hip_Circles_prone/0.jpg', 'Hip_Circles_prone/1.jpg'],
    ),
    "IT_Band_and_Glute_Stretch": ExerciseDefinition(
        id="IT_Band_and_Glute_Stretch",
        display_name="IT Band and Glute Stretch",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.ABDUCTORS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.STATIC,
        equipment_type=EquipmentType.OTHER,
        instructions="['Loop a belt, rope, or band around one of your feet, and swing that leg across your body to the opposite side, keeping the leg extended as you lay on the ground. This will be your starting position.', 'Keeping your foot off of the floor, pull on the belt, using the tension to pull the toes up. Hold for 10-20 seconds, and repeat on the other side.']",
        images=['IT_Band_and_Glute_Stretch/0.jpg', 'IT_Band_and_Glute_Stretch/1.jpg'],
    ),
    "Windmills": ExerciseDefinition(
        id="Windmills",
        display_name="Windmills",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.ABDUCTORS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        secondary_muscles=[MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS, MuscleGroup.LOWER_BACK],
        instructions="['Lie on your back with your arms extended out to the sides and your legs straight. This will be your starting position.', 'Lift one leg and quickly cross it over your body, attempting to touch the ground near the opposite hand.', 'Return to the starting position, and repeat with the opposite leg. Continue to alternate for 10-20 repetitions.']",
        images=['Windmills/0.jpg', 'Windmills/1.jpg'],
    ),
    "Iliotibial_Tract-SMR": ExerciseDefinition(
        id="Iliotibial_Tract-SMR",
        display_name="Iliotibial Tract-SMR",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.ABDUCTORS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.STATIC,
        mechanics_type=MechanicsType.ISOLATION,
        instructions="['Lay on your side, with the bottom leg placed onto a foam roller between the hip and the knee. The other leg can be crossed in front of you.', 'Place as much of your weight as is tolerable onto your bottom leg; there is no need to keep your bottom leg in contact with the ground. Be sure to relax the muscles of the leg you are stretching.', 'Roll your leg over the foam from you hip to your knee, pausing for 10-30 seconds at points of tension. Repeat with the opposite leg.']",
        images=['Iliotibial_Tract-SMR/0.jpg', 'Iliotibial_Tract-SMR/1.jpg'],
    ),
}
