from exercises.base import ExerciseDefinition
from enums import MuscleGroup, EquipmentType, MechanicsType, MajorMuscleGroup, ForceType, LevelType, CategoryType

ADDUCTORS_EXERCISES = {
    "Lateral_Bound": ExerciseDefinition(
        id="Lateral_Bound",
        display_name="Lateral Bound",
        level=LevelType.BEGINNER,
        category=CategoryType.PLYOMETRICS,
        muscle_group=MuscleGroup.ADDUCTORS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.ABDUCTORS, MuscleGroup.CALVES, MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS, MuscleGroup.QUADS],
        instructions="['Assume a half squat position facing 90 degrees from your direction of travel. This will be your starting position.', 'Allow your lead leg to do a countermovement inward as you shift your weight to the outside leg.', 'Immediately push off and extend, attempting to bound to the side as far as possible.', 'Upon landing, immediately push off in the opposite direction, returning to your original start position.', 'Continue back and forth for several repetitions.']",
        images=['Lateral_Bound/0.jpg', 'Lateral_Bound/1.jpg'],
    ),
    "Side_Leg_Raises": ExerciseDefinition(
        id="Side_Leg_Raises",
        display_name="Side Leg Raises",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.ADDUCTORS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        instructions="['Stand next to a chair, which you may hold onto as a support. Stand on one leg. This will be your starting position.', 'Keeping your leg straight, raise it as far out to the side as possible, and swing it back down, allowing it to cross the opposite leg.', 'Repeat this swinging motion 5-10 times, increasing the range of motion as you do so.']",
        images=['Side_Leg_Raises/0.jpg', 'Side_Leg_Raises/1.jpg'],
    ),
    "Lateral_Cone_Hops": ExerciseDefinition(
        id="Lateral_Cone_Hops",
        display_name="Lateral Cone Hops",
        level=LevelType.BEGINNER,
        category=CategoryType.PLYOMETRICS,
        muscle_group=MuscleGroup.ADDUCTORS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.OTHER,
        secondary_muscles=[MuscleGroup.ABDUCTORS, MuscleGroup.CALVES, MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS, MuscleGroup.QUADS],
        instructions="['Position a number of cones in a row several feet apart.', 'Stand next to the end of the cones, facing 90 degrees to the direction of travel. This will be your starting position.', 'Begin the jump by dipping with the knees to initiate a stretch reflex, and immediately reverse direction to push off the ground, jumping up and sideways over the cone.', 'Use your legs to absorb impact upon landing, and rebound into the next jump, continuing down the row of cones.']",
        images=['Lateral_Cone_Hops/0.jpg', 'Lateral_Cone_Hops/1.jpg'],
    ),
    "Thigh_Adductor": ExerciseDefinition(
        id="Thigh_Adductor",
        display_name="Thigh Adductor",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.ADDUCTORS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.MACHINE,
        secondary_muscles=[MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS],
        instructions="['To begin, sit down on the adductor machine and select a weight you are comfortable with. When your legs are positioned properly on the leg pads of the machine, grip the handles on each side. Your entire upper body (from the waist up) should be stationary. This is the starting position.', 'Slowly press against the machine with your legs to move them towards each other while exhaling.', 'Feel the contraction for a second and begin to move your legs back to the starting position while breathing in. Note: Remember to keep your upper body stationary and avoid fast jerking motions in order to prevent any injuries from occurring.', 'Repeat for the recommended amount of repetitions.']",
        images=['Thigh_Adductor/0.jpg', 'Thigh_Adductor/1.jpg'],
    ),
    "Side_Lying_Groin_Stretch": ExerciseDefinition(
        id="Side_Lying_Groin_Stretch",
        display_name="Side Lying Groin Stretch",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.ADDUCTORS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.STATIC,
        mechanics_type=MechanicsType.ISOLATION,
        secondary_muscles=[MuscleGroup.HAMSTRINGS],
        instructions="['Start off by lying on your right side and bend your right knee in front of you to stabilize the torso.', 'Rest your head on your right hand or shoulder. Lift your left leg upward and hold it by the back of the knee (easier) or the foot (harder).', 'Pull your left knee in toward your left shoulder and simultaneously press your foot or knee down to the floor. To intensify this stretch, straighten your left leg. Switch sides.']",
        images=['Side_Lying_Groin_Stretch/0.jpg', 'Side_Lying_Groin_Stretch/1.jpg'],
    ),
    "Lying_Bent_Leg_Groin": ExerciseDefinition(
        id="Lying_Bent_Leg_Groin",
        display_name="Lying Bent Leg Groin",
        level=LevelType.EXPERT,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.ADDUCTORS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.STATIC,
        equipment_type=EquipmentType.OTHER,
        instructions="['Lie on your back with your knees bent and the soles of the feet pressed together. Have your partner hold your knees. This will be your starting position.', 'Attempt to squeeze your knees together, while your partner prevents any movement from occurring.', 'After 10-20 seconds, relax your muscles as your partner gently pushes your knees towards the floor. Be sure to inform your helper when the stretch is adequate to prevent injury or overstretching.']",
        images=['Lying_Bent_Leg_Groin/0.jpg', 'Lying_Bent_Leg_Groin/1.jpg'],
    ),
    "Adductor_Groin": ExerciseDefinition(
        id="Adductor_Groin",
        display_name="Adductor/Groin",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.ADDUCTORS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.STATIC,
        instructions="['Lie on your back with your feet raised towards the ceiling.', 'Have your partner hold your feet or ankles. Abduct your legs as far as you can. This will be your starting position.', 'Attempt to squeeze your legs together for 10 or more seconds, while your partner prevents you from doing so.', 'Now, relax the muscles in your legs as your partner pushes your feet apart, stretching as far as is comfortable for you. Be sure to let your partner know when the stretch is adequate to prevent overstretching or injury.']",
        images=['Adductor_Groin/0.jpg', 'Adductor_Groin/1.jpg'],
    ),
    "Adductor": ExerciseDefinition(
        id="Adductor",
        display_name="Adductor",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.ADDUCTORS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.STATIC,
        mechanics_type=MechanicsType.ISOLATION,
        instructions="['Lie face down with one leg on a foam roll.', 'Rotate the leg so that the foam roll contacts against your inner thigh. Shift as much weight onto the foam roll as can be tolerated.', 'While trying to relax the muscles if the inner thigh, roll over the foam between your hip and knee, holding points of tension for 10-30 seconds. Repeat with the other leg.']",
        images=['Adductor/0.jpg', 'Adductor/1.jpg'],
    ),
    "Lateral_Box_Jump": ExerciseDefinition(
        id="Lateral_Box_Jump",
        display_name="Lateral Box Jump",
        level=LevelType.BEGINNER,
        category=CategoryType.PLYOMETRICS,
        muscle_group=MuscleGroup.ADDUCTORS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.OTHER,
        secondary_muscles=[MuscleGroup.ABDUCTORS, MuscleGroup.CALVES, MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS, MuscleGroup.QUADS],
        instructions="['Assume a comfortable standing position, with a short box positioned next to you. This will be your starting position.', 'Quickly dip into a quarter squat to initiate the stretch reflex, and immediately reverse direction to jump up and to the side.', 'Bring your knees high enough to ensure your feet have good clearance over the box.', 'Land on the center of the box, using your legs to absorb the impact.', 'Carefully jump down to the other side of the box, and continue going back and forth for several repetitions.']",
        images=['Lateral_Box_Jump/0.jpg', 'Lateral_Box_Jump/1.jpg'],
    ),
    "Band_Hip_Adductions": ExerciseDefinition(
        id="Band_Hip_Adductions",
        display_name="Band Hip Adductions",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.ADDUCTORS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        instructions="['Anchor a band around a solid post or other object.', 'Stand with your left side to the post, and put your right foot through the band, getting it around the ankle.', 'Stand up straight and hold onto the post if needed. This will be your starting position.', 'Keeping the knee straight, raise your right legs out to the side as far as you can.', 'Return to the starting position and repeat for the desired rep count.', 'Switch sides.']",
        images=['Band_Hip_Adductions/0.jpg', 'Band_Hip_Adductions/1.jpg'],
    ),
    "Carioca_Quick_Step": ExerciseDefinition(
        id="Carioca_Quick_Step",
        display_name="Carioca Quick Step",
        level=LevelType.BEGINNER,
        category=CategoryType.PLYOMETRICS,
        muscle_group=MuscleGroup.ADDUCTORS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        secondary_muscles=[MuscleGroup.ABS, MuscleGroup.ABDUCTORS, MuscleGroup.CALVES, MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS, MuscleGroup.QUADS],
        instructions="['Begin with your feet a few inches apart and your left arm up in a relaxed, athletic position.', 'With your right foot, quick step behind and pull the knee up.', 'Fire your arms back up when you pull the right knee, being sure that your knee goes straight up and down. Avoid turning your feet as you move and continue to look forward as you move to the side.']",
        images=['Carioca_Quick_Step/0.jpg', 'Carioca_Quick_Step/1.jpg'],
    ),
    "Groiners": ExerciseDefinition(
        id="Groiners",
        display_name="Groiners",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.ADDUCTORS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        instructions="['Begin in a pushup position on the floor. This will be your starting position.', 'Using both legs, jump forward landing with your feet next to your hands. Keep your head up as you do so.', 'Return to the starting position and immediately repeat the movement, continuing for 10-20 repetitions.']",
        images=['Groiners/0.jpg', 'Groiners/1.jpg'],
    ),
    "Groin_and_Back_Stretch": ExerciseDefinition(
        id="Groin_and_Back_Stretch",
        display_name="Groin and Back Stretch",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.ADDUCTORS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.STATIC,
        mechanics_type=MechanicsType.COMPOUND,
        instructions="['Sit on the floor with your knees bent and feet together.', 'Interlock your fingers behind your head. This will be your starting position.', 'Curl downwards, bringing your elbows to the inside of your thighs. After a brief pause, return to the starting position with your head up and your back straight. Repeat for 10-20 repetitions.']",
        images=['Groin_and_Back_Stretch/0.jpg', 'Groin_and_Back_Stretch/1.jpg'],
    ),
}
