from exercises.base import ExerciseDefinition
from enums import MuscleGroup, EquipmentType, MechanicsType, MajorMuscleGroup, ForceType, LevelType, CategoryType

BICEPS_EXERCISES = {
    "Lying_Supine_Dumbbell_Curl": ExerciseDefinition(
        id="Lying_Supine_Dumbbell_Curl",
        display_name="Lying Supine Dumbbell Curl",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        instructions="['Lie down on a flat bench face up while holding a dumbbell in each arm on top of your thighs.', 'Bring the dumbbells to the sides with the arms extended and the palms of the hands facing your thighs (neutral grip).', 'While keeping the arms close to your torso and elbows in, slowly lower your arms (as you keep them extended with a slight bend at the elbows) as far down towards the floor as you can go. Once you cannot go down any further, lock your upper arms in that position and that will be your starting position.', 'As you breathe out, slowly begin to curl the weights up as you simultaneously rotate your wrists so that the palms of the hands face up. Continue curling the weight until your biceps are fully contracted and squeeze hard at the top position for a second. Tip: Only the forearms should move. Upper arms should remain stationary and elbows should stay in throughout the movement.', 'Return back to the starting position very slowly.']",
        images=['Lying_Supine_Dumbbell_Curl/0.jpg', 'Lying_Supine_Dumbbell_Curl/1.jpg'],
    ),
    "Alternate_Incline_Dumbbell_Curl": ExerciseDefinition(
        id="Alternate_Incline_Dumbbell_Curl",
        display_name="Alternate Incline Dumbbell Curl",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        secondary_muscles=[MuscleGroup.FOREARMS],
        instructions="['Sit down on an incline bench with a dumbbell in each hand being held at arms length. Tip: Keep the elbows close to the torso.This will be your starting position.', 'While holding the upper arm stationary, curl the right weight forward while contracting the biceps as you breathe out. As you do so, rotate the hand so that the palm is facing up. Continue the movement until your biceps is fully contracted and the dumbbells are at shoulder level. Hold the contracted position for a second as you squeeze the biceps. Tip: Only the forearms should move.', 'Slowly begin to bring the dumbbell back to starting position as your breathe in.', 'Repeat the movement with the left hand. This equals one repetition.', 'Continue alternating in this manner for the recommended amount of repetitions.']",
        images=['Alternate_Incline_Dumbbell_Curl/0.jpg', 'Alternate_Incline_Dumbbell_Curl/1.jpg'],
    ),
    "Lying_Close-Grip_Bar_Curl_On_High_Pulley": ExerciseDefinition(
        id="Lying_Close-Grip_Bar_Curl_On_High_Pulley",
        display_name="Lying Close-Grip Bar Curl On High Pulley",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="['Place a flat bench in front of a high pulley or lat pulldown machine.', 'Hold the straight bar attachment using an underhand grip (palms up) that is about shoulder width.', 'Lie on your back with your head over the end of the bench.', 'Now extend your arms straight above your shoulders. Your torso and your arms should make a 90-degree angle and the elbows should be in. This will be your starting position.', 'As you breathe out, curl the bar down in a semicircular motion until it touches your chin. Squeeze the biceps for a second at the top contracted position. Tip: As you execute this motion only the forearms should move. At no time should the upper arms be moving at all. They are to remain perpendicular throughout the movement.', 'Return to starting position slowly.', 'Repeat for the recommended amount of repetitions.']",
        images=['Lying_Close-Grip_Bar_Curl_On_High_Pulley/0.jpg', 'Lying_Close-Grip_Bar_Curl_On_High_Pulley/1.jpg'],
    ),
    "Cable_Hammer_Curls_-_Rope_Attachment": ExerciseDefinition(
        id="Cable_Hammer_Curls_-_Rope_Attachment",
        display_name="Cable Hammer Curls - Rope Attachment",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="['Attach a rope attachment to a low pulley and stand facing the machine about 12 inches away from it.', 'Grasp the rope with a neutral (palms-in) grip and stand straight up keeping the natural arch of the back and your torso stationary.', 'Put your elbows in by your side and keep them there stationary during the entire movement. Tip: Only the forearms should move; not your upper arms. This will be your starting position.', 'Using your biceps, pull your arms up as you exhale until your biceps touch your forearms. Tip: Remember to keep the elbows in and your upper arms stationary.', 'After a 1 second contraction where you squeeze your biceps, slowly start to bring the weight back to the original position.', 'Repeat for the recommended amount of repetitions.']",
        images=['Cable_Hammer_Curls_-_Rope_Attachment/0.jpg', 'Cable_Hammer_Curls_-_Rope_Attachment/1.jpg'],
    ),
    "Machine_Preacher_Curls": ExerciseDefinition(
        id="Machine_Preacher_Curls",
        display_name="Machine Preacher Curls",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.MACHINE,
        instructions="['Sit down on the Preacher Curl Machine and select the weight.', 'Place the back of your upper arms (your triceps) on the preacher pad provided and grab the handles using an underhand grip (palms facing up). Tip: Make sure that when you place the arms on the pad you keep the elbows in. This will be your starting position.', 'Now lift the handles as you exhale and you contract the biceps. At the top of the position make sure that you hold the contraction for a second. Tip: Only the forearms should move. The upper arms should remain stationary and on the pad at all times.', 'Lower the handles slowly back to the starting position as you inhale.', 'Repeat for the recommended amount of repetitions.']",
        images=['Machine_Preacher_Curls/0.jpg', 'Machine_Preacher_Curls/1.jpg'],
    ),
    "Seated_Close-Grip_Concentration_Barbell_Curl": ExerciseDefinition(
        id="Seated_Close-Grip_Concentration_Barbell_Curl",
        display_name="Seated Close-Grip Concentration Barbell Curl",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.BARBELL,
        instructions="['Sit down on a flat bench with a barbell or E-Z Bar in front of you in between your legs. Your legs should be spread with the knees bent and the feet on the floor.', 'Use your arms to pick the barbell up and place the back of your upper arms on top of your inner thighs (around three and a half inches away from the front of the knee). A supinated grip closer than shoulder width is needed to perform this exercise. Tip: Your arm should be extended at arms length and the barbell should be above the floor. This will be your starting position.', 'While holding the upper arms stationary, curl the weights forward while contracting the biceps as you breathe out. Only the forearms should move. Continue the movement until your biceps are fully contracted and the dumbbells are at shoulder level. Hold the contracted position for a second as you squeeze the biceps.', 'Slowly begin to bring the barbell back to starting position as your breathe in. Tip: Avoid swinging motions at any time.', 'Repeat for the recommended amount of repetitions.']",
        images=['Seated_Close-Grip_Concentration_Barbell_Curl/0.jpg', 'Seated_Close-Grip_Concentration_Barbell_Curl/1.jpg'],
    ),
    "Standing_Inner-Biceps_Curl": ExerciseDefinition(
        id="Standing_Inner-Biceps_Curl",
        display_name="Standing Inner-Biceps Curl",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        instructions="""['Stand up with a dumbbell in each hand being held at arms length. The elbows should be close to the torso. Your legs should be at about shoulder\'s width apart from each other.', 'Rotate the palms of the hands so that they are facing inward in a neutral position. This will be your starting position.', 'While holding the upper arms stationary, curl the weights out while contracting the biceps as you breathe out. Your wrist should turn so that when the weights are fully elevated you have supinated grip (palms facing up).', 'Only the forearms should move. Continue the movement until your biceps are fully contracted and the dumbbells are at shoulder level. Tip: Keep the forearms aligned with your outer deltoids.', 'Hold the contracted position for a second as you squeeze the biceps.', 'Slowly begin to bring the dumbbells back to the starting position as your breathe in. Remember to rotate the wrists as you lower the weight in order to switch back to a neutral grip.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Standing_Inner-Biceps_Curl/0.jpg', 'Standing_Inner-Biceps_Curl/1.jpg'],
    ),
    "Preacher_Curl": ExerciseDefinition(
        id="Preacher_Curl",
        display_name="Preacher Curl",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.BARBELL,
        instructions="['To perform this movement you will need a preacher bench and an E-Z bar. Grab the E-Z curl bar at the close inner handle (either have someone hand you the bar which is preferable or grab the bar from the front bar rest provided by most preacher benches). The palm of your hands should be facing forward and they should be slightly tilted inwards due to the shape of the bar.', 'With the upper arms positioned against the preacher bench pad and the chest against it, hold the E-Z Curl Bar at shoulder length. This will be your starting position.', 'As you breathe in, slowly lower the bar until your upper arm is extended and the biceps is fully stretched.', 'As you exhale, use the biceps to curl the weight up until your biceps is fully contracted and the bar is at shoulder height. Squeeze the biceps hard and hold this position for a second.', 'Repeat for the recommended amount of repetitions.']",
        images=['Preacher_Curl/0.jpg', 'Preacher_Curl/1.jpg'],
    ),
    "Spider_Curl": ExerciseDefinition(
        id="Spider_Curl",
        display_name="Spider Curl",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        instructions="['Start out by setting the bar on the part of the preacher bench that you would normally sit on. Make sure to align the barbell properly so that it is balanced and will not fall off.', 'Move to the front side of the preacher bench (the part where the arms usually lay) and position yourself to lay at a 45 degree slant with your torso and stomach pressed against the front side of the preacher bench.', 'Make sure that your feet (especially the toes) are well positioned on the floor and place your upper arms on top of the pad located on the inside part of the preacher bench.', 'Use your arms to grab the barbell with a supinated grip (palms facing up) at about shoulder width apart or slightly closer from each other.', 'Slowly begin to lift the barbell upwards and exhale. Hold the contracted position for a second as you squeeze the biceps.', 'Slowly begin to bring the barbell back to the starting position as your breathe in. .', 'Repeat for the recommended amount of repetitions.']",
        images=['Spider_Curl/0.jpg', 'Spider_Curl/1.jpg'],
    ),
    "Reverse_Barbell_Curl": ExerciseDefinition(
        id="Reverse_Barbell_Curl",
        display_name="Reverse Barbell Curl",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.FOREARMS],
        instructions="['Stand up with your torso upright while holding a barbell at shoulder width with the elbows close to the torso. The palm of your hands should be facing down (pronated grip). This will be your starting position.', 'While holding the upper arms stationary, curl the weights while contracting the biceps as you breathe out. Only the forearms should move. Continue the movement until your biceps are fully contracted and the bar is at shoulder level. Hold the contracted position for a second as you squeeze the muscle.', 'Slowly begin to bring the bar back to starting position as your breathe in.', 'Repeat for the recommended amount of repetitions.']",
        images=['Reverse_Barbell_Curl/0.jpg', 'Reverse_Barbell_Curl/1.jpg'],
    ),
    "Incline_Dumbbell_Curl": ExerciseDefinition(
        id="Incline_Dumbbell_Curl",
        display_name="Incline Dumbbell Curl",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        instructions="['Sit back on an incline bench with a dumbbell in each hand held at arms length. Keep your elbows close to your torso and rotate the palms of your hands until they are facing forward. This will be your starting position.', 'While holding the upper arm stationary, curl the weights forward while contracting the biceps as you breathe out. Only the forearms should move. Continue the movement until your biceps are fully contracted and the dumbbells are at shoulder level. Hold the contracted position for a second.', 'Slowly begin to bring the dumbbells back to starting position as your breathe in.', 'Repeat for the recommended amount of repetitions.']",
        images=['Incline_Dumbbell_Curl/0.jpg', 'Incline_Dumbbell_Curl/1.jpg'],
    ),
    "Preacher_Hammer_Dumbbell_Curl": ExerciseDefinition(
        id="Preacher_Hammer_Dumbbell_Curl",
        display_name="Preacher Hammer Dumbbell Curl",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        secondary_muscles=[MuscleGroup.FOREARMS],
        instructions="['Place the upper part of both arms on top of the preacher bench as you hold a dumbbell in each hand with the palms facing each other (neutral grip).', 'As you breathe in, slowly lower the dumbbells until your upper arm is extended and the biceps is fully stretched.', 'As you exhale, use the biceps to curl the weight up until your biceps is fully contracted and the dumbbells are at shoulder height.', 'Squeeze the biceps hard for a second at the contracted position and repeat for the recommended amount of repetitions.']",
        images=['Preacher_Hammer_Dumbbell_Curl/0.jpg', 'Preacher_Hammer_Dumbbell_Curl/1.jpg'],
    ),
    "Reverse_Barbell_Preacher_Curls": ExerciseDefinition(
        id="Reverse_Barbell_Preacher_Curls",
        display_name="Reverse Barbell Preacher Curls",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        secondary_muscles=[MuscleGroup.FOREARMS],
        instructions="['Grab an EZ-bar using a shoulder width and palms down (pronated) grip.', 'Now place the upper part of both arms on top of the preacher bench and have your arms extended. This will be your starting position.', 'As you exhale, use the biceps to curl the weight up until your biceps are fully contracted and the barbell is at shoulder height. Squeeze the biceps hard for a second at the contracted position.', 'As you breathe in, slowly lower the barbell until your upper arms are extended and the biceps is fully stretched.', 'Repeat for the recommended amount of repetitions.']",
        images=['Reverse_Barbell_Preacher_Curls/0.jpg', 'Reverse_Barbell_Preacher_Curls/1.jpg'],
    ),
    "Hammer_Curls": ExerciseDefinition(
        id="Hammer_Curls",
        display_name="Hammer Curls",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        instructions="['Stand up with your torso upright and a dumbbell on each hand being held at arms length. The elbows should be close to the torso.', 'The palms of the hands should be facing your torso. This will be your starting position.', 'Now, while holding your upper arm stationary, exhale and curl the weight forward while contracting the biceps. Continue to raise the weight until the biceps are fully contracted and the dumbbell is at shoulder level. Hold the contracted position for a brief moment as you squeeze the biceps. Tip: Focus on keeping the elbow stationary and only moving your forearm.', 'After the brief pause, inhale and slowly begin the lower the dumbbells back down to the starting position.', 'Repeat for the recommended amount of repetitions.']",
        images=['Hammer_Curls/0.jpg', 'Hammer_Curls/1.jpg'],
    ),
    "Incline_Hammer_Curls": ExerciseDefinition(
        id="Incline_Hammer_Curls",
        display_name="Incline Hammer Curls",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        instructions="['Seat yourself on an incline bench with a dumbbell in each hand. You should pressed firmly against he back with your feet together. Allow the dumbbells to hang straight down at your side, holding them with a neutral grip. This will be your starting position.', 'Initiate the movement by flexing at the elbow, attempting to keep the upper arm stationary.', 'Continue to the top of the movement and pause, then slowly return to the start position.']",
        images=['Incline_Hammer_Curls/0.jpg', 'Incline_Hammer_Curls/1.jpg'],
    ),
    "Standing_One-Arm_Dumbbell_Curl_Over_Incline_Bench": ExerciseDefinition(
        id="Standing_One-Arm_Dumbbell_Curl_Over_Incline_Bench",
        display_name="Standing One-Arm Dumbbell Curl Over Incline Bench",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        instructions="['Stand on the back side of an incline bench as if you were going to be a spotter for someone. Have a dumbbell in one hand and rest it across the incline bench with a supinated (palms up) grip.', 'Position your non lifting hand at the corner or side of the incline bench. The chest should be pressed against the top part of the incline and your feet should be pressed against the floor at a wide stance. This is the starting position.', 'While holding the upper arm stationary, curl the dumbbell upward while contracting the biceps as you breathe out. Only the forearms should move. Continue the movement until your biceps are fully contracted and the dumbbell is at shoulder level. Hold the contracted position for a second.', 'Slowly begin to bring the dumbbells back to starting position as your breathe in.', 'Repeat for the recommended amount of repetitions.', 'Switch arms while performing this exercise.']",
        images=['Standing_One-Arm_Dumbbell_Curl_Over_Incline_Bench/0.jpg', 'Standing_One-Arm_Dumbbell_Curl_Over_Incline_Bench/1.jpg'],
    ),
    "Barbell_Curl": ExerciseDefinition(
        id="Barbell_Curl",
        display_name="Barbell Curl",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.FOREARMS],
        instructions="['Stand up with your torso upright while holding a barbell at a shoulder-width grip. The palm of your hands should be facing forward and the elbows should be close to the torso. This will be your starting position.', 'While holding the upper arms stationary, curl the weights forward while contracting the biceps as you breathe out. Tip: Only the forearms should move.', 'Continue the movement until your biceps are fully contracted and the bar is at shoulder level. Hold the contracted position for a second and squeeze the biceps hard.', 'Slowly begin to bring the bar back to starting position as your breathe in.', 'Repeat for the recommended amount of repetitions.']",
        images=['Barbell_Curl/0.jpg', 'Barbell_Curl/1.jpg'],
    ),
    "Alternate_Hammer_Curl": ExerciseDefinition(
        id="Alternate_Hammer_Curl",
        display_name="Alternate Hammer Curl",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        secondary_muscles=[MuscleGroup.FOREARMS],
        instructions="['Stand up with your torso upright and a dumbbell in each hand being held at arms length. The elbows should be close to the torso.', 'The palms of the hands should be facing your torso. This will be your starting position.', 'While holding the upper arm stationary, curl the right weight forward while contracting the biceps as you breathe out. Continue the movement until your biceps is fully contracted and the dumbbells are at shoulder level. Hold the contracted position for a second as you squeeze the biceps. Tip: Only the forearms should move.', 'Slowly begin to bring the dumbbells back to starting position as your breathe in.', 'Repeat the movement with the left hand. This equals one repetition.', 'Continue alternating in this manner for the recommended amount of repetitions.']",
        images=['Alternate_Hammer_Curl/0.jpg', 'Alternate_Hammer_Curl/1.jpg'],
    ),
    "Close-Grip_Standing_Barbell_Curl": ExerciseDefinition(
        id="Close-Grip_Standing_Barbell_Curl",
        display_name="Close-Grip Standing Barbell Curl",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.FOREARMS],
        instructions="['Hold a barbell with both hands, palms up and a few inches apart.', 'Stand with your torso straight and your head up. Your feet should be about shoulder width and your elbows close to your torso. This will be your starting position. Tip: You will keep your upper arms and elbows stationary throughout the movement.', 'Curl the bar up in a semicircular motion until the forearms touch your biceps. Exhale as you perform this portion of the movement and contract your biceps hard for a second at the top. Tip: Avoid bending the back or using swinging motions as you lift the weight. Only the forearms should move.', 'Slowly go back down to the starting position as you inhale.', 'Repeat for the recommended amount of repetitions.']",
        images=['Close-Grip_Standing_Barbell_Curl/0.jpg', 'Close-Grip_Standing_Barbell_Curl/1.jpg'],
    ),
    "Zottman_Curl": ExerciseDefinition(
        id="Zottman_Curl",
        display_name="Zottman Curl",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        secondary_muscles=[MuscleGroup.FOREARMS],
        instructions="['Stand up with your torso upright and a dumbbell in each hand being held at arms length. The elbows should be close to the torso.', 'Make sure the palms of the hands are facing each other. This will be your starting position.', 'While holding the upper arm stationary, curl the weights while contracting the biceps as you breathe out. Only the forearms should move. Your wrist should rotate so that you have a supinated (palms up) grip. Continue the movement until your biceps are fully contracted and the dumbbells are at shoulder level.', 'Hold the contracted position for a second as you squeeze the biceps.', 'Now during the contracted position, rotate your wrist until you now have a pronated (palms facing down) grip with the thumb at a higher position than the pinky.', 'Slowly begin to bring the dumbbells back down using the pronated grip.', 'As the dumbbells close your thighs, start rotating the wrist so that you go back to a neutral (palms facing your body) grip.', 'Repeat for the recommended amount of repetitions.']",
        images=['Zottman_Curl/0.jpg', 'Zottman_Curl/1.jpg'],
    ),
    "One_Arm_Dumbbell_Preacher_Curl": ExerciseDefinition(
        id="One_Arm_Dumbbell_Preacher_Curl",
        display_name="One Arm Dumbbell Preacher Curl",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        instructions="['Grab a dumbbell with the right arm and place the upper arm on top of the preacher bench or the incline bench. The dumbbell should be held at shoulder length. This will be your starting position.', 'As you breathe in, slowly lower the dumbbell until your upper arm is extended and the biceps is fully stretched.', 'As you exhale, use the biceps to curl the weight up until your biceps is fully contracted and the dumbbell is at shoulder height. Again, remember that to ensure full contraction you need to bring that small finger higher than the thumb.', 'Squeeze the biceps hard for a second at the contracted position and repeat for the recommended amount of repetitions.', 'Switch arms and repeat the movement.']",
        images=['One_Arm_Dumbbell_Preacher_Curl/0.jpg', 'One_Arm_Dumbbell_Preacher_Curl/1.jpg'],
    ),
    "Lying_High_Bench_Barbell_Curl": ExerciseDefinition(
        id="Lying_High_Bench_Barbell_Curl",
        display_name="Lying High Bench Barbell Curl",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.BARBELL,
        instructions="['Lie face forward on a tall flat bench while holding a barbell with a supinated grip (palms facing up). Tip: If you are holding a barbell grab it using a shoulder-width grip and if you are using an E-Z Bar grab it on the inner handles. Your upper body should be positioned in a way that the upper chest is over the end of the bench and the barbell is hanging in front of you with the arms extended and perpendicular to the floor. This will be your starting position.', 'While keeping the elbows in and the upper arms stationary, curl the weight up in a semi-circular motion as you contract the biceps and exhale. Hold at the top of the movement for a second.', 'As you inhale, slowly go back to the starting position. Tip: Maintain full control of the weight at all times and avoid any swinging. Remember, only the forearms should move throughout the movement.', 'Repeat for the recommended amount of repetitions.']",
        images=['Lying_High_Bench_Barbell_Curl/0.jpg', 'Lying_High_Bench_Barbell_Curl/1.jpg'],
    ),
    "Cross_Body_Hammer_Curl": ExerciseDefinition(
        id="Cross_Body_Hammer_Curl",
        display_name="Cross Body Hammer Curl",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        secondary_muscles=[MuscleGroup.FOREARMS],
        instructions="['Stand up straight with a dumbbell in each hand. Your hands should be down at your side with your palms facing in.', 'While keeping your palms facing in and without twisting your arm, curl the dumbbell of the right arm up towards your left shoulder as you exhale. Touch the top of the dumbbell to your shoulder and hold the contraction for a second.', 'Slowly lower the dumbbell along the same path as you inhale and then repeat the same movement for the left arm.', 'Continue alternating in this fashion until the recommended amount of repetitions is performed for each arm.']",
        images=['Cross_Body_Hammer_Curl/0.jpg', 'Cross_Body_Hammer_Curl/1.jpg'],
    ),
    "High_Cable_Curls": ExerciseDefinition(
        id="High_Cable_Curls",
        display_name="High Cable Curls",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.CABLE,
        instructions="['Stand between a couple of high pulleys and grab a handle in each arm. Position your upper arms in a way that they are parallel to the floor with the palms of your hands facing you. This will be your starting position.', 'Curl the handles towards you until they are next to your ears. Make sure that as you do so you flex your biceps and exhale. The upper arms should remain stationary and only the forearms should move. Hold for a second in the contracted position as you squeeze the biceps.', 'Slowly bring back the arms to the starting position.', 'Repeat for the recommended amount of repetitions.']",
        images=['High_Cable_Curls/0.jpg', 'High_Cable_Curls/1.jpg'],
    ),
    "Standing_Biceps_Stretch": ExerciseDefinition(
        id="Standing_Biceps_Stretch",
        display_name="Standing Biceps Stretch",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.STATIC,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.OTHER,
        secondary_muscles=[MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
        instructions="['Clasp your hands behind your back with your palms together, straighten arms and then rotate them so your palms face downward.', 'Raise your arms up and hold until you feel a stretch in your biceps.']",
        images=['Standing_Biceps_Stretch/0.jpg', 'Standing_Biceps_Stretch/1.jpg'],
    ),
    "Dumbbell_Bicep_Curl": ExerciseDefinition(
        id="Dumbbell_Bicep_Curl",
        display_name="Dumbbell Bicep Curl",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        secondary_muscles=[MuscleGroup.FOREARMS],
        instructions="""["Stand up straight with a dumbbell in each hand at arm's length. Keep your elbows close to your torso and rotate the palms of your hands until they are facing forward. This will be your starting position.", 'Now, keeping the upper arms stationary, exhale and curl the weights while contracting your biceps. Continue to raise the weights until your biceps are fully contracted and the dumbbells are at shoulder level. Hold the contracted position for a brief pause as you squeeze your biceps.', 'Then, inhale and slowly begin to lower the dumbbells back to the starting position.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Dumbbell_Bicep_Curl/0.jpg', 'Dumbbell_Bicep_Curl/1.jpg'],
    ),
    "Two-Arm_Dumbbell_Preacher_Curl": ExerciseDefinition(
        id="Two-Arm_Dumbbell_Preacher_Curl",
        display_name="Two-Arm Dumbbell Preacher Curl",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        instructions="['Grab a dumbbell with each arm and place the upper arms on top of the preacher bench or the incline bench. The dumbbell should be held at shoulder length. This will be your starting position.', 'As you breathe in, slowly lower the dumbbells until your upper arm is extended and the biceps is fully stretched.', 'As you exhale, use the biceps to curl the weights up until your biceps is fully contracted and the dumbbells are at shoulder height.', 'Squeeze the biceps hard for a second at the contracted position and repeat for the recommended amount of repetitions.']",
        images=['Two-Arm_Dumbbell_Preacher_Curl/0.jpg', 'Two-Arm_Dumbbell_Preacher_Curl/1.jpg'],
    ),
    "Seated_Dumbbell_Inner_Biceps_Curl": ExerciseDefinition(
        id="Seated_Dumbbell_Inner_Biceps_Curl",
        display_name="Seated Dumbbell Inner Biceps Curl",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        instructions="['Sit on the end of a flat bench with a dumbbell in each hand being held at arms length. The elbows should be close to the torso.', 'Rotate the palms of the hands so that they are facing inward in a neutral position. This will be your starting position.', 'While holding the upper arms stationary, curl the dumbbells out and up, turning the palms out as you lift and keeping your forearms in line with your outer deltoids. Tips:', 'Only the forearms should move. Continue the movement until your biceps are fully contracted and the dumbbells are at shoulder level. Hold the contracted position for a second as you squeeze the biceps.', 'Slowly begin to bring the dumbbells back to the starting position as your breathe in. Remember to rotate your arms as you lower the dumbbells so that you can switch back to a neutral grip.', 'Repeat for the recommended amount of repetitions.']",
        images=['Seated_Dumbbell_Inner_Biceps_Curl/0.jpg', 'Seated_Dumbbell_Inner_Biceps_Curl/1.jpg'],
    ),
    "Dumbbell_Alternate_Bicep_Curl": ExerciseDefinition(
        id="Dumbbell_Alternate_Bicep_Curl",
        display_name="Dumbbell Alternate Bicep Curl",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        secondary_muscles=[MuscleGroup.FOREARMS],
        instructions="['Stand (torso upright) with a dumbbell in each hand held at arms length. The elbows should be close to the torso and the palms of your hand should be facing your thighs.', 'While holding the upper arm stationary, curl the right weight as you rotate the palm of the hands until they are facing forward. At this point continue contracting the biceps as you breathe out until your biceps is fully contracted and the dumbbells are at shoulder level. Hold the contracted position for a second as you squeeze the biceps. Tip: Only the forearms should move.', 'Slowly begin to bring the dumbbell back to the starting position as your breathe in. Tip: Remember to twist the palms back to the starting position (facing your thighs) as you come down.', 'Repeat the movement with the left hand. This equals one repetition.', 'Continue alternating in this manner for the recommended amount of repetitions.']",
        images=['Dumbbell_Alternate_Bicep_Curl/0.jpg', 'Dumbbell_Alternate_Bicep_Curl/1.jpg'],
    ),
    "Barbell_Curls_Lying_Against_An_Incline": ExerciseDefinition(
        id="Barbell_Curls_Lying_Against_An_Incline",
        display_name="Barbell Curls Lying Against An Incline",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.BARBELL,
        instructions="['Lie against an incline bench, with your arms holding a barbell and hanging down in a horizontal line. This will be your starting position.', 'While keeping the upper arms stationary, curl the weight up as high as you can while squeezing the biceps. Breathe out as you perform this portion of the movement. Tip: Only the forearms should move. Do not swing the arms.', 'After a second contraction, slowly go back to the starting position as you inhale. Tip: Make sure that you go all of the way down.', 'Repeat for the recommended amount of repetitions.']",
        images=['Barbell_Curls_Lying_Against_An_Incline/0.jpg', 'Barbell_Curls_Lying_Against_An_Incline/1.jpg'],
    ),
    "Zottman_Preacher_Curl": ExerciseDefinition(
        id="Zottman_Preacher_Curl",
        display_name="Zottman Preacher Curl",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        secondary_muscles=[MuscleGroup.FOREARMS],
        instructions="['Grab a dumbbell in each hand and place your upper arms on top of the preacher bench or the incline bench. The dumbbells should be held at shoulder height and the elbows should be flexed. Hold the dumbbells with the palms of your hands facing down. This will be your starting position.', 'As you breathe in, slowly lower the dumbbells keeping the palms down until your upper arm is extended and your biceps are fully stretched.', 'Now rotate your wrists once you are at the bottom of the movement so that the palms of the hands are facing up.', 'As you exhale, use your biceps to curl the weights up until they are fully contracted and the dumbbells are at shoulder height. Again, remember that to ensure full contraction you need to bring that small finger higher than the thumb.', 'Squeeze the biceps hard for a second at the contracted position and rotate your wrists so that the palms are facing down again.', 'Repeat for the recommended amount of repetitions.']",
        images=['Zottman_Preacher_Curl/0.jpg', 'Zottman_Preacher_Curl/1.jpg'],
    ),
    "Standing_Concentration_Curl": ExerciseDefinition(
        id="Standing_Concentration_Curl",
        display_name="Standing Concentration Curl",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        secondary_muscles=[MuscleGroup.FOREARMS],
        instructions="['Taking a dumbbell in your working hand, lean forward. Allow your working arm to hang perpendicular to the ground with the elbow pointing out. This will be your starting position.', 'Flex the elbow to curl the weight, keeping the upper arm stationary. At the top of the repetition, flex the biceps and pause.', 'Lower the dumbbell back to the starting position.', 'Repeat the movement for the prescribed amount of repetitions.']",
        images=['Standing_Concentration_Curl/0.jpg', 'Standing_Concentration_Curl/1.jpg'],
    ),
    "Seated_Biceps": ExerciseDefinition(
        id="Seated_Biceps",
        display_name="Seated Biceps",
        level=LevelType.EXPERT,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.STATIC,
        mechanics_type=MechanicsType.ISOLATION,
        secondary_muscles=[MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
        instructions="['Sit on the floor with your knees bent and your partner standing behind you. Extend your arms straight behind you with your palms facing each other. Your partner will hold your wrists for you. This will be the starting position.', 'Attempt to flex your elbows, while your partner prevents any actual movement.', 'After 10-20 seconds, relax your arms while your partner gently pulls your wrists up to stretch your biceps. Be sure to let your partner know when the stretch is appropriate to prevent injury or overstretching.']",
        images=['Seated_Biceps/0.jpg', 'Seated_Biceps/1.jpg'],
    ),
    "Brachialis-SMR": ExerciseDefinition(
        id="Brachialis-SMR",
        display_name="Brachialis-SMR",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.STATIC,
        instructions="['Lie on your side, with your upper arm against the foam roller. The upper arm should be more or less aligned with your body, with the outside of the bicep pressed against the foam roller.', 'Raise your hips off of the floor, supporting your weight on your arm and on your feet. Hold for 10-30 seconds, and then switch sides.']",
        images=['Brachialis-SMR/0.jpg', 'Brachialis-SMR/1.jpg'],
    ),
    "Wide-Grip_Standing_Barbell_Curl": ExerciseDefinition(
        id="Wide-Grip_Standing_Barbell_Curl",
        display_name="Wide-Grip Standing Barbell Curl",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.BARBELL,
        instructions="['Stand up with your torso upright while holding a barbell at the wide outer handle. The palm of your hands should be facing forward. The elbows should be close to the torso. This will be your starting position.', 'While holding the upper arms stationary, curl the weights forward while contracting the biceps as you breathe out. Tip: Only the forearms should move.', 'Continue the movement until your biceps are fully contracted and the bar is at shoulder level. Hold the contracted position for a second and squeeze the biceps hard.', 'Slowly begin to bring the bar back to starting position as your breathe in.', 'Repeat for the recommended amount of repetitions.']",
        images=['Wide-Grip_Standing_Barbell_Curl/0.jpg', 'Wide-Grip_Standing_Barbell_Curl/1.jpg'],
    ),
    "Flexor_Incline_Dumbbell_Curls": ExerciseDefinition(
        id="Flexor_Incline_Dumbbell_Curls",
        display_name="Flexor Incline Dumbbell Curls",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        instructions="['Hold the dumbbell towards the side farther from you so that you have more weight on the side closest to you. (This can be done for a good effect on all bicep dumbbell exercises). Now do a normal incline dumbbell curl, but keep your wrists as far back as possible so as to neutralize any stress that is placed on them.', 'Sit on an incline bench that is angled at 45-degrees while holding a dumbbell on each hand.', 'Let your arms hang down on your sides, with the elbows in, and turn the palms of your hands forward with the thumbs pointing away from the body. Tip: You will keep this hand position throughout the movement as there should not be any twisting of the hands as they come up. This will be your starting position.', 'Curl up the two dumbbells at the same time until your biceps are fully contracted and exhale. Tip: Do not swing the arms or use momentum. Keep a controlled motion at all times. Hold the contracted position for a second at the top.', 'As you inhale, slowly go back to the starting position.', 'Repeat for the recommended amount of repetitions.']",
        images=['Flexor_Incline_Dumbbell_Curls/0.jpg', 'Flexor_Incline_Dumbbell_Curls/1.jpg'],
    ),
    "Machine_Bicep_Curl": ExerciseDefinition(
        id="Machine_Bicep_Curl",
        display_name="Machine Bicep Curl",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.MACHINE,
        instructions="['Adjust the seat to the appropriate height and make your weight selection. Place your upper arms against the pads and grasp the handles. This will be your starting position.', 'Perform the movement by flexing the elbow, pulling your lower arm towards your upper arm.', 'Pause at the top of the movement, and then slowly return the weight to the starting position.', 'Avoid returning the weight all the way to the stops until the set is complete to keep tension on the muscles being worked.']",
        images=['Machine_Bicep_Curl/0.jpg', 'Machine_Bicep_Curl/1.jpg'],
    ),
    "Standing_Biceps_Cable_Curl": ExerciseDefinition(
        id="Standing_Biceps_Cable_Curl",
        display_name="Standing Biceps Cable Curl",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="['Stand up with your torso upright while holding a cable curl bar that is attached to a low pulley. Grab the cable bar at shoulder width and keep the elbows close to the torso. The palm of your hands should be facing up (supinated grip). This will be your starting position.', 'While holding the upper arms stationary, curl the weights while contracting the biceps as you breathe out. Only the forearms should move. Continue the movement until your biceps are fully contracted and the bar is at shoulder level. Hold the contracted position for a second as you squeeze the muscle.', 'Slowly begin to bring the curl bar back to starting position as your breathe in.', 'Repeat for the recommended amount of repetitions.']",
        images=['Standing_Biceps_Cable_Curl/0.jpg', 'Standing_Biceps_Cable_Curl/1.jpg'],
    ),
    "Incline_Inner_Biceps_Curl": ExerciseDefinition(
        id="Incline_Inner_Biceps_Curl",
        display_name="Incline Inner Biceps Curl",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        instructions="""['Hold a dumbbell in each hand and lie back on an incline bench.', "The dumbbells should be at arm's length hanging at your sides and your palms should be facing out. This will be your starting position.", 'Now as you exhale curl the weight outward and up while keeping your forearms in line with your side deltoids. Continue the curl until the dumbbells are at shoulder height and to the sides of your deltoids. Tip: The end of the movement should look similar to a double biceps pose.', 'After a second contraction at the top of the movement, start to inhale and slowly lower the weights back to the starting position using the same path used to bring them up.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Incline_Inner_Biceps_Curl/0.jpg', 'Incline_Inner_Biceps_Curl/1.jpg'],
    ),
    "Close-Grip_EZ_Bar_Curl": ExerciseDefinition(
        id="Close-Grip_EZ_Bar_Curl",
        display_name="Close-Grip EZ Bar Curl",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.FOREARMS],
        instructions="['Stand up with your torso upright while holding an E-Z Curl Bar at the closer inner handle. The palm of your hands should be facing forward and they should be slightly tilted inwards due to the shape of the bar. The elbows should be close to the torso. This will be your starting position.', 'While holding the upper arms stationary, curl the weights forward while contracting the biceps as you breathe out. Tip: Only the forearms should move.', 'Continue the movement until your biceps are fully contracted and the bar is at shoulder level. Hold the contracted position for a second and squeeze the biceps hard.', 'Slowly begin to bring the bar back to starting position as your breathe in.', 'Repeat for the recommended amount of repetitions.']",
        images=['Close-Grip_EZ_Bar_Curl/0.jpg', 'Close-Grip_EZ_Bar_Curl/1.jpg'],
    ),
    "Reverse_Cable_Curl": ExerciseDefinition(
        id="Reverse_Cable_Curl",
        display_name="Reverse Cable Curl",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        secondary_muscles=[MuscleGroup.FOREARMS],
        instructions="['Stand up with your torso upright while holding a bar attachment that is attached to a low pulley using a pronated (palms down) and shoulder width grip. Make sure also that you keep the elbows close to the torso. This will be your starting position.', 'While holding the upper arms stationary, curl the weights while contracting the biceps as you breathe out. Only the forearms should move. Continue the movement until your biceps are fully contracted and the bar is at shoulder level. Hold the contracted position for a second as you squeeze the muscle.', 'Slowly begin to bring the bar back to starting position as your breathe in.', 'Repeat for the recommended amount of repetitions.']",
        images=['Reverse_Cable_Curl/0.jpg', 'Reverse_Cable_Curl/1.jpg'],
    ),
    "Lying_Cable_Curl": ExerciseDefinition(
        id="Lying_Cable_Curl",
        display_name="Lying Cable Curl",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="['Grab a straight bar or E-Z bar attachment that is attached to the low pulley with both hands, using an underhand (palms facing up) shoulder-width grip.', 'Lie flat on your back on top of an exercise mat in front of the weight stack with your feet flat against the frame of the pulley machine and your legs straight.', 'With your arms extended and your elbows close to your body slightly bend your arms. This will be your starting position.', 'While keeping your upper arms stationary and the elbows close to your body, curl the bar up slowly toward your chest as you breathe out and you squeeze the biceps.', 'After a second squeeze at the top of the movement, slowly return to the starting position.', 'Repeat for the recommended amount of repetitions.']",
        images=['Lying_Cable_Curl/0.jpg', 'Lying_Cable_Curl/1.jpg'],
    ),
    "Standing_One-Arm_Cable_Curl": ExerciseDefinition(
        id="Standing_One-Arm_Cable_Curl",
        display_name="Standing One-Arm Cable Curl",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="['Start out by grabbing single handle next to the low pulley machine. Make sure you are far enough from the machine so that your arm is supporting the weight.', 'Make sure that your upper arm is stationary, perpendicular to the floor with elbows in and palms facing forward. Your non lifting arm should be grabbing your waist. This will allow you to keep your balance.', 'Slowly begin to curl the single handle upwards while keeping the upper arm stationary until your forearm touches your bicep while exhaling. Tip: Only the forearm should move.', 'Hold the contraction position as you squeeze the bicep and then lower the single handle back down to the starting position as you inhale.', 'Repeat for the recommended amount of repetitions.', 'Switch arms while performing this exercise.']",
        images=['Standing_One-Arm_Cable_Curl/0.jpg', 'Standing_One-Arm_Cable_Curl/1.jpg'],
    ),
    "Drag_Curl": ExerciseDefinition(
        id="Drag_Curl",
        display_name="Drag Curl",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.FOREARMS],
        instructions="""['Grab a barbell with a supinated grip (palms facing forward) and get your elbows close to your torso and back. This will be your starting position.', 'As you exhale, curl the bar up while keeping the elbows to the back as you "Drag" the bar up by keeping it in contact with your torso. Tip: As you can see, you will not be keeping the elbows pinned to your sides, but instead you will be bringing them back. Also, do not lift your shoulders.', 'Slowly go back to the starting position as you keep the bar in contact with the torso at all times.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Drag_Curl/0.jpg', 'Drag_Curl/1.jpg'],
    ),
    "Standing_Dumbbell_Reverse_Curl": ExerciseDefinition(
        id="Standing_Dumbbell_Reverse_Curl",
        display_name="Standing Dumbbell Reverse Curl",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        secondary_muscles=[MuscleGroup.FOREARMS],
        instructions="['To begin, stand straight with a dumbbell in each hand using a pronated grip (palms facing down). Your arms should be fully extended while your feet are shoulder width apart from each other. This is the starting position.', 'While holding the upper arms stationary, curl the weights while contracting the biceps as you breathe out. Only the forearms should move. Continue the movement until your biceps are fully contracted and the dumbbells are at shoulder level. Hold the contracted position for a second as you squeeze the muscle.', 'Slowly begin to bring the dumbbells back to starting position as your breathe in.', 'Repeat for the recommended amount of repetitions.']",
        images=['Standing_Dumbbell_Reverse_Curl/0.jpg', 'Standing_Dumbbell_Reverse_Curl/1.jpg'],
    ),
    "Seated_Dumbbell_Curl": ExerciseDefinition(
        id="Seated_Dumbbell_Curl",
        display_name="Seated Dumbbell Curl",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        instructions="['Sit on a flat bench with a dumbbell on each hand being held at arms length. The elbows should be close to the torso.', 'Rotate the palms of the hands so that they are facing your torso. This will be your starting position.', 'While holding the upper arm stationary, curl the weights and start twisting the wrists once the dumbbells pass your thighs so that the palms of your hands face forward at the end of the movement. Make sure that you contract the biceps as you breathe out and make sure that only the forearms move. Continue the movement until your biceps are fully contracted and the dumbbells are at shoulder level. Hold the contracted position for a second as you squeeze the biceps.', 'Slowly begin to bring the dumbbells back to the starting position as your breathe in and as you rotate the wrists back to a neutral grip.', 'Repeat for the recommended amount of repetitions.']",
        images=['Seated_Dumbbell_Curl/0.jpg', 'Seated_Dumbbell_Curl/1.jpg'],
    ),
    "Cable_Preacher_Curl": ExerciseDefinition(
        id="Cable_Preacher_Curl",
        display_name="Cable Preacher Curl",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        secondary_muscles=[MuscleGroup.FOREARMS],
        instructions="['Place a preacher bench about 2 feet in front of a pulley machine.', 'Attach a straight bar to the low pulley.', 'Sit at the preacher bench with your elbow and upper arms firmly on top of the bench pad and have someone hand you the bar from the low pulley.', 'Grab the bar and fully extend your arms on top of the preacher bench pad. This will be your starting position.', 'Now start pilling the weight up towards your shoulders and squeeze the biceps hard at the top of the movement. Exhale as you perform this motion. Also, hold for a second at the top.', 'Now slowly lower the weight to the starting position.', 'Repeat for the recommended amount of repetitions.']",
        images=['Cable_Preacher_Curl/0.jpg', 'Cable_Preacher_Curl/1.jpg'],
    ),
    "Overhead_Cable_Curl": ExerciseDefinition(
        id="Overhead_Cable_Curl",
        display_name="Overhead Cable Curl",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="['To begin, set a weight that is comfortable on each side of the pulley machine. Note: Make sure that the amount of weight selected is the same on each side.', 'Now adjust the height of the pulleys on each side and make sure that they are positioned at a height higher than that of your shoulders.', 'Stand in the middle of both sides and use an underhand grip (palms facing towards the ceiling) to grab each handle. Your arms should be fully extended and parallel to the floor with your feet positioned shoulder width apart from each other. Your body should be evenly aligned the handles. This is the starting position.', 'While exhaling, slowly squeeze the biceps on each side until your forearms and biceps touch.', 'While inhaling, move your forearms back to the starting position. Note: Your entire body is stationary during this exercise except for the forearms.', 'Repeat for the recommended amount of repetitions prescribed in your program.']",
        images=['Overhead_Cable_Curl/0.jpg', 'Overhead_Cable_Curl/1.jpg'],
    ),
    "Dumbbell_Prone_Incline_Curl": ExerciseDefinition(
        id="Dumbbell_Prone_Incline_Curl",
        display_name="Dumbbell Prone Incline Curl",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        instructions="['Grab a dumbbell on each hand and lie face down on an incline bench with your shoulders near top of the incline. Your knees can rest on the seat or your legs can be straddled to the sides (my preferred way).', 'Let your arms extend and hang naturally in front of you so that they are perpendicular to the floor.', 'Now keep your elbows in by your side and face the palms forward. This will be your starting position.', 'Raise the dumbbells by contracting the biceps until your arms are fully flexed. Exhale as you perform this portion of the movement and ensure that only the forearms move. The upper arms should remain stationary at all times.', 'Lower the dumbbells until your arms are fully extended.', 'Repeat for the recommended amount of times.']",
        images=['Dumbbell_Prone_Incline_Curl/0.jpg', 'Dumbbell_Prone_Incline_Curl/1.jpg'],
    ),
    "Close-Grip_EZ-Bar_Curl_with_Band": ExerciseDefinition(
        id="Close-Grip_EZ-Bar_Curl_with_Band",
        display_name="Close-Grip EZ-Bar Curl with Band",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        secondary_muscles=[MuscleGroup.FOREARMS],
        instructions="['Attach a band to each end of the bar. Take the bar, placing a foot on the middle of the band. Stand upright with a narrow, supinated grip on the EZ bar. The elbows should be close to the torso. This will be your starting position.', 'While keeping the upper arms in place, flex the elbows to execute the curl. Exhale as the weight is lifted.', 'Continue the movement until your biceps are fully contracted and the bar is at shoulder level. Hold the contracted position for a second and squeeze the biceps hard.', 'Slowly begin to bring the bar back to starting position as your breathe in.', 'Repeat for the recommended amount of repetitions.']",
        images=['Close-Grip_EZ-Bar_Curl_with_Band/0.jpg', 'Close-Grip_EZ-Bar_Curl_with_Band/1.jpg'],
    ),
    "EZ-Bar_Curl": ExerciseDefinition(
        id="EZ-Bar_Curl",
        display_name="EZ-Bar Curl",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        instructions="['Stand up straight while holding an EZ curl bar at the wide outer handle. The palms of your hands should be facing forward and slightly tilted inward due to the shape of the bar. Keep your elbows close to your torso. This will be your starting position.', 'Now, while keeping your upper arms stationary, exhale and curl the weights forward while contracting the biceps. Focus on only moving your forearms.', 'Continue to raise the weight until your biceps are fully contracted and the bar is at shoulder level. Hold the top contracted position for a moment and squeeze the biceps.', 'Then inhale and slowly lower the bar back to the starting position.', 'Repeat for the recommended amount of repetitions.']",
        images=['EZ-Bar_Curl/0.jpg', 'EZ-Bar_Curl/1.jpg'],
    ),
    "Concentration_Curls": ExerciseDefinition(
        id="Concentration_Curls",
        display_name="Concentration Curls",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        secondary_muscles=[MuscleGroup.FOREARMS],
        instructions="['Sit down on a flat bench with one dumbbell in front of you between your legs. Your legs should be spread with your knees bent and feet on the floor.', 'Use your right arm to pick the dumbbell up. Place the back of your right upper arm on the top of your inner right thigh. Rotate the palm of your hand until it is facing forward away from your thigh. Tip: Your arm should be extended and the dumbbell should be above the floor. This will be your starting position.', 'While holding the upper arm stationary, curl the weights forward while contracting the biceps as you breathe out. Only the forearms should move. Continue the movement until your biceps are fully contracted and the dumbbells are at shoulder level. Tip: At the top of the movement make sure that the little finger of your arm is higher than your thumb. This guarantees a good contraction. Hold the contracted position for a second as you squeeze the biceps.', 'Slowly begin to bring the dumbbells back to starting position as your breathe in. Caution: Avoid swinging motions at any time.', 'Repeat for the recommended amount of repetitions. Then repeat the movement with the left arm.']",
        images=['Concentration_Curls/0.jpg', 'Concentration_Curls/1.jpg'],
    ),
    "Reverse_Plate_Curls": ExerciseDefinition(
        id="Reverse_Plate_Curls",
        display_name="Reverse Plate Curls",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.OTHER,
        secondary_muscles=[MuscleGroup.FOREARMS],
        instructions="""["Start by standing straight with a weighted plate held by both hands and arms fully extended. Use a pronated grip (palms facing down) and make sure your fingers grab the rough side of the plate while your thumb grabs the smooth side. Note: For the best results, grab the weighted plate at an 11:00 and 1:00 o'clock position.", 'Your feet should be shoulder width apart from each other and the weighted plate should be near the groin area. This is the starting position.', 'Slowly lift the plate up while keeping the elbows in and the upper arms stationary until your biceps and forearms touch while exhaling. The plate should be evenly aligned with your torso at this point.', 'Feel the contraction for a second and begin to lower the weight back down to the starting position while inhaling', 'Repeat for the recommended amount of repetitions.']""",
        images=['Reverse_Plate_Curls/0.jpg', 'Reverse_Plate_Curls/1.jpg'],
    ),
    "Biceps_Chin_Up": ExerciseDefinition(
        id="Biceps_Chin_Up",
        display_name="Biceps Chin Up",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        secondary_muscles=[MuscleGroup.FOREARMS],
        instructions="['To do bicep-focused chin-ups, use an underhand grip (palms facing you), hands shoulder-width apart, and pull up by driving elbows down, aiming to bring your chin over the bar while keeping elbows slightly forward to emphasize the bicep, then lower with control for a full stretch, ensuring your entire body stays stable. Focus on pulling with your biceps and getting a strong contraction at the top to build muscle, rather than just moving your body up.']",
        images=[],
    ),
}
