from exercises.base import ExerciseDefinition
from enums import MuscleGroup, EquipmentType, MechanicsType, MajorMuscleGroup, ForceType, LevelType, CategoryType

BOULDERING_EXERCISES = {
    "bouldering_Vb": ExerciseDefinition(
        id="bouldering_Vb",
        display_name="Bouldering Vb",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BOULDERING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CLIMBING_WALL,
        instructions="""['bouldering']""",
        images=[],
    ),

    "bouldering_V0": ExerciseDefinition(
        id="bouldering_V0",
        display_name="Bouldering V0",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BOULDERING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CLIMBING_WALL,
        instructions="""['bouldering']""",
        images=[],
    ),
    "bouldering_V1": ExerciseDefinition(
        id="bouldering_V1",
        display_name="Bouldering V1",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BOULDERING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CLIMBING_WALL,
        instructions="""['bouldering']""",
        images=[],
    ),
    "bouldering_V2": ExerciseDefinition(
        id="bouldering_V2",
        display_name="Bouldering V2",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BOULDERING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CLIMBING_WALL,
        instructions="""['bouldering']""",
        images=[],
    ),
    "bouldering_V3": ExerciseDefinition(
        id="bouldering_V3",
        display_name="Bouldering V3",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BOULDERING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CLIMBING_WALL,
        instructions="""['bouldering']""",
        images=[],
    ),
    "bouldering_V4": ExerciseDefinition(
        id="bouldering_V4",
        display_name="Bouldering V4",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BOULDERING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CLIMBING_WALL,
        instructions="""['bouldering']""",
        images=[],
    ),
    "bouldering_V5": ExerciseDefinition(
        id="bouldering_V5",
        display_name="Bouldering V5",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BOULDERING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CLIMBING_WALL,
        instructions="""['bouldering']""",
        images=[],
    ),
    "bouldering_V6": ExerciseDefinition(
        id="bouldering_V6",
        display_name="Bouldering V6",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BOULDERING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CLIMBING_WALL,
        instructions="""['bouldering']""",
        images=[],
    ),
    "bouldering_V7": ExerciseDefinition(
        id="bouldering_V7",
        display_name="Bouldering V7",
        level=LevelType.ADVANCED,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BOULDERING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CLIMBING_WALL,
        instructions="""['bouldering']""",
        images=[],
    ),
    "bouldering_V8": ExerciseDefinition(
        id="bouldering_V8",
        display_name="Bouldering V8",
        level=LevelType.ADVANCED,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BOULDERING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CLIMBING_WALL,
        instructions="""['bouldering']""",
        images=[],
    ),
    "bouldering_V9": ExerciseDefinition(
        id="bouldering_V9",
        display_name="Bouldering V9",
        level=LevelType.ADVANCED,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BOULDERING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CLIMBING_WALL,
        instructions="""['bouldering']""",
        images=[],
    ),
    "bouldering_V10": ExerciseDefinition(
        id="bouldering_V10",
        display_name="Bouldering V10",
        level=LevelType.EXPERT,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BOULDERING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CLIMBING_WALL,
        instructions="""['bouldering']""",
        images=[],
    ),
    "bouldering_V11": ExerciseDefinition(
        id="bouldering_V11",
        display_name="Bouldering V11",
        level=LevelType.EXPERT,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BOULDERING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CLIMBING_WALL,
        instructions="""['bouldering']""",
        images=[],
    ),
    "bouldering_V12": ExerciseDefinition(
        id="bouldering_V12",
        display_name="Bouldering V12",
        level=LevelType.EXPERT,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BOULDERING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CLIMBING_WALL,
        instructions="""['bouldering']""",
        images=[],
    ),
    "bouldering_V13": ExerciseDefinition(
        id="bouldering_V13",
        display_name="Bouldering V13",
        level=LevelType.EXPERT,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BOULDERING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CLIMBING_WALL,
        instructions="""['bouldering']""",
        images=[],
    ),
    "bouldering_V14": ExerciseDefinition(
        id="bouldering_V14",
        display_name="Bouldering V14",
        level=LevelType.JEDI,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BOULDERING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CLIMBING_WALL,
        instructions="""['bouldering']""",
        images=[],
    ),
    "bouldering_V15": ExerciseDefinition(
        id="bouldering_V15",
        display_name="Bouldering V15",
        level=LevelType.JEDI,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BOULDERING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CLIMBING_WALL,
        instructions="""['bouldering']""",
        images=[],
    ),
    "bouldering_V16": ExerciseDefinition(
        id="bouldering_V16",
        display_name="Bouldering V16",
        level=LevelType.JEDI,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BOULDERING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CLIMBING_WALL,
        instructions="""['bouldering']""",
        images=[],
    ),
    "bouldering_V17": ExerciseDefinition(
        id="bouldering_V17",
        display_name="Bouldering V17",
        level=LevelType.CLIMBING_DEMI_GOD,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.BOULDERING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CLIMBING_WALL,
        instructions="""['bouldering']""",
        images=[],
    ),
}
