from exercises.base import ExerciseDefinition
from enums import MuscleGroup, EquipmentType, MechanicsType, MajorMuscleGroup, ForceType, LevelType, CategoryType

CALVES_EXERCISES = {
    "Peroneals-SMR": ExerciseDefinition(
        id="Peroneals-SMR",
        display_name="Peroneals-SMR",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.CALVES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.STATIC,
        instructions="['Lay on your side, supporting your weight on your forearm and on a foam roller placed on the outside of your lower leg. Your upper leg can either be on top of your lower leg, or you can cross it in front of you. This will be your starting position.', 'Raise your hips off of the ground and begin to roll from below the knee to above the ankle on the side of your leg, pausing at points of tension for 10-30 seconds. Repeat on the other leg.']",
        images=['Peroneals-SMR/0.jpg', 'Peroneals-SMR/1.jpg'],
    ),
    "Rocking_Standing_Calf_Raise": ExerciseDefinition(
        id="Rocking_Standing_Calf_Raise",
        display_name="Rocking Standing Calf Raise",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.CALVES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.BARBELL,
        instructions="['This exercise is best performed inside a squat rack for safety purposes. To begin, first set the bar on a rack that best matches your height. Once the correct height is chosen and the bar is loaded, step under the bar and place it on the back of your shoulders (slightly below the neck).', 'Hold on to the bar using both arms at each side and lift it off the rack by first pushing with your legs and at the same time straightening your torso.', 'Step away from the rack and position your legs using a shoulder width medium stance with the toes slightly pointed out. Keep your head up at all times as looking down will get you off balance. Also maintain a straight back and keep the knees with a slight bend; never locked. This will be your starting position.', 'Raise your heels as you breathe out by extending your ankles as high as possible and flexing your calf. Ensure that the knee is kept stationary at all times. There should be no bending (other than the slight initial bend we created during positioning) at any time. Hold the contracted position by a second before you start to go back down.', 'Go back slowly to the starting position as you breathe in by lowering your heels as you bend the ankles until calves are stretched.', 'Now lift your toes by contracting the tibia muscles in the front of the calves as you breathe out.', 'Hold for a second and bring them back down as you breathe in.', 'Repeat for the recommended amount of repetitions.']",
        images=['Rocking_Standing_Calf_Raise/0.jpg', 'Rocking_Standing_Calf_Raise/1.jpg'],
    ),
    "Calf_Raise_On_A_Dumbbell": ExerciseDefinition(
        id="Calf_Raise_On_A_Dumbbell",
        display_name="Calf Raise On A Dumbbell",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.CALVES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        instructions="['Hang on to a sturdy object for balance and stand on a dumbbell handle, preferably one with round plates so that it rolls as in this manner you have to work harder to stabilize yourself; thus increasing the effectiveness of the exercise.', 'Now roll your foot slightly forward so that you can get a nice stretch of the calf. This will be your starting position.', 'Lift the calf as you roll your foot over the top of the handle so that you get a full extension. Exhale during the execution of this movement. Contract the calf hard at the top and hold for a second. Tip: As you come up, roll the dumbbell slightly backward.', 'Now inhale as you roll the dumbbell slightly forward as you come down to get a better stretch.', 'Repeat for the recommended amount of repetitions.']",
        images=['Calf_Raise_On_A_Dumbbell/0.jpg', 'Calf_Raise_On_A_Dumbbell/1.jpg'],
    ),
    "Standing_Barbell_Calf_Raise": ExerciseDefinition(
        id="Standing_Barbell_Calf_Raise",
        display_name="Standing Barbell Calf Raise",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.CALVES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.BARBELL,
        instructions="['This exercise is best performed inside a squat rack for safety purposes. To begin, first set the bar on a rack that best matches your height. Once the correct height is chosen and the bar is loaded, step under the bar and place the bar on the back of your shoulders (slightly below the neck).', 'Hold on to the bar using both arms at each side and lift it off the rack by first pushing with your legs and at the same time straightening your torso.', 'Step away from the rack and position your legs using a shoulder width medium stance with the toes slightly pointed out. Keep your head up at all times as looking down will get you off balance and also maintain a straight back. The knees should be kept with a slight bend; never locked. This will be your starting position. Tip: For better range of motion you may also place the ball of your feet on a wooden block but be careful as this option requires more balance and a sturdy block.', 'Raise your heels as you breathe out by extending your ankles as high as possible and flexing your calf. Ensure that the knee is kept stationary at all times. There should be no bending at any time. Hold the contracted position by a second before you start to go back down.', 'Go back slowly to the starting position as you breathe in by lowering your heels as you bend the ankles until calves are stretched.', 'Repeat for the recommended amount of repetitions.']",
        images=['Standing_Barbell_Calf_Raise/0.jpg', 'Standing_Barbell_Calf_Raise/1.jpg'],
    ),
    "Barbell_Seated_Calf_Raise": ExerciseDefinition(
        id="Barbell_Seated_Calf_Raise",
        display_name="Barbell Seated Calf Raise",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.CALVES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.BARBELL,
        instructions="['Place a block about 12 inches in front of a flat bench.', 'Sit on the bench and place the ball of your feet on the block.', 'Have someone place a barbell over your upper thighs about 3 inches above your knees and hold it there. This will be your starting position.', 'Raise up on your toes as high as possible as you squeeze the calves and as you breathe out.', 'After a second contraction, slowly go back to the starting position. Tip: To get maximum benefit stretch your calves as far as you can.', 'Repeat for the recommended amount of repetitions.']",
        images=['Barbell_Seated_Calf_Raise/0.jpg', 'Barbell_Seated_Calf_Raise/1.jpg'],
    ),
    "Anterior_Tibialis-SMR": ExerciseDefinition(
        id="Anterior_Tibialis-SMR",
        display_name="Anterior Tibialis-SMR",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.CALVES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.STATIC,
        equipment_type=EquipmentType.OTHER,
        instructions="['Begin seated on the ground with your legs bent and your feet on the floor.', 'Using a Muscle Roller or a rolling pin, apply pressure to the muscles on the outside of your shins. Work from just below the knee to above the ankle, pausing at points of tension for 10-30 seconds. Repeat on the other leg.']",
        images=['Anterior_Tibialis-SMR/0.jpg', 'Anterior_Tibialis-SMR/1.jpg'],
    ),
    "Peroneals_Stretch": ExerciseDefinition(
        id="Peroneals_Stretch",
        display_name="Peroneals Stretch",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.CALVES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.STATIC,
        equipment_type=EquipmentType.OTHER,
        instructions="['In a seated position, loop a belt, rope, or band around one foot. This will be your starting position.', 'With the leg extended and the heel off of the ground, pull on the belt so that the foot is inverted, with the inside of the foot being pulled towards you. Hold for 10-20 seconds, and then switch sides.']",
        images=['Peroneals_Stretch/0.jpg', 'Peroneals_Stretch/1.jpg'],
    ),
    "Calf_Stretch_Elbows_Against_Wall": ExerciseDefinition(
        id="Calf_Stretch_Elbows_Against_Wall",
        display_name="Calf Stretch Elbows Against Wall",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.CALVES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.STATIC,
        mechanics_type=MechanicsType.ISOLATION,
        instructions="['Stand facing a wall from a couple feet away.', 'Lean against the wall, placing your weight on your forearms.', 'Attempt to keep your heels on the ground. Hold for 10-20 seconds. You may move further or closer the wall, making it more or less difficult, respectively.']",
        images=['Calf_Stretch_Elbows_Against_Wall/0.jpg', 'Calf_Stretch_Elbows_Against_Wall/1.jpg'],
    ),
    "Standing_Soleus_And_Achilles_Stretch": ExerciseDefinition(
        id="Standing_Soleus_And_Achilles_Stretch",
        display_name="Standing Soleus And Achilles Stretch",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.CALVES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.STATIC,
        mechanics_type=MechanicsType.ISOLATION,
        instructions="['Stand with your feet hip-distance apart, one foot slightly in front of the other.', 'Bend both knees, keeping your back heel on the floor. Switch sides.']",
        images=['Standing_Soleus_And_Achilles_Stretch/0.jpg', 'Standing_Soleus_And_Achilles_Stretch/1.jpg'],
    ),
    "Dumbbell_Seated_One-Leg_Calf_Raise": ExerciseDefinition(
        id="Dumbbell_Seated_One-Leg_Calf_Raise",
        display_name="Dumbbell Seated One-Leg Calf Raise",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.CALVES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        instructions="['Place a block on the floor about 12 inches from a flat bench.', 'Sit on a flat bench and place a dumbbell on your upper left thigh about 3 inches above your knee.', 'Now place the ball of your left foot on the block. This will be your starting position.', 'Raise your toes up as high as possible as you exhale and you contract your calf muscle. Hold the contraction for a second.', 'Slowly return to the starting position, stretching as far down as possible.', 'Repeat for your prescribed number of repetitions and then repeat with the right leg.']",
        images=['Dumbbell_Seated_One-Leg_Calf_Raise/0.jpg', 'Dumbbell_Seated_One-Leg_Calf_Raise/1.jpg'],
    ),
    "Smith_Machine_Reverse_Calf_Raises": ExerciseDefinition(
        id="Smith_Machine_Reverse_Calf_Raises",
        display_name="Smith Machine Reverse Calf Raises",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.CALVES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.MACHINE,
        instructions="['Adjust the barbell on the smith machine to fit your height and align a raised platform right under the bar.', 'Stand on the platform with the heels of your feet secured on top of it with the balls of your feet extending off it. Position your toes facing forward with a shoulder width stance.', 'Now, place your shoulders under the barbell while maintaining the foot positioning described and push the barbell up by extending your hips and knees until your torso is standing erect. The knees should be kept with a slight bend; never locked. This will be your starting position. Tip: The barbell on your back is only for balance purposes.', 'Raise the balls of your feet as you breathe out by extending your toes as high as possible and flexing your calf. Ensure that the knee is kept stationary at all times. There should be no bending at any time. Hold the contracted position for a second before you start to go back down.', 'Slowly go back down to the starting position as you breathe in by lowering the balls of your feet and toes.', 'Repeat for the recommended amount of repetitions.']",
        images=['Smith_Machine_Reverse_Calf_Raises/0.jpg', 'Smith_Machine_Reverse_Calf_Raises/1.jpg'],
    ),
    "Calf_Press_On_The_Leg_Press_Machine": ExerciseDefinition(
        id="Calf_Press_On_The_Leg_Press_Machine",
        display_name="Calf Press On The Leg Press Machine",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.CALVES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.MACHINE,
        instructions="['Using a leg press machine, sit down on the machine and place your legs on the platform directly in front of you at a medium (shoulder width) foot stance.', 'Lower the safety bars holding the weighted platform in place and press the platform all the way up until your legs are fully extended in front of you without locking your knees. (Note: In some leg press units you can leave the safety bars on for increased safety. If your leg press unit allows for this, then this is the preferred method of performing the exercise.) Your torso and the legs should make perfect 90-degree angle. Now carefully place your toes and balls of your feet on the lower portion of the platform with the heels extending off. Toes should be facing forward, outwards or inwards as described at the beginning of the chapter. This will be your starting position.', 'Press on the platform by raising your heels as you breathe out by extending your ankles as high as possible and flexing your calf. Ensure that the knee is kept stationary at all times. There should be no bending at any time. Hold the contracted position by a second before you start to go back down.', 'Go back slowly to the starting position as you breathe in by lowering your heels as you bend the ankles until calves are stretched.', 'Repeat for the recommended amount of repetitions.']",
        images=['Calf_Press_On_The_Leg_Press_Machine/0.jpg', 'Calf_Press_On_The_Leg_Press_Machine/1.jpg'],
    ),
    "Seated_Calf_Stretch": ExerciseDefinition(
        id="Seated_Calf_Stretch",
        display_name="Seated Calf Stretch",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.CALVES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.STATIC,
        secondary_muscles=[MuscleGroup.HAMSTRINGS, MuscleGroup.LOWER_BACK],
        instructions="['Sit up straight on an exercise mat.', 'Bend one knee and put that foot on the floor to stabilize the torso.', 'Straighten your other leg and flex your ankle.', 'Using a band, towel, or your hand if you can reach, pull the toes toward you. Hold for 10 to 20 seconds, then switch sides.']",
        images=['Seated_Calf_Stretch/0.jpg', 'Seated_Calf_Stretch/1.jpg'],
    ),
    "Knee_Circles": ExerciseDefinition(
        id="Knee_Circles",
        display_name="Knee Circles",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.CALVES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.HAMSTRINGS, MuscleGroup.QUADS],
        instructions="['Stand with your legs together and hands by your waist.', 'Now move your knees in a circular motion as you breathe normally.', 'Repeat for the recommended amount of repetitions.']",
        images=['Knee_Circles/0.jpg', 'Knee_Circles/1.jpg'],
    ),
    "Smith_Machine_Calf_Raise": ExerciseDefinition(
        id="Smith_Machine_Calf_Raise",
        display_name="Smith Machine Calf Raise",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.CALVES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.MACHINE,
        instructions="['Place a block or weight plate below the bar on the Smith machine. Set the bar to a position that best matches your height. Once the correct height is chosen and the bar is loaded, step onto the plates with the balls of your feet and place the bar on the back of your shoulders.', 'Take the bar with both hands facing forward. Rotate the bar to unrack it. This will be your starting position.', 'Raise your heels as high as possible by pushing off of the balls of your feet, flexing your calf at the top of the contraction. Your knees should remain extended. Hold the contracted position for a second before you start to go back down.', 'Return slowly to the starting position as you breathe in while lowering your heels.', 'Repeat for the recommended amount of repetitions.']",
        images=['Smith_Machine_Calf_Raise/0.jpg', 'Smith_Machine_Calf_Raise/1.jpg'],
    ),
    "Foot-SMR": ExerciseDefinition(
        id="Foot-SMR",
        display_name="Foot-SMR",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.CALVES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.STATIC,
        equipment_type=EquipmentType.OTHER,
        instructions="['This exercise stretches the fascia of the muscles in the feet. Start off seated with your shoes removed. Using a foot roller or a similar object, such as a small section of pvc pipe, place your foot against the roller across the arch of your foot. This will be your starting position.', 'Press down firmly, rolling across the arch of your foot. Hold for 10-30 seconds, and then switch feet.']",
        images=['Foot-SMR/0.jpg', 'Foot-SMR/1.jpg'],
    ),
    "Calves-SMR": ExerciseDefinition(
        id="Calves-SMR",
        display_name="Calves-SMR",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.CALVES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.STATIC,
        instructions="['Begin seated on the floor. Place a foam roller underneath your lower leg. Your other leg can either be crossed over the opposite or be placed on the floor, supporting some of your weight. This will be your starting position.', 'Place your hands to your side or just behind you, and press down to raise your hips off of the floor, placing much of your weight against your calf muscle. Roll from below the knee to above the ankle, pausing at points of tension for 10-30 seconds. Repeat for the other leg.']",
        images=['Calves-SMR/0.jpg', 'Calves-SMR/1.jpg'],
    ),
    "Ankle_Circles": ExerciseDefinition(
        id="Ankle_Circles",
        display_name="Ankle Circles",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.CALVES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        instructions="['Use a sturdy object like a squat rack to hold yourself.', 'Lift the right leg in the air (just around 2 inches from the floor) and perform a circular motion with the big toe. Pretend that you are drawing a big circle with it. Tip: One circle equals 1 repetition. Breathe normally as you perform the movement.', 'When you are done with the right foot, then repeat with the left leg.']",
        images=['Ankle_Circles/0.jpg', 'Ankle_Circles/1.jpg'],
    ),
    "Calf_Stretch_Hands_Against_Wall": ExerciseDefinition(
        id="Calf_Stretch_Hands_Against_Wall",
        display_name="Calf Stretch Hands Against Wall",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.CALVES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.STATIC,
        mechanics_type=MechanicsType.ISOLATION,
        instructions="['Stand facing a wall from several feet away. Stagger your stance, placing one foot forward.', 'Lean forward and rest your hands on the wall, keeping your heel, hip and head in a straight line.', 'Attempt to keep your heel on the ground. Hold for 10-20 seconds and then switch sides.']",
        images=['Calf_Stretch_Hands_Against_Wall/0.jpg', 'Calf_Stretch_Hands_Against_Wall/1.jpg'],
    ),
    "Standing_Gastrocnemius_Calf_Stretch": ExerciseDefinition(
        id="Standing_Gastrocnemius_Calf_Stretch",
        display_name="Standing Gastrocnemius Calf Stretch",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.CALVES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.STATIC,
        secondary_muscles=[MuscleGroup.HAMSTRINGS],
        instructions="['Place your right heel on a step with your knee extended and lean forward to grab your right toe with your right hand. Your left knee should be slightly bent and your back should be straight.', 'Support your weight on your left leg and place your left hand on your left thigh.', 'Pull your right toes toward your knee until you feel a stretch in your calf.']",
        images=['Standing_Gastrocnemius_Calf_Stretch/0.jpg', 'Standing_Gastrocnemius_Calf_Stretch/1.jpg'],
    ),
    "Standing_Calf_Raises": ExerciseDefinition(
        id="Standing_Calf_Raises",
        display_name="Standing Calf Raises",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.CALVES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.MACHINE,
        instructions="['Adjust the padded lever of the calf raise machine to fit your height.', 'Place your shoulders under the pads provided and position your toes facing forward (or using any of the two other positions described at the beginning of the chapter). The balls of your feet should be secured on top of the calf block with the heels extending off it. Push the lever up by extending your hips and knees until your torso is standing erect. The knees should be kept with a slight bend; never locked. Toes should be facing forward, outwards or inwards as described at the beginning of the chapter. This will be your starting position.', 'Raise your heels as you breathe out by extending your ankles as high as possible and flexing your calf. Ensure that the knee is kept stationary at all times. There should be no bending at any time. Hold the contracted position by a second before you start to go back down.', 'Go back slowly to the starting position as you breathe in by lowering your heels as you bend the ankles until calves are stretched.', 'Repeat for the recommended amount of repetitions.']",
        images=['Standing_Calf_Raises/0.jpg', 'Standing_Calf_Raises/1.jpg'],
    ),
    "Seated_Calf_Raise": ExerciseDefinition(
        id="Seated_Calf_Raise",
        display_name="Seated Calf Raise",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.CALVES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.MACHINE,
        instructions="['Sit on the machine and place your toes on the lower portion of the platform provided with the heels extending off. Choose the toe positioning of your choice (forward, in, or out) as per the beginning of this chapter.', 'Place your lower thighs under the lever pad, which will need to be adjusted according to the height of your thighs. Now place your hands on top of the lever pad in order to prevent it from slipping forward.', 'Lift the lever slightly by pushing your heels up and release the safety bar. This will be your starting position.', 'Slowly lower your heels by bending at the ankles until the calves are fully stretched. Inhale as you perform this movement.', 'Raise the heels by extending the ankles as high as possible as you contract the calves and breathe out. Hold the top contraction for a second.', 'Repeat for the recommended amount of repetitions.']",
        images=['Seated_Calf_Raise/0.jpg', 'Seated_Calf_Raise/1.jpg'],
    ),
    "Posterior_Tibialis_Stretch": ExerciseDefinition(
        id="Posterior_Tibialis_Stretch",
        display_name="Posterior Tibialis Stretch",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.CALVES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.STATIC,
        equipment_type=EquipmentType.OTHER,
        instructions="['In a seated position, loop a belt, rope, or band around one foot. This will be your starting position.', 'With the leg extended and the heel off of the ground, pull on the belt so that the foot is everted, with the outside of the foot being pulled towards you. Hold for 10-20 seconds, and then switch sides.']",
        images=['Posterior_Tibialis_Stretch/0.jpg', 'Posterior_Tibialis_Stretch/1.jpg'],
    ),
    "Donkey_Calf_Raises": ExerciseDefinition(
        id="Donkey_Calf_Raises",
        display_name="Donkey Calf Raises",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.CALVES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.OTHER,
        instructions="['For this exercise you will need access to a donkey calf raise machine. Start by positioning your lower back and hips under the padded lever provided. The tailbone area should be the one making contact with the pad.', 'Place both of your arms on the side handles and place the balls of your feet on the calf block with the heels extending off. Align the toes forward, inward or outward, depending on the area you wish to target, and straighten the knees without locking them. This will be your starting position.', 'Raise your heels as you breathe out by extending your ankles as high as possible and flexing your calf. Ensure that the knee is kept stationary at all times. There should be no bending at any time. Hold the contracted position by a second before you start to go back down.', 'Go back slowly to the starting position as you breathe in by lowering your heels as you bend the ankles until calves are stretched.', 'Repeat for the recommended amount of repetitions.']",
        images=['Donkey_Calf_Raises/0.jpg', 'Donkey_Calf_Raises/1.jpg'],
    ),
    "Balance_Board": ExerciseDefinition(
        id="Balance_Board",
        display_name="Balance Board",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.CALVES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.OTHER,
        secondary_muscles=[MuscleGroup.HAMSTRINGS, MuscleGroup.QUADS],
        instructions="['Place a balance board in front of you.', 'Stand up on it and try to balance yourself.', 'Hold the balance for as long as desired.']",
        images=['Balance_Board/0.jpg', 'Balance_Board/1.jpg'],
    ),
    "Calf_Press": ExerciseDefinition(
        id="Calf_Press",
        display_name="Calf Press",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.CALVES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.MACHINE,
        instructions="['Adjust the seat so that your legs are only slightly bent in the start position. The balls of your feet should be firmly on the platform.', 'Select an appropriate weight, and grasp the handles. This will be your starting position.', 'Straighten the legs by extending the knees, just barely lifting the weight from the stack. Your ankle should be fully flexed, toes pointing up. Execute the movement by pressing downward through the balls of your feet as far as possible.', 'After a brief pause, reverse the motion and repeat.']",
        images=['Calf_Press/0.jpg', 'Calf_Press/1.jpg'],
    ),
    "Standing_Dumbbell_Calf_Raise": ExerciseDefinition(
        id="Standing_Dumbbell_Calf_Raise",
        display_name="Standing Dumbbell Calf Raise",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.CALVES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        instructions="['Stand with your torso upright holding two dumbbells in your hands by your sides. Place the ball of the foot on a sturdy and stable wooden board (that is around 2-3 inches tall) while your heels extend off and touch the floor. This will be your starting position.', 'With the toes pointing either straight (to hit all parts equally), inwards (for emphasis on the outer head) or outwards (for emphasis on the inner head), raise the heels off the floor as you exhale by contracting the calves. Hold the top contraction for a second.', 'As you inhale, go back to the starting position by slowly lowering the heels.', 'Repeat for the recommended amount of times.']",
        images=['Standing_Dumbbell_Calf_Raise/0.jpg', 'Standing_Dumbbell_Calf_Raise/1.jpg'],
    ),
    "Calf_Raises_-_With_Bands": ExerciseDefinition(
        id="Calf_Raises_-_With_Bands",
        display_name="Calf Raises - With Bands",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.CALVES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        instructions="['Grab an exercise band and stand on it with your toes making sure that the length of the band between the foot and the arms is the same for both sides.', 'While holding the handles of the band, raise the arms to the side of your head as if you were getting ready to perform a shoulder press. The palms should be facing forward with the elbows bent and to the sides. This movement will create tension on the band. This will be your starting position.', 'Keeping the hands by your shoulder, stand up on your toes as you exhale and contract the calves hard at the top of the movement.', 'After a one second contraction, slowly go back down to the starting position.', 'Repeat for the recommended amount of repetitions.']",
        images=['Calf_Raises_-_With_Bands/0.jpg', 'Calf_Raises_-_With_Bands/1.jpg'],
    ),
}
