from exercises.base import ExerciseDefinition
from enums import MuscleGroup, EquipmentType, MechanicsType, MajorMuscleGroup, ForceType, LevelType, CategoryType

FOREARMS_EXERCISES = {
    "Wrist_Rotations_with_Straight_Bar": ExerciseDefinition(
        id="Wrist_Rotations_with_Straight_Bar",
        display_name="Wrist Rotations with Straight Bar",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.FOREARMS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.BARBELL,
        instructions="""['Hold a barbell with both hands and your palms facing down; hands spaced about shoulder width. This will be your starting position.', 'Alternating between each of your hands, perform the movement by extending the wrist as though you were rolling up a newspaper. Continue alternating back and forth until failure.', 'Reverse the motion by flexing the wrist, rolling the opposite direction. Continue the alternating motion until failure.']""",
        images=['Wrist_Rotations_with_Straight_Bar/0.jpg', 'Wrist_Rotations_with_Straight_Bar/1.jpg'],
    ),
    "Seated_Palm-Up_Barbell_Wrist_Curl": ExerciseDefinition(
        id="Seated_Palm-Up_Barbell_Wrist_Curl",
        display_name="Seated Palm-Up Barbell Wrist Curl",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.FOREARMS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.BARBELL,
        instructions="""['Hold a barbell with both hands and your palms facing up; hands spaced about shoulder width.', 'Place your feet flat on the floor, at a distance that is slightly wider than shoulder width apart.', 'Lean forward and place your forearms on top of your upper thighs with your palms up. Tip: Make sure that the front of the wrists lay on top of your knees. This will be your starting position.', 'Lower the bar as far as possible while inhaling and keeping a tight grip.', 'Now curl bar up as high as possible while flexing the forearms and exhaling. Hold the contraction at the top for a second and Tip: Only the wrist should move.']""",
        images=['Seated_Palm-Up_Barbell_Wrist_Curl/0.jpg', 'Seated_Palm-Up_Barbell_Wrist_Curl/1.jpg'],
    ),
    "Plate_Pinch": ExerciseDefinition(
        id="Plate_Pinch",
        display_name="Plate Pinch",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.FOREARMS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.STATIC,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.OTHER,
        instructions="""['Grab two wide-rimmed plates and put them together with the smooth sides facing outward', 'Use your fingers to grip the outside part of the plate and your thumb for the other side thus holding both plates together. This is the starting position.', 'Squeeze the plate with your fingers and thumb. Hold this position for as long as you can.', 'Repeat for the recommended amount of sets prescribed in your program.', 'Switch arms and repeat the movements.']""",
        images=['Plate_Pinch/0.jpg', 'Plate_Pinch/1.jpg'],
    ),
    "Seated_One-Arm_Dumbbell_Palms-Up_Wrist_Curl": ExerciseDefinition(
        id="Seated_One-Arm_Dumbbell_Palms-Up_Wrist_Curl",
        display_name="Seated One-Arm Dumbbell Palms-Up Wrist Curl",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.FOREARMS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        instructions="""['Sit on a flat bench with a dumbbell in your right hand.', 'Place your feet flat on the floor, at a distance that is slightly wider than shoulder width apart.', 'Lean forward and place your right forearm on top of your upper right thigh with your palm up. Tip: Make sure that the front of the wrist lies on top of your knees. This will be your starting position.', 'Lower the dumbbell as far as possible as you keep a tight grip on the dumbbell. Inhale as you perform this movement.', 'Now curl the dumbbell as high as possible as you contract the forearms and as you exhale. Keep the contraction for a second before you lower again. Tip: The only movement should happen at the wrist.', 'Perform for the recommended amount of repetitions, switch arms and repeat the movement.']""",
        images=['Seated_One-Arm_Dumbbell_Palms-Up_Wrist_Curl/0.jpg', 'Seated_One-Arm_Dumbbell_Palms-Up_Wrist_Curl/1.jpg'],
    ),
    "Rickshaw_Carry": ExerciseDefinition(
        id="Rickshaw_Carry",
        display_name="Rickshaw Carry",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRONGMAN,
        muscle_group=MuscleGroup.FOREARMS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.OTHER,
        secondary_muscles=[MuscleGroup.ABS, MuscleGroup.CALVES, MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS, MuscleGroup.LOWER_BACK, MuscleGroup.QUADS, MuscleGroup.TRAPS],
        instructions="""['Position the frame at the starting point, and load with the appropriate weight. Standing in the center of the frame, begin by gripping the handles and driving through your heels to lift the frame. Ensure your chest and head are up and your back is straight.', 'Immediately begin walking briskly with quick, controlled steps. Keep your chest up and head forward, and make sure you continue breathing. Bring the frame to the ground after you have reached the end point.']""",
        images=['Rickshaw_Carry/0.jpg', 'Rickshaw_Carry/1.jpg'],
    ),
    "Cable_Wrist_Curl": ExerciseDefinition(
        id="Cable_Wrist_Curl",
        display_name="Cable Wrist Curl",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.FOREARMS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['Start out by placing a flat bench in front of a low pulley cable that has a straight bar attachment.', 'Use your arms to grab the cable bar with a narrow to shoulder width supinated grip (palms up) and bring them up so that your forearms are resting against the top of your thighs. Your wrists should be hanging just beyond your knees.', 'Start out by curling your wrist upwards and exhaling. Keep the contraction for a second.', 'Slowly lower your wrists back down to the starting position while inhaling.', 'Your forearms should be stationary as your wrist is the only movement needed to perform this exercise.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Cable_Wrist_Curl/0.jpg', 'Cable_Wrist_Curl/1.jpg'],
    ),
    "Palms-Down_Dumbbell_Wrist_Curl_Over_A_Bench": ExerciseDefinition(
        id="Palms-Down_Dumbbell_Wrist_Curl_Over_A_Bench",
        display_name="Palms-Down Dumbbell Wrist Curl Over A Bench",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.FOREARMS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        instructions="""['Start out by placing two dumbbells on one side of a flat bench.', 'Kneel down on both of your knees so that your body is facing the flat bench.', 'Use your arms to grab both of the dumbbells with a pronated grip (palms facing down) and bring them up so that your forearms are resting against the flat bench. Your wrists should be hanging over the edge.', 'Start out by curling your wrist upwards and exhaling.', 'Slowly lower your wrists back down to the starting position while inhaling.', 'Your forearms should be stationary as your wrist is the only movement needed to perform this exercise.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Palms-Down_Dumbbell_Wrist_Curl_Over_A_Bench/0.jpg', 'Palms-Down_Dumbbell_Wrist_Curl_Over_A_Bench/1.jpg'],
    ),
    "Farmers_Walk": ExerciseDefinition(
        id="Farmers_Walk",
        display_name="Farmer's Walk",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRONGMAN,
        muscle_group=MuscleGroup.FOREARMS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.OTHER,
        secondary_muscles=[MuscleGroup.ABS, MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS, MuscleGroup.LOWER_BACK, MuscleGroup.QUADS, MuscleGroup.TRAPS],
        instructions="""["There are various implements that can be used for the farmers walk. These can also be performed with heavy dumbbells or short bars if these implements aren't available. Begin by standing between the implements.", 'After gripping the handles, lift them up by driving through your heels, keeping your back straight and your head up.', "Walk taking short, quick steps, and don't forget to breathe. Move for a given distance, typically 50-100 feet, as fast as possible."]""",
        images=['Farmers_Walk/0.jpg', 'Farmers_Walk/1.jpg'],
    ),
    "Palms-Up_Barbell_Wrist_Curl_Over_A_Bench": ExerciseDefinition(
        id="Palms-Up_Barbell_Wrist_Curl_Over_A_Bench",
        display_name="Palms-Up Barbell Wrist Curl Over A Bench",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.FOREARMS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.BARBELL,
        instructions="""['Start out by placing a barbell on one side of a flat bench.', 'Kneel down on both of your knees so that your body is facing the flat bench.', 'Use your arms to grab the barbell with a supinated grip (palms up) and bring them up so that your forearms are resting against the flat bench. Your wrists should be hanging over the edge.', 'Start out by curling your wrist upwards and exhaling.', 'Slowly lower your wrists back down to the starting position while inhaling.', 'Your forearms should be stationary as your wrist is the only movement needed to perform this exercise.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Palms-Up_Barbell_Wrist_Curl_Over_A_Bench/0.jpg', 'Palms-Up_Barbell_Wrist_Curl_Over_A_Bench/1.jpg'],
    ),
    "Seated_Palms-Down_Barbell_Wrist_Curl": ExerciseDefinition(
        id="Seated_Palms-Down_Barbell_Wrist_Curl",
        display_name="Seated Palms-Down Barbell Wrist Curl",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.FOREARMS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.BARBELL,
        instructions="""['Hold a barbell with both hands and your palms facing down; hands spaced about shoulder width.', 'Place your feet flat on the floor, at a distance that is slightly wider than shoulder width apart.', 'Lean forward and place your forearms on top of your upper thighs with your palms down. Tip: Make sure that the back of the wrists lay on top of your knees. This will be your starting position.', 'Lower the bar as far as possible while inhaling and keeping a tight grip.', 'Now curl bar up as high as possible while flexing the forearms and exhaling. Hold the contraction at the top for a second and Tip: Only the wrist should move.']""",
        images=['Seated_Palms-Down_Barbell_Wrist_Curl/0.jpg', 'Seated_Palms-Down_Barbell_Wrist_Curl/1.jpg'],
    ),
    "Palms-Up_Dumbbell_Wrist_Curl_Over_A_Bench": ExerciseDefinition(
        id="Palms-Up_Dumbbell_Wrist_Curl_Over_A_Bench",
        display_name="Palms-Up Dumbbell Wrist Curl Over A Bench",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.FOREARMS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        instructions="['Start out by placing two dumbbells on one side of a flat bench.', 'Kneel down on both of your knees so that your body is facing the flat bench.', 'Use your arms to grab both of the dumbbells with a supinated grip (palms up) and bring them up so that your forearms are resting against the flat bench. Your wrists should be hanging over the edge.', 'Start out by curling your wrist upwards and exhaling.', 'Slowly lower your wrists back down to the starting position while inhaling. Make sure to inhale during this part of the exercise.', 'Your forearms should be stationary as your wrist is the only movement needed to perform this exercise.', 'Repeat for the recommended amount of repetitions.']",
        images=['Palms-Up_Dumbbell_Wrist_Curl_Over_A_Bench/0.jpg', 'Palms-Up_Dumbbell_Wrist_Curl_Over_A_Bench/1.jpg'],
    ),
    "Palms-Down_Wrist_Curl_Over_A_Bench": ExerciseDefinition(
        id="Palms-Down_Wrist_Curl_Over_A_Bench",
        display_name="Palms-Down Wrist Curl Over A Bench",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.FOREARMS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.BARBELL,
        instructions="['Start out by placing a barbell on one side of a flat bench.', 'Kneel down on both of your knees so that your body is facing the flat bench.', 'Use your arms to grab the barbell with a pronated grip (palms down) and bring them up so that your forearms are resting against the flat bench. Your wrists should be hanging over the edge.', 'Start out by curling your wrist upwards and exhaling.', 'Slowly lower your wrists back down to the starting position while inhaling.', 'Your forearms should be stationary as your wrist is the only movement needed to perform this exercise.', 'Repeat for the recommended amount of repetitions.']",
        images=['Palms-Down_Wrist_Curl_Over_A_Bench/0.jpg', 'Palms-Down_Wrist_Curl_Over_A_Bench/1.jpg'],
    ),
    "Wrist_Circles": ExerciseDefinition(
        id="Wrist_Circles",
        display_name="Wrist Circles",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.FOREARMS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        instructions="""['Start by standing straight with your feet being shoulder width apart from each other. Elevate your arms to the side of you until they are fully extended and parallel to the floor at a height that is evenly aligned with your shoulders. Tip: Your torso and arms should form the letter "T: Your palms should be facing down. This is the starting position.', 'Keeping your entire body stationary except for the wrists, begin to rotate both wrists forward in a circular motion. Tip: Pretend that you are trying to draw circles by using your hands as the brush. Breathe normally as you perform this exercise.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Wrist_Circles/0.jpg', 'Wrist_Circles/1.jpg'],
    ),
    "Seated_Two-Arm_Palms-Up_Low-Pulley_Wrist_Curl": ExerciseDefinition(
        id="Seated_Two-Arm_Palms-Up_Low-Pulley_Wrist_Curl",
        display_name="Seated Two-Arm Palms-Up Low-Pulley Wrist Curl",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.FOREARMS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['Put a bench in front of a low pulley machine that has a barbell or EZ Curl attachment on it.', 'Move the bench far enough away so that when you bring the handle to the top of your thighs tension is created on the cable due to the weight stack being moved up.', 'Now hold the handle with both hands, palms up, using a shoulder-width grip.', 'Step back and sit on the bench with your feet about shoulder width apart, firmly on the floor.', 'Lean forward and place the forearms on your thighs with the back of your wrists over your knees. This will be your starting position.', 'Lower the bar as far as possible, while inhaling and keeping a tight grip.', 'Now curl the bar up as high as possible while contracting the forearms. Tip: Only the wrist should move; not the forearms.', 'After a second contraction at the top go back to the starting position as you inhale.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Seated_Two-Arm_Palms-Up_Low-Pulley_Wrist_Curl/0.jpg', 'Seated_Two-Arm_Palms-Up_Low-Pulley_Wrist_Curl/1.jpg'],
    ),
    "Standing_Palms-Up_Barbell_Behind_The_Back_Wrist_Curl": ExerciseDefinition(
        id="Standing_Palms-Up_Barbell_Behind_The_Back_Wrist_Curl",
        display_name="Standing Palms-Up Barbell Behind The Back Wrist Curl",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.FOREARMS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.BARBELL,
        instructions="""["Start by standing straight and holding a barbell behind your glutes at arm's length while using a pronated grip (palms will be facing back away from the glutes) and having your hands shoulder width apart from each other.", 'You should be looking straight forward while your feet are shoulder width apart from each other. This is the starting position.', 'While exhaling, slowly elevate the barbell up by curling your wrist in a semi-circular motion towards the ceiling. Note: Your wrist should be the only body part moving for this exercise.', 'Hold the contraction for a second and lower the barbell back down to the starting position while inhaling.', 'Repeat for the recommended amount of repetitions.', 'When finished, lower the barbell down to the squat rack or the floor by bending the knees. Tip: It is easiest to either pick it up from a squat rack or have a partner hand it to you.']""",
        images=['Standing_Palms-Up_Barbell_Behind_The_Back_Wrist_Curl/0.jpg', 'Standing_Palms-Up_Barbell_Behind_The_Back_Wrist_Curl/1.jpg'],
    ),
    "Dumbbell_Lying_Supination": ExerciseDefinition(
        id="Dumbbell_Lying_Supination",
        display_name="Dumbbell Lying Supination",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.FOREARMS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        instructions="""['Lie sideways on a flat bench with one arm holding a dumbbell and the other hand on top of the bench folded so that you can rest your head on it.', 'Bend the elbows of the arm holding the dumbbell so that it creates a 90-degree angle between the upper arm and the forearm.', 'Now raise the upper arm so that the forearm is parallel to the floor and perpendicular to your torso (Tip: So the forearm will be directly in front of you). The upper arm will be stationary by your torso and should be parallel to the floor (aligned with your torso at all times). This will be your starting position.', 'As you breathe out, externally rotate your forearm so that the dumbbell is lifted up in a semicircle motion as you maintain the 90 degree angle bend between the upper arms and the forearm. You will continue this external rotation until the forearm is perpendicular to the floor and the torso pointing towards the ceiling. At this point you will hold the contraction for a second.', 'As you breathe in, slowly go back to the starting position.', 'Repeat for the recommended amount of repetitions and then switch to the other arm.']""",
        images=['Dumbbell_Lying_Supination/0.jpg', 'Dumbbell_Lying_Supination/1.jpg'],
    ),
    "Dumbbell_Lying_Pronation": ExerciseDefinition(
        id="Dumbbell_Lying_Pronation",
        display_name="Dumbbell Lying Pronation",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.FOREARMS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        instructions="""['Lie on a flat bench face down with one arm holding a dumbbell and the other hand on top of the bench folded so that you can rest your head on it.', 'Bend the elbows of the arm holding the dumbbell so that it creates a 90-degree angle between the upper arm and the forearm.', 'Now raise the upper arm so that the forearm is perpendicular to the floor and the upper arm is perpendicular to your torso. Tip: The upper arm should be parallel to the floor and also creating a 90-degree angle with your torso. This will be your starting position.', 'As you breathe out, externally rotate your forearm so that the dumbbell is lifted forward as you maintain the 90 degree angle bend between the upper arms and the forearm. You will continue this external rotation until the forearm is parallel to the floor. At this point you will hold the contraction for a second.', 'As you breathe in, slowly go back to the starting position.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Dumbbell_Lying_Pronation/0.jpg', 'Dumbbell_Lying_Pronation/1.jpg'],
    ),
    "Kneeling_Forearm_Stretch": ExerciseDefinition(
        id="Kneeling_Forearm_Stretch",
        display_name="Kneeling Forearm Stretch",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.FOREARMS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.STATIC,
        mechanics_type=MechanicsType.ISOLATION,
        instructions="""['Start by kneeling on a mat with your palms flat and your fingers pointing back toward your knees.', 'Slowly lean back keeping your palms flat on the floor until you feel a stretch in your wrists and forearms. Hold for 20-30 seconds.']""",
        images=['Kneeling_Forearm_Stretch/0.jpg', 'Kneeling_Forearm_Stretch/1.jpg'],
    ),
    "Seated_One-Arm_Dumbbell_Palms-Down_Wrist_Curl": ExerciseDefinition(
        id="Seated_One-Arm_Dumbbell_Palms-Down_Wrist_Curl",
        display_name="Seated One-Arm Dumbbell Palms-Down Wrist Curl",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.FOREARMS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        instructions="""['Sit on a flat bench with a dumbbell in your right hand.', 'Place your feet flat on the floor, at a distance that is slightly wider than shoulder width apart.', 'Lean forward and place your right forearm on top of your upper right thigh with your palm down. Tip: Make sure that the back of the wrist lies on top of your knees. This will be your starting position.', 'Lower the dumbbell as far as possible as you keep a tight grip on the dumbbell. Inhale as you perform this movement.', 'Now curl the dumbbell as high as possible as you contract the forearms and as you exhale. Keep the contraction for a second before you lower again. Tip: The only movement should happen at the wrist.', 'Perform for the recommended amount of repetitions, switch arms and repeat the movement.']""",
        images=['Seated_One-Arm_Dumbbell_Palms-Down_Wrist_Curl/0.jpg', 'Seated_One-Arm_Dumbbell_Palms-Down_Wrist_Curl/1.jpg'],
    ),
    "Seated_Dumbbell_Palms-Up_Wrist_Curl": ExerciseDefinition(
        id="Seated_Dumbbell_Palms-Up_Wrist_Curl",
        display_name="Seated Dumbbell Palms-Up Wrist Curl",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.FOREARMS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        instructions="""['Start out by placing two dumbbells on the floor in front of a flat bench.', 'Sit down on the edge of the flat bench with your legs at about shoulder width apart. Make sure to keep your feet on the floor.', 'Use your arms to grab both of the dumbbells and bring them up so that your forearms are resting against your thighs with the palms of the hands facing up. Your wrists should be hanging over the edge of your thighs.', 'Start out by curling your wrist upwards and exhaling.', 'Slowly lower your wrists back down to the starting position while inhaling. Make sure to inhale during this part of the exercise. Tip: Your forearms should be stationary as your wrist is the only movement needed to perform this exercise.', 'Repeat for the recommended amount of repetitions.', 'When finished, simply lower the dumbbells to the floor.']""",
        images=['Seated_Dumbbell_Palms-Up_Wrist_Curl/0.jpg', 'Seated_Dumbbell_Palms-Up_Wrist_Curl/1.jpg'],
    ),
    "Wrist_Roller": ExerciseDefinition(
        id="Wrist_Roller",
        display_name="Wrist Roller",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.FOREARMS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.OTHER,
        secondary_muscles=[MuscleGroup.SHOULDERS],
        instructions="""['To begin, stand straight up grabbing a wrist roller using a pronated grip (palms facing down). Your feet should be shoulder width apart.', 'Slowly lift both arms until they are fully extended and parallel to the floor in front of you. Note: Make sure the rope is not wrapped around the roller. Your entire body should be stationary except for the forearms. This is the starting position.', 'Rotate one wrist at a time in an upward motion to bring the weight up to the bar by rolling the rope around the roller.', 'Once the weight has reached the bar, slowly begin to lower the weight back down by rotating the wrist in a downward motion until the weight reaches the starting position.', 'Repeat for the prescribed amount of repetitions in your program.']""",
        images=['Wrist_Roller/0.jpg', 'Wrist_Roller/1.jpg'],
    ),
    "Bottoms-Up_Clean_From_The_Hang_Position": ExerciseDefinition(
        id="Bottoms-Up_Clean_From_The_Hang_Position",
        display_name="Bottoms-Up Clean From The Hang Position",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.FOREARMS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.BICEPS, MuscleGroup.SHOULDERS],
        instructions="""['Initiate the exercise by standing upright with a kettlebell in one hand.', 'Swing the kettlebell back forcefully and then reverse the motion forcefully. Crush the kettlebell handle as hard as possible and raise the kettlebell to your shoulder.']""",
        images=['Bottoms-Up_Clean_From_The_Hang_Position/0.jpg', 'Bottoms-Up_Clean_From_The_Hang_Position/1.jpg'],
    ),
    "Standing_Olympic_Plate_Hand_Squeeze": ExerciseDefinition(
        id="Standing_Olympic_Plate_Hand_Squeeze",
        display_name="Standing Olympic Plate Hand Squeeze",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.FOREARMS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.STATIC,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.OTHER,
        secondary_muscles=[MuscleGroup.BICEPS],
        instructions="""["To begin, stand straight while holding a weight plate by the ridge at arm's length in each hand using a neutral grip (palms facing in). You feet should be shoulder width apart from each other. This will be your starting position.", 'Lower the plates until the fingers are nearly extended but can still hold weights. Inhale as you lower the plates.', 'Now raise the plates back to the starting position as you exhale by closing your hands.', 'Repeat for the recommended amount of repetitions prescribed in your program.']""",
        images=['Standing_Olympic_Plate_Hand_Squeeze/0.jpg', 'Standing_Olympic_Plate_Hand_Squeeze/1.jpg'],
    ),
    "Seated_Dumbbell_Palms-Down_Wrist_Curl": ExerciseDefinition(
        id="Seated_Dumbbell_Palms-Down_Wrist_Curl",
        display_name="Seated Dumbbell Palms-Down Wrist Curl",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.FOREARMS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        instructions="""['Start out by placing two dumbbells on the floor in front of a flat bench.', 'Sit down on the edge of the flat bench with your legs at about shoulder width apart. Make sure to keep your feet on the floor.', 'Use your arms to grab both of the dumbbells and bring them up so that your forearms are resting against your thighs with the palms of the hands facing down. Your wrists should be hanging over the edge of your thighs.', 'Start out by curling your wrist upwards and exhaling.', 'Slowly lower your wrists back down to the starting position while inhaling. Make sure to inhale during this part of the exercise. Tip: Your forearms should be stationary as your wrist is the only movement needed to perform this exercise.', 'Repeat for the recommended amount of repetitions.', 'When finished, simply lower the dumbbells to the floor.']""",
        images=['Seated_Dumbbell_Palms-Down_Wrist_Curl/0.jpg', 'Seated_Dumbbell_Palms-Down_Wrist_Curl/1.jpg'],
    ),
    "Finger_Curls": ExerciseDefinition(
        id="Finger_Curls",
        display_name="Finger Curls",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.FOREARMS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.BARBELL,
        instructions="""['Hold a barbell with both hands and your palms facing up; hands spaced about shoulder width.', 'Place your feet flat on the floor, at a distance that is slightly wider than shoulder width apart. This will be your starting position.', 'Lower the bar as far as possible by extending the fingers. Allowing the bar to roll down the hands, catch the bar with the final joint in the fingers.', 'Now curl bar up as high as possible by closing your hands while exhaling. Hold the contraction at the top.']""",
        images=['Finger_Curls/0.jpg', 'Finger_Curls/1.jpg'],
    ),
}
