from exercises.base import ExerciseDefinition
from enums import MuscleGroup, EquipmentType, MechanicsType, MajorMuscleGroup, ForceType, LevelType, CategoryType

GLUTES_EXERCISES = {
    "Single_Leg_Glute_Bridge": ExerciseDefinition(
        id="Single_Leg_Glute_Bridge",
        display_name="Single Leg Glute Bridge",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.GLUTES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        secondary_muscles=[MuscleGroup.HAMSTRINGS],
        instructions="""['Lay on the floor with your feet flat and knees bent.', 'Raise one leg off of the ground, pulling the knee to your chest. This will be your starting position.', 'Execute the movement by driving through the heel, extending your hip upward and raising your glutes off of the ground.', 'Extend as far as possible, pause and then return to the starting position.']""",
        images=['Single_Leg_Glute_Bridge/0.jpg', 'Single_Leg_Glute_Bridge/1.jpg'],
    ),
    "Pull_Through": ExerciseDefinition(
        id="Pull_Through",
        display_name="Pull Through",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.GLUTES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.CABLE,
        secondary_muscles=[MuscleGroup.HAMSTRINGS, MuscleGroup.LOWER_BACK],
        instructions="""['Begin standing a few feet in front of a low pulley with a rope or handle attached. Face away from the machine, straddling the cable, with your feet set wide apart.', 'Begin the movement by reaching through your legs as far as possible, bending at the hips. Keep your knees slightly bent. Keeping your arms straight, extend through the hip to stand straight up. Avoid pulling upward through the shoulders; all of the motion should originate through the hips.']""",
        images=['Pull_Through/0.jpg', 'Pull_Through/1.jpg'],
    ),
    "One_Knee_To_Chest": ExerciseDefinition(
        id="One_Knee_To_Chest",
        display_name="One Knee To Chest",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.GLUTES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.STATIC,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.HAMSTRINGS, MuscleGroup.LOWER_BACK],
        instructions="""['Start off by lying on the floor.', 'Extend one leg straight and pull the other knee to your chest. Hold under the knee joint to protect the kneecap.', 'Gently tug that knee toward your nose.', 'Switch sides. This stretches the buttocks and lower back of the bent leg and the hip flexor of the straight leg.']""",
        images=['One_Knee_To_Chest/0.jpg', 'One_Knee_To_Chest/1.jpg'],
    ),
    "Kneeling_Squat": ExerciseDefinition(
        id="Kneeling_Squat",
        display_name="Kneeling Squat",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.POWERLIFTING,
        muscle_group=MuscleGroup.GLUTES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.ABS, MuscleGroup.HAMSTRINGS, MuscleGroup.LOWER_BACK],
        instructions="""['Set the bar to the proper height in a power rack. Kneel behind the bar; it may be beneficial to put a mat down to pad your knees. Slide under the bar, racking it across the back of your shoulders. Your shoulder blades should be retracted and the bar tight across your back. Unrack the weight.', 'With your head looking forward, sit back with your butt until you touch your calves.', 'Reverse the motion, returning the torso to an upright position.']""",
        images=['Kneeling_Squat/0.jpg', 'Kneeling_Squat/1.jpg'],
    ),
    "Kneeling_Jump_Squat": ExerciseDefinition(
        id="Kneeling_Jump_Squat",
        display_name="Kneeling Jump Squat",
        level=LevelType.EXPERT,
        category=CategoryType.OLYMPIC_WEIGHTLIFTING,
        muscle_group=MuscleGroup.GLUTES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.CALVES, MuscleGroup.HAMSTRINGS, MuscleGroup.QUADS],
        instructions="""['Begin kneeling on the floor with a barbell racked across the back of your shoulders, or you can use your body weight for this exercise. This can be done inside of a power rack to make unracking easier.', 'Sit back with your hips until your glutes touch your feet, keeping your head and chest up.', 'Explode up with your hips, generating enough power to land with your feet flat on the floor.', 'Continue with the squat by driving through your heels and extending the knees to come to a standing position.']""",
        images=['Kneeling_Jump_Squat/0.jpg', 'Kneeling_Jump_Squat/1.jpg'],
    ),
    "Downward_Facing_Balance": ExerciseDefinition(
        id="Downward_Facing_Balance",
        display_name="Downward Facing Balance",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.GLUTES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.STATIC,
        mechanics_type=MechanicsType.ISOLATION,
        secondary_muscles=[MuscleGroup.ABS, MuscleGroup.HAMSTRINGS],
        instructions="""['Lie facedown on top of an exercise ball.', 'While resting on your stomach on the ball, walk your hands forward along the floor and lift your legs, extending your elbows and knees.']""",
        images=['Downward_Facing_Balance/0.jpg', 'Downward_Facing_Balance/1.jpg'],
    ),
    "Flutter_Kicks": ExerciseDefinition(
        id="Flutter_Kicks",
        display_name="Flutter Kicks",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.GLUTES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.HAMSTRINGS],
        instructions="""['On a flat bench lie facedown with the hips on the edge of the bench, the legs straight with toes high off the floor and with the arms on top of the bench holding on to the front edge.', 'Squeeze your glutes and hamstrings and straighten the legs until they are level with the hips. This will be your starting position.', 'Start the movement by lifting the left leg higher than the right leg.', 'Then lower the left leg as you lift the right leg.', 'Continue alternating in this manner (as though you are doing a flutter kick in water) until you have done the recommended amount of repetitions for each leg. Make sure that you keep a controlled movement at all times. Tip: You will breathe normally as you perform this movement.']""",
        images=['Flutter_Kicks/0.jpg', 'Flutter_Kicks/1.jpg'],
    ),
    "Lying_Glute": ExerciseDefinition(
        id="Lying_Glute",
        display_name="Lying Glute",
        level=LevelType.EXPERT,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.GLUTES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.STATIC,
        secondary_muscles=[MuscleGroup.ABDUCTORS],
        instructions="""['Lie on your back with your partner kneeling beside you.', 'Flex the hip of one leg, raising it off of the floor. Rotate the leg so the foot is over the opposite hip, the lower leg perpendicular to your body. Your partner should hold the knee and ankle in place. This will be your starting position.', 'Attempt to push your leg towards your partner, who should be preventing any actual movement of the leg.', 'After 10-20 seconds, completely relax as your partner gently pushes the ankle and knee towards your chest. Be sure to inform your helper when the stretch is adequate to prevent injury or overstretching.']""",
        images=['Lying_Glute/0.jpg', 'Lying_Glute/1.jpg'],
    ),
    "Glute_Kickback": ExerciseDefinition(
        id="Glute_Kickback",
        display_name="Glute Kickback",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.GLUTES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.HAMSTRINGS],
        instructions="""['Kneel on the floor or an exercise mat and bend at the waist with your arms extended in front of you (perpendicular to the torso) in order to get into a kneeling push-up position but with the arms spaced at shoulder width. Your head should be looking forward and the bend of the knees should create a 90-degree angle between the hamstrings and the calves. This will be your starting position.', 'As you exhale, lift up your right leg until the hamstrings are in line with the back while maintaining the 90-degree angle bend. Contract the glutes throughout this movement and hold the contraction at the top for a second. Tip: At the end of the movement the upper leg should be parallel to the floor while the calf should be perpendicular to it.', 'Go back to the initial position as you inhale and now repeat with the left leg.', 'Continue to alternate legs until all of the recommended repetitions have been performed.']""",
        images=['Glute_Kickback/0.jpg', 'Glute_Kickback/1.jpg'],
    ),
    "One-Legged_Cable_Kickback": ExerciseDefinition(
        id="One-Legged_Cable_Kickback",
        display_name="One-Legged Cable Kickback",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.GLUTES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        secondary_muscles=[MuscleGroup.HAMSTRINGS],
        instructions="""['Hook a leather ankle cuff to a low cable pulley and then attach the cuff to your ankle.', 'Face the weight stack from a distance of about two feet, grasping the steel frame for support.', 'While keeping your knees and hips bent slightly and your abs tight, contract your glutes to slowly "kick" the working leg back in a semicircular arc as high as it will comfortably go as you breathe out. Tip: At full extension, squeeze your glutes for a second in order to achieve a peak contraction.', 'Now slowly bring your working leg forward, resisting the pull of the cable until you reach the starting position.', 'Repeat for the recommended amount of repetitions.', 'Switch legs and repeat the movement for the other side.']""",
        images=['One-Legged_Cable_Kickback/0.jpg', 'One-Legged_Cable_Kickback/1.jpg'],
    ),
    "Piriformis-SMR": ExerciseDefinition(
        id="Piriformis-SMR",
        display_name="Piriformis-SMR",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.GLUTES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.STATIC,
        mechanics_type=MechanicsType.ISOLATION,
        instructions="""['Sit with your buttocks on top of a foam roll. Bend your knees, and then cross one leg so that the ankle is over the knee. This will be your starting position.', 'Shift your weight to the side of the crossed leg, rolling over the buttocks until you feel tension in your upper glute. You may assist the stretch by using one hand to pull the bent knee towards your chest. Hold this position for 10-30 seconds, and then switch sides.']""",
        images=['Piriformis-SMR/0.jpg', 'Piriformis-SMR/1.jpg'],
    ),
    "Ankle_On_The_Knee": ExerciseDefinition(
        id="Ankle_On_The_Knee",
        display_name="Ankle On The Knee",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.GLUTES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.STATIC,
        instructions="""['From a lying position, bend your knees and keep your feet on the floor.', 'Place your ankle of one foot on your opposite knee.', 'Grasp the thigh or knee of the bottom leg and pull both of your legs into the chest. Relax your neck and shoulders. Hold for 10-20 seconds and then switch sides.']""",
        images=['Ankle_On_The_Knee/0.jpg', 'Ankle_On_The_Knee/1.jpg'],
    ),
    "Hip_Extension_with_Bands": ExerciseDefinition(
        id="Hip_Extension_with_Bands",
        display_name="Hip Extension with Bands",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.GLUTES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.HAMSTRINGS],
        instructions="""['Secure one end of the band to the lower portion of a post and attach the other to one ankle.', 'Facing the attachment point of the band, hold on to the column to stabilize yourself.', 'Keeping your head and your chest up, move the resisted leg back as far as you can while keeping the knee straight.', 'Return the leg to the starting position.']""",
        images=['Hip_Extension_with_Bands/0.jpg', 'Hip_Extension_with_Bands/1.jpg'],
    ),
    "Physioball_Hip_Bridge": ExerciseDefinition(
        id="Physioball_Hip_Bridge",
        display_name="Physioball Hip Bridge",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.GLUTES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.HAMSTRINGS],
        instructions="""['Lay on a ball so that your upper back is on the ball with your hips unsupported. Both feet should be flat on the floor, hip width apart or wider. This will be your starting position.', 'Begin by extending the hips using your glutes and hamstrings, raising your hips upward as you bridge.', 'Pause at the top of the motion and return to the starting position.']""",
        images=['Physioball_Hip_Bridge/0.jpg', 'Physioball_Hip_Bridge/1.jpg'],
    ),
    "Step-up_with_Knee_Raise": ExerciseDefinition(
        id="Step-up_with_Knee_Raise",
        display_name="Step-up with Knee Raise",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.GLUTES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.HAMSTRINGS, MuscleGroup.QUADS],
        instructions="""['Stand facing a box or bench of an appropriate height with your feet together. This will be your starting position.', 'Begin the movement by stepping up, putting your left foot on the top of the bench. Extend through the hip and knee of your front leg to stand up on the box. As you stand on the box with your left leg, flex your right knee and hip, bringing your knee as high as you can.', 'Reverse this motion to step down off the box, and then repeat the sequence on the opposite leg.']""",
        images=['Step-up_with_Knee_Raise/0.jpg', 'Step-up_with_Knee_Raise/1.jpg'],
    ),
    "Butt_Lift_Bridge": ExerciseDefinition(
        id="Butt_Lift_Bridge",
        display_name="Butt Lift (Bridge)",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.GLUTES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        secondary_muscles=[MuscleGroup.HAMSTRINGS],
        instructions="""['Lie flat on the floor on your back with the hands by your side and your knees bent. Your feet should be placed around shoulder width. This will be your starting position.', 'Pushing mainly with your heels, lift your hips off the floor while keeping your back straight. Breathe out as you perform this part of the motion and hold at the top for a second.', 'Slowly go back to the starting position as you breathe in.']""",
        images=['Butt_Lift_Bridge/0.jpg', 'Butt_Lift_Bridge/1.jpg'],
    ),
    "Leg_Lift": ExerciseDefinition(
        id="Leg_Lift",
        display_name="Leg Lift",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.GLUTES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        secondary_muscles=[MuscleGroup.HAMSTRINGS],
        instructions="""['While standing up straight with both feet next to each other at around shoulder width, grab a sturdy surface such as the sides of a squat rack or the top of a chair to brace yourself and keep balance.', 'With or without an ankle weight, lift one leg behind you as if performing a leg curl but standing up while keeping the other leg straight. Breathe out as you perform this movement.', 'Slowly bring the raised leg back to the floor as you breathe in.', 'Repeat for the recommended amount of repetitions.', 'Repeat the movement with the opposite leg.']""",
        images=['Leg_Lift/0.jpg', 'Leg_Lift/1.jpg'],
    ),
    "Knee_Across_The_Body": ExerciseDefinition(
        id="Knee_Across_The_Body",
        display_name="Knee Across The Body",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.GLUTES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.STATIC,
        secondary_muscles=[MuscleGroup.ABDUCTORS, MuscleGroup.LOWER_BACK],
        instructions="""["Lie down on the floor with your right leg straight. Bend your left leg and lower it across your body, holding the knee down toward the floor with your right hand. (The knee doesn't need to touch the floor if you're tight.)", 'Place your left arm comfortably beside you and turn your head to the left. Imagine you have a weight tied to your tailbone. let your tailbone fall back toward the floor as your chest reaches in the opposite direction to stretch your lower back. Switch sides.']""",
        images=['Knee_Across_The_Body/0.jpg', 'Knee_Across_The_Body/1.jpg'],
    ),
    "Barbell_Glute_Bridge": ExerciseDefinition(
        id="Barbell_Glute_Bridge",
        display_name="Barbell Glute Bridge",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.POWERLIFTING,
        muscle_group=MuscleGroup.GLUTES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.CALVES, MuscleGroup.HAMSTRINGS],
        instructions="""['Begin seated on the ground with a loaded barbell over your legs. Using a fat bar or having a pad on the bar can greatly reduce the discomfort caused by this exercise. Roll the bar so that it is directly above your hips, and lay down flat on the floor.', 'Begin the movement by driving through with your heels, extending your hips vertically through the bar. Your weight should be supported by your upper back and the heels of your feet.', 'Extend as far as possible, then reverse the motion to return to the starting position.']""",
        images=['Barbell_Glute_Bridge/0.jpg', 'Barbell_Glute_Bridge/1.jpg'],
    ),
    "Seated_Glute": ExerciseDefinition(
        id="Seated_Glute",
        display_name="Seated Glute",
        level=LevelType.EXPERT,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.GLUTES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.STATIC,
        secondary_muscles=[MuscleGroup.ADDUCTORS],
        instructions="""['In a seated position with your knees bent, cross one ankle over the opposite knee. Your partner will stand behind you. Now, lean forward as your partner braces your shoulders with their hands. This will be your starting position.', 'Attempt to push your torso back for 10-20 seconds, as your partner prevents any actual movement of your torso.', 'Now relax your muscles as your partner increases the stretch by gently pushing your torso forward for 10-20 seconds.']""",
        images=['Seated_Glute/0.jpg', 'Seated_Glute/1.jpg'],
    ),
    "Barbell_Hip_Thrust": ExerciseDefinition(
        id="Barbell_Hip_Thrust",
        display_name="Barbell Hip Thrust",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.POWERLIFTING,
        muscle_group=MuscleGroup.GLUTES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.CALVES, MuscleGroup.HAMSTRINGS],
        instructions="""['Begin seated on the ground with a bench directly behind you. Have a loaded barbell over your legs. Using a fat bar or having a pad on the bar can greatly reduce the discomfort caused by this exercise.', 'Roll the bar so that it is directly above your hips, and lean back against the bench so that your shoulder blades are near the top of it.', 'Begin the movement by driving through your feet, extending your hips vertically through the bar. Your weight should be supported by your shoulder blades and your feet. Extend as far as possible, then reverse the motion to return to the starting position.']""",
        images=['Barbell_Hip_Thrust/0.jpg', 'Barbell_Hip_Thrust/1.jpg'],
    ),
    "Hip_Lift_with_Band": ExerciseDefinition(
        id="Hip_Lift_with_Band",
        display_name="Hip Lift with Band",
        level=LevelType.BEGINNER,
        category=CategoryType.POWERLIFTING,
        muscle_group=MuscleGroup.GLUTES,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.CALVES, MuscleGroup.HAMSTRINGS],
        instructions="""["After choosing a suitable band, lay down in the middle of the rack, after securing the band on either side of you. If your rack doesn't have pegs, the band can be secured using heavy dumbbells or similar objects, just ensure they won't move.", 'Adjust your position so that the band is directly over your hips. Bend your knees and place your feet flat on the floor. Your hands can be on the floor or holding the band in position.', 'Keeping your shoulders on the ground, drive through your heels to raise your hips, pushing into the band as high as you can.', 'Pause at the top of the motion, and return to the starting position.']""",
        images=['Hip_Lift_with_Band/0.jpg', 'Hip_Lift_with_Band/1.jpg'],
    ),
}
