from exercises.base import ExerciseDefinition
from enums import MuscleGroup, EquipmentType, MechanicsType, MajorMuscleGroup, ForceType, LevelType, CategoryType

HAMSTRINGS_EXERCISES = {
    "Front_Leg_Raises": ExerciseDefinition(
        id="Front_Leg_Raises",
        display_name="Front Leg Raises",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        instructions="""['Stand next to a chair or other support, holding on with one hand.', 'Swing your leg forward, keeping the leg straight. Continue with a downward swing, bringing the leg as far back as your flexibility allows. Repeat 5-10 times, and then switch legs.']""",
        images=['Front_Leg_Raises/0.jpg', 'Front_Leg_Raises/1.jpg'],
    ),
    "Smith_Machine_Stiff-Legged_Deadlift": ExerciseDefinition(
        id="Smith_Machine_Stiff-Legged_Deadlift",
        display_name="Smith Machine Stiff-Legged Deadlift",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.MACHINE,
        secondary_muscles=[MuscleGroup.GLUTES, MuscleGroup.LOWER_BACK],
        instructions="""['To begin, set the bar on the smith machine to a height that is around the middle of your thighs. Once the correct height is chosen and the bar is loaded, grasp the bar using a pronated (palms forward) grip that is shoulder width apart. You may need some wrist wraps if using a significant amount of weight.', 'Lift the bar up by fully extending your arms while keeping your back straight. Stand with your torso straight and your legs spaced using a shoulder width or narrower stance. The knees should be slightly bent. This is your starting position.', 'Keeping the knees stationary, lower the barbell to over the top of your feet by bending at the waist while keeping your back straight. Keep moving forward as if you were going to pick something from the floor until you feel a stretch on the hamstrings. Exhale as you perform this movement', 'Start bringing your torso up straight again as soon as you feel the hamstrings stretch by extending your hips and waist until you are back at the starting position. Inhale as you perform this movement.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Smith_Machine_Stiff-Legged_Deadlift/0.jpg', 'Smith_Machine_Stiff-Legged_Deadlift/1.jpg'],
    ),
    "Kettlebell_Dead_Clean": ExerciseDefinition(
        id="Kettlebell_Dead_Clean",
        display_name="Kettlebell Dead Clean",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.CALVES, MuscleGroup.GLUTES, MuscleGroup.LOWER_BACK, MuscleGroup.QUADS, MuscleGroup.TRAPS],
        instructions="""['Place kettlebell between your feet. To get in the starting position, push your butt back and look straight ahead.', 'Clean the kettlebell to your shoulder. Clean the kettlebell to your shoulders by extending through the legs and hips as you raise the kettlebell towards your shoulder. The wrist should rotate as you do so.', 'Lower the kettlebell, keeping the hamstrings loaded by keeping your back straight and your butt out.']""",
        images=['Kettlebell_Dead_Clean/0.jpg', 'Kettlebell_Dead_Clean/1.jpg'],
    ),
    "Good_Morning_off_Pins": ExerciseDefinition(
        id="Good_Morning_off_Pins",
        display_name="Good Morning off Pins",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.POWERLIFTING,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.ABS, MuscleGroup.GLUTES, MuscleGroup.LOWER_BACK],
        instructions="""['Begin with a bar on a rack at about the same height as your stomach. Bend over underneath the bar and rack the bar across the rear of your shoulders as you would a power squat, not on top of your shoulders. At the proper height, you should be near parallel to the floor when bent over. Keep your back tight, shoulder blades pinched together, and your knees slightly bent. Keep your back arched and your cervical spine in proper alignment.', 'Begin the motion by extending through the hips with your glutes and hamstrings, and you are standing with the weight. Slowly lower the weight back to the pins returning to the starting position.']""",
        images=['Good_Morning_off_Pins/0.jpg', 'Good_Morning_off_Pins/1.jpg'],
    ),
    "Standing_Toe_Touches": ExerciseDefinition(
        id="Standing_Toe_Touches",
        display_name="Standing Toe Touches",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.STATIC,
        secondary_muscles=[MuscleGroup.CALVES],
        instructions="""['Stand with some space in front and behind you.', 'Bend at the waist, keeping your legs straight, until you can relax and let your upper body hang down in front of you. Let your arms and hands hang down naturally. Hold for 10 to 20 seconds.']""",
        images=['Standing_Toe_Touches/0.jpg', 'Standing_Toe_Touches/1.jpg'],
    ),
    "Romanian_Deadlift_from_Deficit": ExerciseDefinition(
        id="Romanian_Deadlift_from_Deficit",
        display_name="Romanian Deadlift from Deficit",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.OLYMPIC_WEIGHTLIFTING,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.FOREARMS, MuscleGroup.GLUTES, MuscleGroup.LOWER_BACK, MuscleGroup.TRAPS],
        instructions="""["Begin standing while holding a bar at arm's length in front of you. You can stand on a raised platform to increase the range of motion.", 'Begin by flexing the knees slightly, and then flex at the hip, moving your butt back as far as possible, lowering the torso as far as flexibility allows. The back should remain in absolute extension at all times, and the bar should remain in contact with the legs. If done properly, there should be heavy tension felt in the hamstrings.', 'Reverse the motion to return to the starting position.']""",
        images=['Romanian_Deadlift_from_Deficit/0.jpg', 'Romanian_Deadlift_from_Deficit/1.jpg'],
    ),
    "Linear_3-Part_Start_Technique": ExerciseDefinition(
        id="Linear_3-Part_Start_Technique",
        display_name="Linear 3-Part Start Technique",
        level=LevelType.BEGINNER,
        category=CategoryType.PLYOMETRICS,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.CALVES, MuscleGroup.QUADS],
        instructions="""['This drill helps you accelerate as quickly as possible into a sprint from a dead stop. It helps to use a line to start from. Begin with two feet on the line. Place your left foot with the toe next to your right ankle. Place your right foot 4-6 inches behind the left.', 'Place your right hand onto the line, and thing bring your nose close to your left knee.', 'Squat down as you lean foward, your head being lower than your hips and your weight loaded onto the left leg. This will be your starting position.', 'Take your left hand up so that it is parallel to the ground, pointing behind you, and explode out when ready.']""",
        images=['Linear_3-Part_Start_Technique/0.jpg', 'Linear_3-Part_Start_Technique/1.jpg'],
    ),
    "Power_Stairs": ExerciseDefinition(
        id="Power_Stairs",
        display_name="Power Stairs",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRONGMAN,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.OTHER,
        secondary_muscles=[MuscleGroup.ADDUCTORS, MuscleGroup.CALVES, MuscleGroup.GLUTES, MuscleGroup.LOWER_BACK, MuscleGroup.QUADS, MuscleGroup.SHOULDERS, MuscleGroup.TRAPS],
        instructions="""['In the power stairs, implements are moved up a staircase. For training purposes, these can be performed with a tire or box.', 'Begin by taking the implement with both hands. Set your feet wide, with your head and chest up. Drive through the ground with your heels, extending your knees and hips to raise the weight from the ground.', 'As you lean back, attempt to swing the weight onto the stairs, which are usually around 16-18" high. You can use your legs to help push the weight onto the stair.', 'Repeat for 3-5 repetitions, and continue with a heavier weight, moving as fast as possible.']""",
        images=['Power_Stairs/0.jpg', 'Power_Stairs/1.jpg'],
    ),
    "Natural_Glute_Ham_Raise": ExerciseDefinition(
        id="Natural_Glute_Ham_Raise",
        display_name="Natural Glute Ham Raise",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.CALVES, MuscleGroup.GLUTES, MuscleGroup.LOWER_BACK],
        instructions="""['Using the leg pad of a lat pulldown machine or a preacher bench, position yourself so that your ankles are under the pads, knees on the seat, and you are facing away from the machine. You should be upright and maintaining good posture.', 'This will be your starting position. Lower yourself under control until your knees are almost completely straight.', 'Remaining in control, raise yourself back up to the starting position.', 'If you are unable to complete a rep, use a band, a partner, or push off of a box to aid in completing a repetition.']""",
        images=['Natural_Glute_Ham_Raise/0.jpg', 'Natural_Glute_Ham_Raise/1.jpg'],
    ),
    "Power_Snatch": ExerciseDefinition(
        id="Power_Snatch",
        display_name="Power Snatch",
        level=LevelType.EXPERT,
        category=CategoryType.OLYMPIC_WEIGHTLIFTING,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.CALVES, MuscleGroup.GLUTES, MuscleGroup.LOWER_BACK, MuscleGroup.QUADS, MuscleGroup.SHOULDERS, MuscleGroup.TRAPS, MuscleGroup.TRICEPS],
        instructions="""['Begin with a loaded barbell on the floor. The bar should be close to or touching the shins, and a wide grip should be taken on the bar. The feet should be directly below the hips, with the feet turned out as needed. Lower the hips, with the chest up and the head looking forward. The shoulders should be just in front of the bar. This will be the starting position.', 'Begin the first pull by driving through the front of the heels, raising the bar from the ground. The back angle should stay the same until the bar passes the knees.', 'Transition into the second pull by extending through the hips knees and ankles, driving the bar up as quickly as possible. The bar should be close to the body. At peak extension, shrug the shoulders and allow the elbows to flex to the side.', 'As you move your feet into the receiving position, a slightly wider position, pull yourself below the bar as you elevate the bar overhead. The bar should be received in a partial squat. Continue raising the bar to the overhead position, receiving the bar locked out overhead.', 'Return to a standing position with the weight over head.']""",
        images=['Power_Snatch/0.jpg', 'Power_Snatch/1.jpg'],
    ),
    "Upper_Back-Leg_Grab": ExerciseDefinition(
        id="Upper_Back-Leg_Grab",
        display_name="Upper Back-Leg Grab",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.STATIC,
        secondary_muscles=[MuscleGroup.LOWER_BACK],
        instructions="""['While seated, bend forward to hug your thighs from underneath with both arms.', 'Keep your knees together and your legs extended out as you bring your chest down to your knees. You can also stretch your middle back by pulling your back away from your knees as your hugging them.']""",
        images=['Upper_Back-Leg_Grab/0.jpg', 'Upper_Back-Leg_Grab/1.jpg'],
    ),
    "Band_Good_Morning_Pull_Through": ExerciseDefinition(
        id="Band_Good_Morning_Pull_Through",
        display_name="Band Good Morning (Pull Through)",
        level=LevelType.BEGINNER,
        category=CategoryType.POWERLIFTING,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.GLUTES, MuscleGroup.LOWER_BACK],
        instructions="""['Loop the band around a post. Standing a little ways away, loop the opposite end around the neck. Your hands can help hold the band in position.', 'Begin by bending at the hips, getting your butt back as far as possible. Keep your back flat and bend forward to about 90 degrees. Your knees should be only slightly bent.', 'Return to the starting position be driving through with the hips to come back to a standing position.']""",
        images=['Band_Good_Morning_Pull_Through/0.jpg', 'Band_Good_Morning_Pull_Through/1.jpg'],
    ),
    "Linear_Acceleration_Wall_Drill": ExerciseDefinition(
        id="Linear_Acceleration_Wall_Drill",
        display_name="Linear Acceleration Wall Drill",
        level=LevelType.BEGINNER,
        category=CategoryType.PLYOMETRICS,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.CALVES, MuscleGroup.GLUTES, MuscleGroup.QUADS],
        instructions="""['Lean at around 45 degrees against a wall. Your feet should be together, glutes contracted.', 'Begin by lifting your right knee quickly, pausing, and then driving it straight down into the ground.', 'Switch legs, raising the opposite knee, and then attacking the ground straight down.', 'Repeat once more with your right leg, and as soon as the right foot strikes the ground hammer them out rapidly, alternating left and right as fast as you can.']""",
        images=['Linear_Acceleration_Wall_Drill/0.jpg', 'Linear_Acceleration_Wall_Drill/1.jpg'],
    ),
    "Front_Box_Jump": ExerciseDefinition(
        id="Front_Box_Jump",
        display_name="Front Box Jump",
        level=LevelType.BEGINNER,
        category=CategoryType.PLYOMETRICS,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.OTHER,
        secondary_muscles=[MuscleGroup.ABDUCTORS, MuscleGroup.ADDUCTORS, MuscleGroup.CALVES, MuscleGroup.GLUTES, MuscleGroup.QUADS],
        instructions="""['Begin with a box of an appropriate height 1-2 feet in front of you. Stand with your feet should width apart. This will be your starting position.', 'Perform a short squat in preparation for jumping, swinging your arms behind you.', 'Rebound out of this position, extending through the hips, knees, and ankles to jump as high as possible. Swing your arms forward and up.', 'Land on the box with the knees bent, absorbing the impact through the legs. You can jump from the box back to the ground, or preferably step down one leg at a time.']""",
        images=['Front_Box_Jump/0.jpg', 'Front_Box_Jump/1.jpg'],
    ),
    "Open_Palm_Kettlebell_Clean": ExerciseDefinition(
        id="Open_Palm_Kettlebell_Clean",
        display_name="Open Palm Kettlebell Clean",
        level=LevelType.EXPERT,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.GLUTES, MuscleGroup.LOWER_BACK, MuscleGroup.QUADS, MuscleGroup.SHOULDERS],
        instructions="""['Place one kettlebell between your feet. Clean the kettlebell by extending through the legs and hips as you raise the kettlebell towards your shoulders.', 'Release the kettlebell as it comes up, and let it flip so that the ball of the kettlebell lands in the palms of your hands.', 'Release the kettlebell out in front of you and catch the handle with both hands. Lower the kettlebell to the starting position and repeat.']""",
        images=['Open_Palm_Kettlebell_Clean/0.jpg', 'Open_Palm_Kettlebell_Clean/1.jpg'],
    ),
    "Kettlebell_One-Legged_Deadlift": ExerciseDefinition(
        id="Kettlebell_One-Legged_Deadlift",
        display_name="Kettlebell One-Legged Deadlift",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.GLUTES, MuscleGroup.LOWER_BACK],
        instructions="""['Hold a kettlebell by the handle in one hand. Stand on one leg, on the same side that you hold the kettlebell.', 'Keeping that knee slightly bent, perform a stiff legged deadlift by bending at the hip, extending your free leg behind you for balance.', 'Continue lowering the kettlebell until you are parallel to the ground, and then return to the upright position.']""",
        images=['Kettlebell_One-Legged_Deadlift/0.jpg', 'Kettlebell_One-Legged_Deadlift/1.jpg'],
    ),
    "Standing_Leg_Curl": ExerciseDefinition(
        id="Standing_Leg_Curl",
        display_name="Standing Leg Curl",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.MACHINE,
        instructions="""['Adjust the machine lever to fit your height and lie with your torso bent at the waist facing forward around 30-45 degrees (since an angled position is more favorable for hamstrings recruitment) with the pad of the lever on the back of your right leg (just a few inches under the calves) and the front of the right leg on top of the machine pad.', 'Keeping the torso bent forward, ensure your leg is fully stretched and grab the side handles of the machine. Position your toes straight. This will be your starting position.', 'As you exhale, curl your right leg up as far as possible without lifting the upper leg from the pad. Once you hit the fully contracted position, hold it for a second.', 'As you inhale, bring the legs back to the initial position. Repeat for the recommended amount of repetitions.', 'Perform the same exercise now for the left leg.']""",
        images=['Standing_Leg_Curl/0.jpg', 'Standing_Leg_Curl/1.jpg'],
    ),
    "Runners_Stretch": ExerciseDefinition(
        id="Runners_Stretch",
        display_name="Runner's Stretch",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.STATIC,
        secondary_muscles=[MuscleGroup.CALVES],
        instructions="""["It's easiest to get into this stretch if you start standing up, put one leg behind you, and slowly lower your torso down to the floor.", 'Keep the front heel on the floor (if it lifts up, scoot your other leg further back).', "Place your hands on either side of your front leg. To get more out of this stretch, push your butt up toward the ceiling, and then gradually lower it back toward the floor. You'll Stretch the hip flexor of the back leg and the hamstring and buttocks of the front."]""",
        images=['Runners_Stretch/0.jpg', 'Runners_Stretch/1.jpg'],
    ),
    "Wide_Stance_Stiff_Legs": ExerciseDefinition(
        id="Wide_Stance_Stiff_Legs",
        display_name="Wide Stance Stiff Legs",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.OLYMPIC_WEIGHTLIFTING,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.ADDUCTORS, MuscleGroup.GLUTES, MuscleGroup.LOWER_BACK],
        instructions="""['Begin with a barbell loaded on the floor. Adopt a wide stance, and then bend at the hips to grab the bar. Your hips should be as far back as possible, and your legs nearly straight. Keep your back straight, and your head and chest up. This will be your starting position.', 'Begin the movement be engaging the hips, driving them forward as you allow the arms to hang straight. Continue until you are standing straight up, and then slowly return the weight to the starting position. For successive reps, the weight need not touch the floor.']""",
        images=['Wide_Stance_Stiff_Legs/0.jpg', 'Wide_Stance_Stiff_Legs/1.jpg'],
    ),
    "Prowler_Sprint": ExerciseDefinition(
        id="Prowler_Sprint",
        display_name="Prowler Sprint",
        level=LevelType.BEGINNER,
        category=CategoryType.CARDIO,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.OTHER,
        secondary_muscles=[MuscleGroup.CALVES, MuscleGroup.CHEST, MuscleGroup.GLUTES, MuscleGroup.QUADS, MuscleGroup.SHOULDERS],
        instructions="""['Place your sled on an appropriate surface, loaded to a suitable weight. The sled should provide enough resistance to require effort, but not so heavy that you are significantly slowed down.', 'You may use the upright or the low handles for this exercise. Place your hands on the handles with your arms extended, leaning into the implement.', 'With good posture, drive through the ground with alternating, short steps. Move as fast as you can for a short distance.']""",
        images=['Prowler_Sprint/0.jpg', 'Prowler_Sprint/1.jpg'],
    ),
    "Inchworm": ExerciseDefinition(
        id="Inchworm",
        display_name="Inchworm",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        mechanics_type=MechanicsType.COMPOUND,
        instructions="""['Stand with your feet close together. Keeping your legs straight, stretch down and put your hands on the floor directly in front of you. This will be your starting position.', 'Begin by walking your hands forward slowly, alternating your left and your right. As you do so, bend only at the hip, keeping your legs straight.', 'Keep going until your body is parallel to the ground in a pushup position.', 'Now, keep your hands in place and slowly take short steps with your feet, moving only a few inches at a time.', 'Continue walking until your feet are by hour hands, keeping your legs straight as you do so.']""",
        images=['Inchworm/0.jpg', 'Inchworm/1.jpg'],
    ),
    "Standing_Hamstring_and_Calf_Stretch": ExerciseDefinition(
        id="Standing_Hamstring_and_Calf_Stretch",
        display_name="Standing Hamstring and Calf Stretch",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.STATIC,
        equipment_type=EquipmentType.OTHER,
        instructions="""['Being by looping a belt, band, or rope around one foot. While standing, place that foot forward.', 'Bend your back leg, while keeping the front one straight. Now raise the toes of your front foot off of the ground and lean forward.', 'Using the belt, pull on the top of the foot to increase the stretch in the calf. Hold for 10-20 seconds and repeat with the other foot.']""",
        images=['Standing_Hamstring_and_Calf_Stretch/0.jpg', 'Standing_Hamstring_and_Calf_Stretch/1.jpg'],
    ),
    "Hamstring-SMR": ExerciseDefinition(
        id="Hamstring-SMR",
        display_name="Hamstring-SMR",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.STATIC,
        mechanics_type=MechanicsType.ISOLATION,
        instructions="""['In a seated position, extend your legs over a foam roll so that it is position on the back of the upper legs. Place your hands to the side or behind you to help support your weight. This will be your starting position.', 'Using your hands, lift your hips off of the floor and shift your weight on the foam roll to one leg. Relax the hamstrings of the leg you are stretching.', 'Roll over the foam from below the hip to above the back of the knee, pausing at points of tension for 10-30 seconds. Repeat for the other leg.']""",
        images=['Hamstring-SMR/0.jpg', 'Hamstring-SMR/1.jpg'],
    ),
    "Hang_Snatch_-_Below_Knees": ExerciseDefinition(
        id="Hang_Snatch_-_Below_Knees",
        display_name="Hang Snatch - Below Knees",
        level=LevelType.EXPERT,
        category=CategoryType.OLYMPIC_WEIGHTLIFTING,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.ABS, MuscleGroup.CALVES, MuscleGroup.FOREARMS, MuscleGroup.GLUTES, MuscleGroup.LOWER_BACK, MuscleGroup.QUADS, MuscleGroup.SHOULDERS, MuscleGroup.TRAPS],
        instructions="""['Begin with a wide grip on the bar, with an overhand or hook grip. The feet should be directly below the hips with the feet turned out. Your knees should be slightly bent, and the torso inclined forward. The spine should be fully extended and the head facing forward. The bar should be just below the knees. This will be your starting position.', 'Aggressively extend through the legs and hips. At peak extension, shrug the shoulders and allow the elbows to flex to the side.', 'As you move your feet into the receiving position, forcefully pull yourself below the bar as you elevate the bar overhead. Receive the bar with your body as low as possible and the arms fully extended overhead.', 'Return to a standing position with the weight overhead, and then return the weight to the floor under control.']""",
        images=['Hang_Snatch_-_Below_Knees/0.jpg', 'Hang_Snatch_-_Below_Knees/1.jpg'],
    ),
    "One-Arm_Kettlebell_Clean": ExerciseDefinition(
        id="One-Arm_Kettlebell_Clean",
        display_name="One-Arm Kettlebell Clean",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.GLUTES, MuscleGroup.LOWER_BACK, MuscleGroup.SHOULDERS, MuscleGroup.TRAPS],
        instructions="""['Place kettlebell between your feet. As you bend down to grab the kettlebell, push your butt back and keep your eyes looking forward.', 'Clean the kettlebell to your shoulders by extending through the legs and hips as you raise the kettlebell towards your shoulder. The wrist should rotate as you do so.', 'Return the weight to the starting position.']""",
        images=['One-Arm_Kettlebell_Clean/0.jpg', 'One-Arm_Kettlebell_Clean/1.jpg'],
    ),
    "Sumo_Deadlift": ExerciseDefinition(
        id="Sumo_Deadlift",
        display_name="Sumo Deadlift",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.POWERLIFTING,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.ADDUCTORS, MuscleGroup.FOREARMS, MuscleGroup.GLUTES, MuscleGroup.LOWER_BACK, MuscleGroup.QUADS, MuscleGroup.TRAPS],
        instructions="""['Begin with a bar loaded on the ground. Approach the bar so that the bar intersects the middle of the feet. The feet should be set very wide, near the collars. Bend at the hips to grip the bar. The arms should be directly below the shoulders, inside the legs, and you can use a pronated grip, a mixed grip, or hook grip. Relax the shoulders, which in effect lengthens your arms.', 'Take a breath, and then lower your hips, looking forward with your head with your chest up. Drive through the floor, spreading your feet apart, with your weight on the back half of your feet. Extend through the hips and knees.', 'As the bar passes through the knees, lean back and drive the hips into the bar, pulling your shoulder blades together.', 'Return the weight to the ground by bending at the hips and controlling the weight on the way down.']""",
        images=['Sumo_Deadlift/0.jpg', 'Sumo_Deadlift/1.jpg'],
    ),
    "Prone_Manual_Hamstring": ExerciseDefinition(
        id="Prone_Manual_Hamstring",
        display_name="Prone Manual Hamstring",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.STATIC,
        mechanics_type=MechanicsType.ISOLATION,
        instructions="""['You will need a partner for this exercise. Lay face down with your legs straight. Your assistant will place their hand on your heel.', 'To begin, flex the knee to curl your leg up. Your partner should provide resistance, starting light and increasing the pressure as the movement is completed. Communicate with your partner to monitor appropriate resistance levels.', 'Pause at the top, returning the leg to the starting position as your partner provides resistance going the other direction.']""",
        images=['Prone_Manual_Hamstring/0.jpg', 'Prone_Manual_Hamstring/1.jpg'],
    ),
    "Sumo_Deadlift_with_Chains": ExerciseDefinition(
        id="Sumo_Deadlift_with_Chains",
        display_name="Sumo Deadlift with Chains",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.POWERLIFTING,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.ABDUCTORS, MuscleGroup.ADDUCTORS, MuscleGroup.FOREARMS, MuscleGroup.GLUTES, MuscleGroup.LOWER_BACK, MuscleGroup.QUADS, MuscleGroup.TRAPS],
        instructions="""["You can attach the chains to the sleeves of the bar, or just drape the middle over the bar so there is a greater weight increase as you lift. Attempt to keep the ends of the chains away from the plates so you don't hit them when you lower the weight.", 'Begin with a bar loaded on the ground. Approach the bar so that the bar intersects the middle of the feet. The feet should be set very wide, near the collars. Bend at the hips to grip the bar. The arms should be directly below the shoulders, inside the legs, and you can use a pronated grip, a mixed grip, or hook grip. Relax the shoulders, which in effect lengthens your arms.', 'Take a breath, and then lower your hips, looking forward with your head with your chest up. Drive through the floor, spreading your feet apart, with your weight on the back half of your feet. Extend through the hips and knees.', 'As the bar passes through the knees, lean back and drive the hips into the bar, pulling your shoulder blades together.', 'Return the weight to the ground by bending at the hips and controlling the weight on the way down.']""",
        images=['Sumo_Deadlift_with_Chains/0.jpg', 'Sumo_Deadlift_with_Chains/1.jpg'],
    ),
    "Seated_Leg_Curl": ExerciseDefinition(
        id="Seated_Leg_Curl",
        display_name="Seated Leg Curl",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.MACHINE,
        instructions="""['Adjust the machine lever to fit your height and sit on the machine with your back against the back support pad.', 'Place the back of lower leg on top of padded lever (just a few inches under the calves) and secure the lap pad against your thighs, just above the knees. Then grasp the side handles on the machine as you point your toes straight (or you can also use any of the other two stances) and ensure that the legs are fully straight right in front of you. This will be your starting position.', 'As you exhale, pull the machine lever as far as possible to the back of your thighs by flexing at the knees. Keep your torso stationary at all times. Hold the contracted position for a second.', 'Slowly return to the starting position as you breathe in.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Seated_Leg_Curl/0.jpg', 'Seated_Leg_Curl/1.jpg'],
    ),
    "Glute_Ham_Raise": ExerciseDefinition(
        id="Glute_Ham_Raise",
        display_name="Glute Ham Raise",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.POWERLIFTING,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.MACHINE,
        secondary_muscles=[MuscleGroup.CALVES, MuscleGroup.GLUTES],
        instructions="""['Begin by adjusting the equipment to fit your body. Place your feet against the footplate in between the rollers as you lie facedown. Your knees should be just behind the pad.', 'Start from the bottom of the movement. Keep your back arched as you begin the movement by flexing the knees. Drive your toes into the foot plate as you do so. Keep your upper body straight, and continue until your body is upright.', 'Return to the starting position, keeping your descent under control.']""",
        images=['Glute_Ham_Raise/0.jpg', 'Glute_Ham_Raise/1.jpg'],
    ),
    "Clean": ExerciseDefinition(
        id="Clean",
        display_name="Clean",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.OLYMPIC_WEIGHTLIFTING,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.CALVES, MuscleGroup.FOREARMS, MuscleGroup.GLUTES, MuscleGroup.LOWER_BACK, MuscleGroup.QUADS, MuscleGroup.SHOULDERS, MuscleGroup.TRAPS],
        instructions="""['With a barbell on the floor close to the shins, take an overhand (or hook) grip just outside the legs. Lower your hips with the weight focused on the heels, back straight, head facing forward, chest up, with your shoulders just in front of the bar. This will be your starting position.', '', 'Begin the first pull by driving through the heels, extending your knees. Your back angle should stay the same, and your arms should remain straight. Move the weight with control as you continue to above the knees.', 'Next comes the second pull, the main source of acceleration for the clean. As the bar approaches the mid-thigh position, begin extending through the hips. In a jumping motion, accelerate by extending the hips, knees, and ankles, using speed to move the bar upward. There should be no need to actively pull through the arms to accelerate the weight; at the end of the second pull, the body should be fully extended, leaning slightly back, with the arms still extended.', 'As full extension is achieved, transition into the third pull by aggressively shrugging and flexing the arms with the elbows up and out. At peak extension, aggressively pull yourself down, rotating your elbows under the bar as you do so. Receive the bar in a front squat position, the depth of which is dependent upon the height of the bar at the end of the third pull. The bar should be racked onto the protracted shoulders, lightly touching the throat with the hands relaxed. Continue to descend to the bottom squat position, which will help in the recovery.', 'Immediately recover by driving through the heels, keeping the torso upright and elbows up. Continue until you have risen to a standing position.']""",
        images=['Clean/0.jpg', 'Clean/1.jpg'],
    ),
    "Sumo_Deadlift_with_Bands": ExerciseDefinition(
        id="Sumo_Deadlift_with_Bands",
        display_name="Sumo Deadlift with Bands",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.POWERLIFTING,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.ADDUCTORS, MuscleGroup.FOREARMS, MuscleGroup.GLUTES, MuscleGroup.LOWER_BACK, MuscleGroup.QUADS, MuscleGroup.TRAPS],
        instructions="""['To deadlift with short bands, simply loop them over the bar before you start, and step into them to set up. Ensure that they under the back half of your foot, directly where you are driving into the floor.', 'Begin with a bar loaded on the ground. Approach the bar so that the bar intersects the middle of the feet. The feet should be set very wide, near the collars. Bend at the hips to grip the bar. The arms should be directly below the shoulders, inside the legs, and you can use a pronated grip, a mixed grip, or hook grip.', 'Take a breath, and then lower your hips, looking forward with your head with your chest up. Drive through the floor, spreading your feet apart, with your weight on the back half of your feet. Extend through the hips and knees.', 'As the bar passes through the knees, lean back and drive the hips into the bar, pulling your shoulder blades together.', 'Return the weight to the ground by bending at the hips and controlling the weight on the way down.']""",
        images=['Sumo_Deadlift_with_Bands/0.jpg', 'Sumo_Deadlift_with_Bands/1.jpg'],
    ),
    "Lying_Leg_Curls": ExerciseDefinition(
        id="Lying_Leg_Curls",
        display_name="Lying Leg Curls",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.MACHINE,
        instructions="""['Adjust the machine lever to fit your height and lie face down on the leg curl machine with the pad of the lever on the back of your legs (just a few inches under the calves). Tip: Preferably use a leg curl machine that is angled as opposed to flat since an angled position is more favorable for hamstrings recruitment.', 'Keeping the torso flat on the bench, ensure your legs are fully stretched and grab the side handles of the machine. Position your toes straight (or you can also use any of the other two stances described on the foot positioning section). This will be your starting position.', 'As you exhale, curl your legs up as far as possible without lifting the upper legs from the pad. Once you hit the fully contracted position, hold it for a second.', 'As you inhale, bring the legs back to the initial position. Repeat for the recommended amount of repetitions.']""",
        images=['Lying_Leg_Curls/0.jpg', 'Lying_Leg_Curls/1.jpg'],
    ),
    "Hamstring_Stretch": ExerciseDefinition(
        id="Hamstring_Stretch",
        display_name="Hamstring Stretch",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.STATIC,
        mechanics_type=MechanicsType.ISOLATION,
        instructions="""['Lie on your back with one leg extended above you, with the hip at ninety degrees. Keep the other leg flat on the floor.', 'Loop a belt, band, or rope over the ball of your foot. This will be your starting position.', 'Pull on the belt to create tension in the calves and hamstrings. Hold this stretch for 10-30 seconds, and repeat with the other leg.']""",
        images=['Hamstring_Stretch/0.jpg', 'Hamstring_Stretch/1.jpg'],
    ),
    "90_90_Hamstring": ExerciseDefinition(
        id="90_90_Hamstring",
        display_name="90/90 Hamstring",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        secondary_muscles=[MuscleGroup.CALVES],
        instructions="""['Lie on your back, with one leg extended straight out.', 'With the other leg, bend the hip and knee to 90 degrees. You may brace your leg with your hands if necessary. This will be your starting position.', 'Extend your leg straight into the air, pausing briefly at the top. Return the leg to the starting position.', 'Repeat for 10-20 repetitions, and then switch to the other leg.']""",
        images=['90_90_Hamstring/0.jpg', '90_90_Hamstring/1.jpg'],
    ),
    "Split_Squats": ExerciseDefinition(
        id="Split_Squats",
        display_name="Split Squats",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        secondary_muscles=[MuscleGroup.CALVES, MuscleGroup.GLUTES, MuscleGroup.QUADS],
        instructions="""['Being in a standing position. Jump into a split leg position, with one leg forward and one leg back, flexing the knees and lowering your hips slightly as you do so.', 'As you descend, immediately reverse direction, standing back up and jumping, reversing the position of your legs. Repeat 5-10 times on each leg.']""",
        images=['Split_Squats/0.jpg', 'Split_Squats/1.jpg'],
    ),
    "The_Straddle": ExerciseDefinition(
        id="The_Straddle",
        display_name="The Straddle",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.STATIC,
        secondary_muscles=[MuscleGroup.ADDUCTORS, MuscleGroup.CALVES],
        instructions="""['Begin in a seated, upright position. Start by extending your legs in front of you in a V.', 'With your hands on the floor, lean forward as far as possible. Hold for 10 to 20 seconds.']""",
        images=['The_Straddle/0.jpg', 'The_Straddle/1.jpg'],
    ),
    "Vertical_Swing": ExerciseDefinition(
        id="Vertical_Swing",
        display_name="Vertical Swing",
        level=LevelType.BEGINNER,
        category=CategoryType.PLYOMETRICS,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.DUMBBELL,
        secondary_muscles=[MuscleGroup.GLUTES, MuscleGroup.QUADS, MuscleGroup.SHOULDERS],
        instructions="""['Allow the dumbbell to hang at arms length between your legs, holding it with both hands. Keep your back straight and your head up.', 'Swing the dumbbell between your legs, flexing at the hips and bending the knees slightly.', 'Powerfully reverse the motion by extending at the hips, knees, and ankles to propel yourself upward, swinging the dumbell over your head.', 'As you land, absorb the impact through your legs and draw the dumbbell to your torso before the next repetition.']""",
        images=['Vertical_Swing/0.jpg', 'Vertical_Swing/1.jpg'],
    ),
    "Alternating_Hang_Clean": ExerciseDefinition(
        id="Alternating_Hang_Clean",
        display_name="Alternating Hang Clean",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.BICEPS, MuscleGroup.CALVES, MuscleGroup.FOREARMS, MuscleGroup.GLUTES, MuscleGroup.LOWER_BACK, MuscleGroup.TRAPS],
        instructions="""['Place two kettlebells between your feet. To get in the starting position, push your butt back and look straight ahead.', 'Clean one kettlebell to your shoulder and hold on to the other kettlebell in a hanging position. Clean the kettlebell to your shoulder by extending through the legs and hips as you pull the kettlebell towards your shoulders. Rotate your wrist as you do so.', 'Lower the cleaned kettlebell to a hanging position and clean the alternate kettlebell. Repeat.']""",
        images=['Alternating_Hang_Clean/0.jpg', 'Alternating_Hang_Clean/1.jpg'],
    ),
    "Box_Jump_Multiple_Response": ExerciseDefinition(
        id="Box_Jump_Multiple_Response",
        display_name="Box Jump (Multiple Response)",
        level=LevelType.BEGINNER,
        category=CategoryType.PLYOMETRICS,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.OTHER,
        secondary_muscles=[MuscleGroup.ABDUCTORS, MuscleGroup.ADDUCTORS, MuscleGroup.CALVES, MuscleGroup.GLUTES, MuscleGroup.QUADS],
        instructions="""["Assume a relaxed stance facing the box or platform approximately an arm's length away. Arms should be down at the sides and legs slightly bent.", 'Using the arms to aid in the initial burst, jump upward and forward, landing with feet simultaneously on top of the box or platform.', 'Immediately drop or jump back down to the original starting place; then repeat the sequence.']""",
        images=['Box_Jump_Multiple_Response/0.jpg', 'Box_Jump_Multiple_Response/1.jpg'],
    ),
    "Lunge_Pass_Through": ExerciseDefinition(
        id="Lunge_Pass_Through",
        display_name="Lunge Pass Through",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.CALVES, MuscleGroup.GLUTES, MuscleGroup.QUADS],
        instructions="""['Stand with your torso upright holding a kettlebell in your right hand. This will be your starting position.', 'Step forward with your left foot and lower your upper body down by flexing the hip and the knee, keeping the torso upright. Lower your back knee until it nearly touches the ground.', 'As you lunge, pass the kettlebell under your front leg to your opposite hand.', 'Pressing through the heel of your foot, return to the starting position.', 'Repeat the movement for the recommended amount of repetitions, alternating legs.']""",
        images=['Lunge_Pass_Through/0.jpg', 'Lunge_Pass_Through/1.jpg'],
    ),
    "Muscle_Snatch": ExerciseDefinition(
        id="Muscle_Snatch",
        display_name="Muscle Snatch",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.OLYMPIC_WEIGHTLIFTING,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.GLUTES, MuscleGroup.LOWER_BACK, MuscleGroup.QUADS, MuscleGroup.SHOULDERS, MuscleGroup.TRICEPS],
        instructions="""['Begin with a loaded barbell held at the mid thigh position with a wide grip. The feet should be directly below the hips, with the feet turned out as needed. Lower the hips, with the chest up and the head looking forward. The shoulders should be just in front of the bar. This will be your starting position.', 'Begin the pull by driving through the front of the heels, raising the bar. Transition into the second pull by extending through the hips knees and ankles, driving the bar up as quickly as possible. The bar should be close to the body.', 'Continue raising the bar to the overhead position, without rebending the knees.']""",
        images=['Muscle_Snatch/0.jpg', 'Muscle_Snatch/1.jpg'],
    ),
    "Box_Skip": ExerciseDefinition(
        id="Box_Skip",
        display_name="Box Skip",
        level=LevelType.BEGINNER,
        category=CategoryType.PLYOMETRICS,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.OTHER,
        secondary_muscles=[MuscleGroup.ABDUCTORS, MuscleGroup.ADDUCTORS, MuscleGroup.CALVES, MuscleGroup.GLUTES, MuscleGroup.QUADS],
        instructions="""['You will need several boxes lined up about 8 feet apart.', 'Begin facing the first box with one leg slightly behind the other.', 'Drive off the back leg, attempting to gain as much height with the hips as possible.', 'Immediately upon landing on the box, drive the other leg forward and upward to gain height and distance, leaping from the box. Land between the first two boxes with the same leg that landed on the first box.', 'Then, step to the next box and repeat.']""",
        images=['Box_Skip/0.jpg', 'Box_Skip/1.jpg'],
    ),
    "Power_Clean": ExerciseDefinition(
        id="Power_Clean",
        display_name="Power Clean",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.CALVES, MuscleGroup.FOREARMS, MuscleGroup.GLUTES, MuscleGroup.LOWER_BACK, MuscleGroup.QUADS, MuscleGroup.SHOULDERS, MuscleGroup.TRAPS, MuscleGroup.TRICEPS],
        instructions="""['Stand with your feet slightly wider than shoulder width apart and toes pointing out slightly.', 'Squat down and grasp bar with a closed, pronated grip. Your hands should be slightly wider than shoulder width apart outside knees with elbows fully extended.', 'Place the bar about 1 inch in front of your shins and over the balls of your feet.', 'Your back should be flat or slightly arched, your chest held up and out and your shoulder blades should be retracted.', 'Keep your head in a neutral position (in line with vertebral column and not tilted or rotated) with your eyes focused straight ahead. Inhale during this phase.', 'Lift the bar from the floor by forcefully extending the hips and the knees as you exhale. Tip: The upper torso should maintain the same angle. Do not bend at the waist yet and do not let the hips rise before the shoulders (this would have the effect of pushing the glutes in the air and stretching the hamstrings.', 'Keep elbows fully extended with the head in a neutral position and the shoulders over the bar.', 'As the bar raises keep it as close to the shins as possible.', 'As the bar passes the knees, thrust your hips forward and slightly bend the knees to avoid locking them. Tip: At this point your thighs should be against the bar.', 'Keep the back flat or slightly arched, elbows fully extended and your head neutral. Tip: You will hold your breath until the next phase.', 'Inhale and then forcefully and quickly extend your hips and knees and stand on your toes.', 'Keep the bar as close to your body as possible. Tip: Your back should be flat with the elbows pointed out to the sides and your head in a neutral position. Also, keep your shoulders over the bar and arms straight as long as possible.', 'When your lower body joints are fully extended, shrug the shoulders upward rapidly without letting the elbows flex yet. Exhale during this portion of the movement.', 'As the shoulders reach their highest elevation flex your elbows to transition under the bar.']""",
        images=['Power_Clean/0.jpg', 'Power_Clean/1.jpg'],
    ),
    "Leg-Up_Hamstring_Stretch": ExerciseDefinition(
        id="Leg-Up_Hamstring_Stretch",
        display_name="Leg-Up Hamstring Stretch",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        instructions="""['Lie flat on your back, bend one knee, and put that foot flat on the floor to stabilize your spine.', "Extend the other leg in the air. If you're tight, you wont be able to straighten it. That's okay. Extend the knee so that the sole of the lifted foot faces the ceiling (or as close as you can get it).", 'Slowly straighten the legs as much as possible and then pull the leg toward your nose. Switch sides.']""",
        images=['Leg-Up_Hamstring_Stretch/0.jpg', 'Leg-Up_Hamstring_Stretch/1.jpg'],
    ),
    "Good_Morning": ExerciseDefinition(
        id="Good_Morning",
        display_name="Good Morning",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.POWERLIFTING,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.ABS, MuscleGroup.GLUTES, MuscleGroup.LOWER_BACK],
        instructions="""['Begin with a bar on a rack at shoulder height. Rack the bar across the rear of your shoulders as you would a power squat, not on top of your shoulders. Keep your back tight, shoulder blades pinched together, and your knees slightly bent. Step back from the rack.', 'Begin by bending at the hips, moving them back as you bend over to near parallel. Keep your back arched and your cervical spine in proper alignment.', 'Reverse the motion by extending through the hips with your glutes and hamstrings. Continue until you have returned to the starting position.']""",
        images=['Good_Morning/0.jpg', 'Good_Morning/1.jpg'],
    ),
    "Seated_Band_Hamstring_Curl": ExerciseDefinition(
        id="Seated_Band_Hamstring_Curl",
        display_name="Seated Band Hamstring Curl",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.OTHER,
        instructions="""['Secure a band close to the ground and place a bench a couple feet away from it.', 'Seat yourself on the bench and secure the band behind your ankles, beginning with your legs straight. This will be your starting position.', 'Flex the knees, bringing your feet towards the bench. You may need to lean back slightly to keep your feet from striking the floor.', 'Pause at the completion of the movement, and then slowly return to the starting position.']""",
        images=['Seated_Band_Hamstring_Curl/0.jpg', 'Seated_Band_Hamstring_Curl/1.jpg'],
    ),
    "Intermediate_Groin_Stretch": ExerciseDefinition(
        id="Intermediate_Groin_Stretch",
        display_name="Intermediate Groin Stretch",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.STATIC,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.OTHER,
        instructions="""['Lie on your back with your legs extended. Loop a belt, rope, or band around one of your feet, and swing that leg as far to the side as you can. This will be your starting position.', 'Pull gently on the belt to create tension in your groin and hamstring muscles. Hold for 10-20 seconds, and repeat on the other side.']""",
        images=['Intermediate_Groin_Stretch/0.jpg', 'Intermediate_Groin_Stretch/1.jpg'],
    ),
    "Lying_Hamstring": ExerciseDefinition(
        id="Lying_Hamstring",
        display_name="Lying Hamstring",
        level=LevelType.EXPERT,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.STATIC,
        equipment_type=EquipmentType.OTHER,
        secondary_muscles=[MuscleGroup.CALVES],
        instructions="""['Lie on your back with your legs extended. Your partner should be kneeling beside you. Raise one leg up towards the ceiling and have your partner hold the ankle. Your partner can use their shoulder to brace your leg if necessary. This will be your starting position.', 'With your partner holding your leg in place, attempt to flex the knee, contracting the hamstrings for 10-20 seconds.', 'Then relax your leg, allowing your partner to gently push the leg towards your head. Be sure to inform your helper when the stretch is adequate to prevent injury or overstretching. Switch sides once complete.']""",
        images=['Lying_Hamstring/0.jpg', 'Lying_Hamstring/1.jpg'],
    ),
    "Snatch_Deadlift": ExerciseDefinition(
        id="Snatch_Deadlift",
        display_name="Snatch Deadlift",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.OLYMPIC_WEIGHTLIFTING,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.FOREARMS, MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS, MuscleGroup.LOWER_BACK, MuscleGroup.QUADS, MuscleGroup.TRAPS],
        instructions="""['The snatch deadlift strengthens the first pull of the snatch. Begin with a wide snatch grip with the barbell placed on the platform. The feet should be directly under the hips, with the feet turned out. Squat down to the bar, keeping the back in absolute extension with the head facing forward.', 'Initiate the movement by driving through the heels, raising the hips. The back angle should remain the same until the bar passes the knees.', 'At that point, drive your hips through the bar as you lay back. Return the bar to the platform by reversing the motion.']""",
        images=['Snatch_Deadlift/0.jpg', 'Snatch_Deadlift/1.jpg'],
    ),
    "Reverse_Hyperextension": ExerciseDefinition(
        id="Reverse_Hyperextension",
        display_name="Reverse Hyperextension",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        equipment_type=EquipmentType.MACHINE,
        secondary_muscles=[MuscleGroup.CALVES, MuscleGroup.GLUTES],
        instructions="""['Place your feet between the pads after loading an appropriate weight. Lay on the top pad, allowing your hips to hang off the back, while grasping the handles to hold your position.', 'To begin the movement, flex the hips, pulling the legs forward.', 'Reverse the motion by extending the hips, kicking the leg back. It is very important not to over-extend the hip on this movement, stopping short of your full range of motion.', 'Return by again flexing the hip, pulling the carriage forward as far as you can.', 'Repeat for the desired number of repetitions.']""",
        images=['Reverse_Hyperextension/0.jpg', 'Reverse_Hyperextension/1.jpg'],
    ),
    "Seated_Hamstring_and_Calf_Stretch": ExerciseDefinition(
        id="Seated_Hamstring_and_Calf_Stretch",
        display_name="Seated Hamstring and Calf Stretch",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.STATIC,
        equipment_type=EquipmentType.OTHER,
        secondary_muscles=[MuscleGroup.CALVES],
        instructions="""['Loop a belt, rope, or band around one foot. Sit down with both legs extended . This will be your starting position.', 'Leaning forward slightly, pull on the belt to draw the toes of your foot back. Hold this position for 10-20 seconds and then repeat with the other leg.']""",
        images=['Seated_Hamstring_and_Calf_Stretch/0.jpg', 'Seated_Hamstring_and_Calf_Stretch/1.jpg'],
    ),
    "Power_Clean_from_Blocks": ExerciseDefinition(
        id="Power_Clean_from_Blocks",
        display_name="Power Clean from Blocks",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.OLYMPIC_WEIGHTLIFTING,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.QUADS],
        instructions="""['With a barbell on boxes of the desired height, take a grip just outside the legs. Lower your hips with the weight focused on the heels, back straight, head facing forward, chest up, with your shoulders just in front of the bar. This will be your starting position.', 'Begin the first pull by driving through the heels, extending your knees. Your back angle should stay the same, and your arms should remain straight. As the bar approaches the mid-thigh position, begin extending through the hips.', 'In a jumping motion, accelerate by extending the hips, knees, and ankles, using speed to move the bar upward. There should be no need to actively pull through the arms to accelerate the weight. At the end of the second pull, the body should be fully extended, leaning slightly back, with the arms still extended.', 'As full extension is achieved, transition into the third pull by aggressively shrugging and flexing the arms with the elbows up and out. At peak extension, pull yourself under the bar far enough that it can be racked onto the shoulders, rotating your elbows under the bar as you do so. The bar should be racked onto the protracted shoulders, lightly touching the throat with the hands relaxed.', 'Immediately recover by driving through the heels, keeping the torso upright and elbows up. Continue until you have risen to a standing position, and complete the repetition by returning the weight to the boxes.']""",
        images=['Power_Clean_from_Blocks/0.jpg', 'Power_Clean_from_Blocks/1.jpg'],
    ),
    "Platform_Hamstring_Slides": ExerciseDefinition(
        id="Platform_Hamstring_Slides",
        display_name="Platform Hamstring Slides",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.OTHER,
        secondary_muscles=[MuscleGroup.GLUTES],
        instructions="""['For this movement a wooden floor or similar is needed. Lay on your back with your legs extended. Place a gym towel or a light weight underneath your heel. This will be your starting position.', 'Begin the movement by flexing the knee, keeping your other leg straight.', 'Continue bringing the heel closer to you, sliding it on the floor.', 'At full knee flexion, reverse the movement to return to the starting position.']""",
        images=['Platform_Hamstring_Slides/0.jpg', 'Platform_Hamstring_Slides/1.jpg'],
    ),
    "Knee_Tuck_Jump": ExerciseDefinition(
        id="Knee_Tuck_Jump",
        display_name="Knee Tuck Jump",
        level=LevelType.BEGINNER,
        category=CategoryType.PLYOMETRICS,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.ABDUCTORS, MuscleGroup.ADDUCTORS, MuscleGroup.CALVES, MuscleGroup.GLUTES, MuscleGroup.QUADS],
        instructions="""['Begin in a comfortable standing position with your knees slightly bent. Hold your hands in front of you, palms down with your fingertips together at chest height. This will be your starting position.', 'Rapidly dip down into a quarter squat and immediately explode upward. Drive the knees towards the chest, attempting to touch them to the palms of the hands.', 'Jump as high as you can, raising your knees up, and then ensure a good land be re-extending your legs, absorbing impact through be allowing the knees to rebend.']""",
        images=['Knee_Tuck_Jump/0.jpg', 'Knee_Tuck_Jump/1.jpg'],
    ),
    "Worlds_Greatest_Stretch": ExerciseDefinition(
        id="Worlds_Greatest_Stretch",
        display_name="World's Greatest Stretch",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.STATIC,
        secondary_muscles=[MuscleGroup.CALVES, MuscleGroup.GLUTES, MuscleGroup.QUADS],
        instructions="""['This is a three-part stretch. Begin by lunging forward, with your front foot flat on the ground and on the toes of your back foot. With your knees bent, squat down until your knee is almost touching the ground. Keep your torso erect, and hold this position for 10-20 seconds.', 'Now, place the arm on the same side as your front leg on the ground, with the elbow next to the foot. Your other hand should be placed on the ground, parallel to your lead leg, to help support you during this portion of the stretch.', 'After 10-20 seconds, place your hands on either side of your front foot. Raise the toes of the front foot off of the ground, and straighten your leg. You may need to reposition your rear leg to do so. Hold for 10-20 seconds, and then repeat the entire sequence for the other side.']""",
        images=['Worlds_Greatest_Stretch/0.jpg', 'Worlds_Greatest_Stretch/1.jpg'],
    ),
    "Ball_Leg_Curl": ExerciseDefinition(
        id="Ball_Leg_Curl",
        display_name="Ball Leg Curl",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        secondary_muscles=[MuscleGroup.CALVES, MuscleGroup.GLUTES],
        instructions="""['Begin on the floor laying on your back with your feet on top of the ball.', 'Position the ball so that when your legs are extended your ankles are on top of the ball. This will be your starting position.', 'Raise your hips off of the ground, keeping your weight on the shoulder blades and your feet.', 'Flex the knees, pulling the ball as close to you as you can, contracting the hamstrings.', 'After a brief pause, return to the starting position.']""",
        images=['Ball_Leg_Curl/0.jpg', 'Ball_Leg_Curl/1.jpg'],
    ),
    "Romanian_Deadlift": ExerciseDefinition(
        id="Romanian_Deadlift",
        display_name="Romanian Deadlift",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.CALVES, MuscleGroup.GLUTES, MuscleGroup.LOWER_BACK],
        instructions="""['Put a barbell in front of you on the ground and grab it using a pronated (palms facing down) grip that a little wider than shoulder width. Tip: Depending on the weight used, you may need wrist wraps to perform the exercise and also a raised platform in order to allow for better range of motion.', 'Bend the knees slightly and keep the shins vertical, hips back and back straight. This will be your starting position.', 'Keeping your back and arms completely straight at all times, use your hips to lift the bar as you exhale. Tip: The movement should not be fast but steady and under control.', 'Once you are standing completely straight up, lower the bar by pushing the hips back, only slightly bending the knees, unlike when squatting. Tip: Take a deep breath at the start of the movement and keep your chest up. Hold your breath as you lower and exhale as you complete the movement.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Romanian_Deadlift/0.jpg', 'Romanian_Deadlift/1.jpg'],
    ),
    "Stiff-Legged_Dumbbell_Deadlift": ExerciseDefinition(
        id="Stiff-Legged_Dumbbell_Deadlift",
        display_name="Stiff-Legged Dumbbell Deadlift",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.DUMBBELL,
        secondary_muscles=[MuscleGroup.GLUTES, MuscleGroup.LOWER_BACK],
        instructions="""["Grasp a couple of dumbbells holding them by your side at arm's length.", 'Stand with your torso straight and your legs spaced using a shoulder width or narrower stance. The knees should be slightly bent. This is your starting position.', 'Keeping the knees stationary, lower the dumbbells to over the top of your feet by bending at the waist while keeping your back straight. Keep moving forward as if you were going to pick something from the floor until you feel a stretch on the hamstrings. Exhale as you perform this movement', 'Start bringing your torso up straight again by extending your hips and waist until you are back at the starting position. Inhale as you perform this movement.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Stiff-Legged_Dumbbell_Deadlift/0.jpg', 'Stiff-Legged_Dumbbell_Deadlift/1.jpg'],
    ),
    "Smith_Machine_Hang_Power_Clean": ExerciseDefinition(
        id="Smith_Machine_Hang_Power_Clean",
        display_name="Smith Machine Hang Power Clean",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.MACHINE,
        secondary_muscles=[MuscleGroup.GLUTES, MuscleGroup.LOWER_BACK, MuscleGroup.QUADS, MuscleGroup.SHOULDERS, MuscleGroup.TRAPS],
        instructions="""['Position the bar at knee height and load it to an appropriate weight.', 'Take a pronated grip on the bar outside of shoulder width and unhook the bar from the machine. Your arms should be fully extended with your head and chest up. Your elbows should be pointed out with your shoulders back and down. Your hips should be back, loading the tension into the hamstrings. This will be your starting position.', 'Initate the movement by forcefully extending the hips and knees, accelerating into the bar. Ensure that you keep your arms straight during this part of the motion.', 'Upon full extension, rebend the hips and knees to lower your receiving position.', 'Allow the arms to flex at this point, rotating the elbows around the bar to receive it on your shoulders.', 'Extend through the hips and knees to come to a standing position with the bar racked on your shoulders to complete the movement.']""",
        images=['Smith_Machine_Hang_Power_Clean/0.jpg', 'Smith_Machine_Hang_Power_Clean/1.jpg'],
    ),
    "Snatch_Pull": ExerciseDefinition(
        id="Snatch_Pull",
        display_name="Snatch Pull",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.CALVES, MuscleGroup.GLUTES, MuscleGroup.LOWER_BACK, MuscleGroup.QUADS, MuscleGroup.TRAPS],
        instructions="""['With a barbell on the floor close to the shins, take a wide snatch grip. Lower your hips with the weight focused on the heels, back straight, head facing forward, chest up, with your shoulders just in front of the bar. This will be your starting position.', 'Begin the first pull by driving through the heels, extending your knees. Your back angle should stay the same, and your arms should remain straight. Move the weight with control as you continue to above the knees.', 'Next comes the second pull, the main source of acceleration for the pull. As the bar approaches the mid-thigh position, begin extending through the hips. In a jumping motion, accelerate by extending the hips, knees, and ankles, using speed to move the bar upward.', 'There should be no need to actively pull through the arms to accelerate the weight; at the end of the second pull, the body should be fully extended, leaning slightly back. Full extension should be violent and abrupt, and ensure that you do not prolong the extension for longer than necessary.']""",
        images=['Snatch_Pull/0.jpg', 'Snatch_Pull/1.jpg'],
    ),
    "One-Arm_Kettlebell_Swings": ExerciseDefinition(
        id="One-Arm_Kettlebell_Swings",
        display_name="One-Arm Kettlebell Swings",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.CALVES, MuscleGroup.GLUTES, MuscleGroup.LOWER_BACK, MuscleGroup.SHOULDERS],
        instructions="""['Begin with a kettlebell on the ground. Position your feet in a wide stance, and grasp the kettlebell with one hand.', 'Swing the kettlebell between your legs, flexing at the hips and bending the knees slightly.', 'Powerfully reverse the motion by extending at the hips, knees, and ankles to propel yourself upward, swinging the kettlebell to shoulder height.']""",
        images=['One-Arm_Kettlebell_Swings/0.jpg', 'One-Arm_Kettlebell_Swings/1.jpg'],
    ),
    "Clean_Deadlift": ExerciseDefinition(
        id="Clean_Deadlift",
        display_name="Clean Deadlift",
        level=LevelType.BEGINNER,
        category=CategoryType.OLYMPIC_WEIGHTLIFTING,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.FOREARMS, MuscleGroup.GLUTES, MuscleGroup.LOWER_BACK, MuscleGroup.QUADS, MuscleGroup.TRAPS],
        instructions="""['Begin standing with a barbell close to your shins. Your feet should be directly under your hips with your feet turned out slightly. Grip the bar with a double overhand grip or hook grip, about shoulder width apart. Squat down to the bar. Your spine should be in full extension, with a back angle that places your shoulders in front of the bar and your back as vertical as possible.', "Begin by driving through the floor through the front of your heels. As the bar travels upward, maintain a constant back angle. Flare your knees out to the side to help keep them out of the bar's path.", 'After the bar crosses the knees, complete the lift by driving the hips into the bar until your hips and knees are extended.']""",
        images=['Clean_Deadlift/0.jpg', 'Clean_Deadlift/1.jpg'],
    ),
    "Band_Good_Morning": ExerciseDefinition(
        id="Band_Good_Morning",
        display_name="Band Good Morning",
        level=LevelType.BEGINNER,
        category=CategoryType.POWERLIFTING,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.GLUTES, MuscleGroup.LOWER_BACK],
        instructions="""['Using a 41 inch band, stand on one end, spreading your feet a small amount. Bend at the hips to loop the end of the band behind your neck. This will be your starting position.', 'Keeping your legs straight, extend through the hips to come to a near vertical position.', 'Ensure that you do not round your back as you go down back to the starting position.']""",
        images=['Band_Good_Morning/0.jpg', 'Band_Good_Morning/1.jpg'],
    ),
    "Floor_Glute-Ham_Raise": ExerciseDefinition(
        id="Floor_Glute-Ham_Raise",
        display_name="Floor Glute-Ham Raise",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        secondary_muscles=[MuscleGroup.CALVES, MuscleGroup.GLUTES],
        instructions="""['You can use a partner for this exercise or brace your feet under something stable.', 'Begin on your knees with your upper legs and torso upright. If using a partner, they will firmly hold your feet to keep you in position. This will be your starting position.', 'Lower yourself by extending at the knee, taking care to NOT flex the hips as you go forward.', 'Place your hands in front of you as you reach the floor. This movement is very difficult and you may be unable to do it unaided. Use your arms to lightly push off the floor to aid your return to the starting position.']""",
        images=['Floor_Glute-Ham_Raise/0.jpg', 'Floor_Glute-Ham_Raise/1.jpg'],
    ),
    "Double_Kettlebell_Alternating_Hang_Clean": ExerciseDefinition(
        id="Double_Kettlebell_Alternating_Hang_Clean",
        display_name="Double Kettlebell Alternating Hang Clean",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.BICEPS, MuscleGroup.CALVES, MuscleGroup.FOREARMS, MuscleGroup.GLUTES, MuscleGroup.LOWER_BACK, MuscleGroup.QUADS, MuscleGroup.TRAPS],
        instructions="""['Place two kettlebells between your feet. To get in the starting position, push your butt back and look straight ahead.', 'Clean one kettlebell to your shoulder and hold on to the other kettlebell.', 'With a fluid motion, lower the top kettlebell while driving the bottom kettlebell up.']""",
        images=['Double_Kettlebell_Alternating_Hang_Clean/0.jpg', 'Double_Kettlebell_Alternating_Hang_Clean/1.jpg'],
    ),
    "Kettlebell_Hang_Clean": ExerciseDefinition(
        id="Kettlebell_Hang_Clean",
        display_name="Kettlebell Hang Clean",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.CALVES, MuscleGroup.GLUTES, MuscleGroup.LOWER_BACK, MuscleGroup.SHOULDERS, MuscleGroup.TRAPS],
        instructions="""['Place kettlebell between your feet. To get in the starting position, push your butt back and look straight ahead.', 'Clean kettlebell to your shoulder. Clean the kettlebell to your shoulders by extending through the legs and hips as you raise the kettlebell towards your shoulder. The wrist should rotate as you do so.', 'Lower kettlebell to a hanging position between your legs while keeping the hamstrings loaded. Keep your head up at all times.']""",
        images=['Kettlebell_Hang_Clean/0.jpg', 'Kettlebell_Hang_Clean/1.jpg'],
    ),
    "Seated_Floor_Hamstring_Stretch": ExerciseDefinition(
        id="Seated_Floor_Hamstring_Stretch",
        display_name="Seated Floor Hamstring Stretch",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.STATIC,
        secondary_muscles=[MuscleGroup.CALVES],
        instructions="""['Sit on a mat with your right leg extended in front of you and your left leg bent with your foot against your right inner thigh.', 'Lean forward from your hips and reach for your ankle until you feel a stretch in your hamstring. Hold for 15 seconds, then repeat for your other side.']""",
        images=['Seated_Floor_Hamstring_Stretch/0.jpg', 'Seated_Floor_Hamstring_Stretch/1.jpg'],
    ),
    "Seated_Hamstring": ExerciseDefinition(
        id="Seated_Hamstring",
        display_name="Seated Hamstring",
        level=LevelType.EXPERT,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.STATIC,
        secondary_muscles=[MuscleGroup.CALVES],
        instructions="""['In a seated position with your legs extended, have your partner stand behind you. Now, lean forward as your partner braces your shoulders with their hands. This will be your starting position.', 'Attempt to push your torso back for 10-20 seconds, as your partner prevents any actual movement of your torso.', 'Now relax your muscles as your partner increases the stretch by gently pushing your torso forward for 10-20 seconds.']""",
        images=['Seated_Hamstring/0.jpg', 'Seated_Hamstring/1.jpg'],
    ),
    "Split_Snatch": ExerciseDefinition(
        id="Split_Snatch",
        display_name="Split Snatch",
        level=LevelType.EXPERT,
        category=CategoryType.OLYMPIC_WEIGHTLIFTING,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.CALVES, MuscleGroup.FOREARMS, MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS, MuscleGroup.LOWER_BACK, MuscleGroup.QUADS, MuscleGroup.SHOULDERS, MuscleGroup.TRAPS, MuscleGroup.TRICEPS],
        instructions="""['Begin with a loaded barbell on the floor. The bar should be close to or touching the shins, and a wide grip should be taken on the bar. The feet should be directly below the hips, with the feet turned out as needed. Lower the hips, with the chest up and the head looking forward. The shoulders should be just in front of the bar. This will be your starting position.', 'Begin the first pull by driving through the front of the heels, raising the bar from the ground. The back angle should stay the same until the bar passes the knees.', 'Transition into the second pull by extending through the hips knees and ankles, driving the bar up as quickly as possible. The bar should be close to the body. At peak extension, shrug the shoulders and allow the elbows to flex to the side.', 'As you move your feet into the receiving position, forcefully pull yourself below the bar as you elevate the bar overhead. The feet should move forcefully to a split position, one foot forward one foot back. Receive the bar with your body as low as possible and the arms fully extended overhead.', 'Keeping the bar aligned over the front of the heels, your head and chest up, drive through heels of the feet to move to a standing position, bringing your feet together.', 'Carefully return the weight to floor.']""",
        images=['Split_Snatch/0.jpg', 'Split_Snatch/1.jpg'],
    ),
    "Moving_Claw_Series": ExerciseDefinition(
        id="Moving_Claw_Series",
        display_name="Moving Claw Series",
        level=LevelType.BEGINNER,
        category=CategoryType.PLYOMETRICS,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.CALVES, MuscleGroup.QUADS],
        instructions="""['This move helps prepare your running form to help you excel at sprinting. As you run, be sure to flex the knee, aiming to kick your glutes as the hip extends.', 'Reload the quad as the leg moves back forward, attacking the ground on the next step.', 'Ensure that as you run, you block with the arms, punching through in a rapid 1-2 motion.']""",
        images=['Moving_Claw_Series/0.jpg', 'Moving_Claw_Series/1.jpg'],
    ),
    "Chair_Leg_Extended_Stretch": ExerciseDefinition(
        id="Chair_Leg_Extended_Stretch",
        display_name="Chair Leg Extended Stretch",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.STATIC,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.OTHER,
        secondary_muscles=[MuscleGroup.ADDUCTORS],
        instructions="""['Sit upright in a chair and grip the seat on the sides.', 'Raise one leg, extending the knee, flexing the ankle as you do so.', 'Slowly move that leg outward as far as you can, and then back to the center and down.', 'Repeat for your other leg.']""",
        images=['Chair_Leg_Extended_Stretch/0.jpg', 'Chair_Leg_Extended_Stretch/1.jpg'],
    ),
    "Hang_Snatch": ExerciseDefinition(
        id="Hang_Snatch",
        display_name="Hang Snatch",
        level=LevelType.EXPERT,
        category=CategoryType.OLYMPIC_WEIGHTLIFTING,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.ABS, MuscleGroup.CALVES, MuscleGroup.FOREARMS, MuscleGroup.GLUTES, MuscleGroup.LOWER_BACK, MuscleGroup.QUADS, MuscleGroup.SHOULDERS, MuscleGroup.TRAPS],
        instructions="""['Begin with a wide grip on the bar, with an overhand or hook grip. The feet should be directly below the hips with the feet turned out. Your knees should be slightly bent, and the torso inclined forward. The spine should be fully extended and the head facing forward. The bar should be at the hips. This will be your starting position.', 'Aggressively extend through the legs and hips. At peak extension, shrug the shoulders and allow the elbows to flex to the side.', 'As you move your feet into the receiving position, forcefully pull yourself below the bar as you elevate the bar overhead. Receive the bar with your body as low as possible and the arms fully extended overhead.', 'Return to a standing position with the weight overhead. Follow by returning the weight to the ground under control.']""",
        images=['Hang_Snatch/0.jpg', 'Hang_Snatch/1.jpg'],
    ),
    "Stiff-Legged_Barbell_Deadlift": ExerciseDefinition(
        id="Stiff-Legged_Barbell_Deadlift",
        display_name="Stiff-Legged Barbell Deadlift",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.GLUTES, MuscleGroup.LOWER_BACK],
        instructions="""['Grasp a bar using an overhand grip (palms facing down). You may need some wrist wraps if using a significant amount of weight.', 'Stand with your torso straight and your legs spaced using a shoulder width or narrower stance. The knees should be slightly bent. This is your starting position.', 'Keeping the knees stationary, lower the barbell to over the top of your feet by bending at the hips while keeping your back straight. Keep moving forward as if you were going to pick something from the floor until you feel a stretch on the hamstrings. Inhale as you perform this movement.', 'Start bringing your torso up straight again by extending your hips until you are back at the starting position. Exhale as you perform this movement.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Stiff-Legged_Barbell_Deadlift/0.jpg', 'Stiff-Legged_Barbell_Deadlift/1.jpg'],
    ),
    "Reverse_Band_Sumo_Deadlift": ExerciseDefinition(
        id="Reverse_Band_Sumo_Deadlift",
        display_name="Reverse Band Sumo Deadlift",
        level=LevelType.EXPERT,
        category=CategoryType.POWERLIFTING,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.ABDUCTORS, MuscleGroup.ADDUCTORS, MuscleGroup.CALVES, MuscleGroup.FOREARMS, MuscleGroup.GLUTES, MuscleGroup.LOWER_BACK, MuscleGroup.QUADS, MuscleGroup.TRAPS],
        instructions="""['Begin with a bar loaded on the floor inside of a power rack. Attach bands to the top of the rack, using either pegs or the frame itself. Attach the other end to the barbell.', 'Approach the bar so that the bar intersects the middle of the feet. The feet should be set very wide, near the collars. Bend at the hips to grip the bar. The arms should be directly below the shoulders, inside the legs, and you can use a pronated grip, a mixed grip, or hook grip. Relax the shoulders, which in effect lengthens your arms.', 'Take a breath, and then lower your hips, looking forward with your head with your chest up. Drive through the floor, spreading your feet apart, with your weight on the back half of your feet. Extend through the hips and knees.', 'As the bar passes through the knees, lean back and drive the hips into the bar, pulling your shoulder blades together.', 'Return the weight to the ground by bending at the hips and controlling the weight on the way down.']""",
        images=['Reverse_Band_Sumo_Deadlift/0.jpg', 'Reverse_Band_Sumo_Deadlift/1.jpg'],
    ),
    "Dumbbell_Clean": ExerciseDefinition(
        id="Dumbbell_Clean",
        display_name="Dumbbell Clean",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.DUMBBELL,
        secondary_muscles=[MuscleGroup.CALVES, MuscleGroup.FOREARMS, MuscleGroup.GLUTES, MuscleGroup.LOWER_BACK, MuscleGroup.QUADS, MuscleGroup.SHOULDERS, MuscleGroup.TRAPS],
        instructions="""['Begin standing with a dumbbell in each hand with your feet shoulder width apart.', 'Lower the weights to the floor by flexing at the hips and knees, pushing your hips back until the dumbbells reach the floor. This will be your starting position.', 'To initiate the movement, violently jump upward by extending the hips, knees, and ankles to acclerate the weights upward. Maintaining a neutral grip on the dumbbells, keep the arms straight until full extension is reached.', 'After full extension, rebend the hips and knees to receive the weight in a squat position. Allow the arms to bend, guiding the dumbbells to your shoulders.', 'Upon receiving the weight in the squat position, extend the hips and knees to finish in a standing position with the weights on your shoulders.']""",
        images=['Dumbbell_Clean/0.jpg', 'Dumbbell_Clean/1.jpg'],
    ),
    "One-Arm_Open_Palm_Kettlebell_Clean": ExerciseDefinition(
        id="One-Arm_Open_Palm_Kettlebell_Clean",
        display_name="One-Arm Open Palm Kettlebell Clean",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.FOREARMS, MuscleGroup.GLUTES, MuscleGroup.LOWER_BACK, MuscleGroup.QUADS, MuscleGroup.SHOULDERS],
        instructions="""['Place one kettlebell between your feet.', 'Grab the handle with one hand and raise the kettlebell rapidly, let it flip so that the ball of the kettlebell lands in the palm of your hand.', 'Throw the kettlebell out in front of you and catch the handle with one hand.', 'Take the kettlebell to the floor and repeat. Make sure to work both arms.']""",
        images=['One-Arm_Open_Palm_Kettlebell_Clean/0.jpg', 'One-Arm_Open_Palm_Kettlebell_Clean/1.jpg'],
    ),
    "Hanging_Bar_Good_Morning": ExerciseDefinition(
        id="Hanging_Bar_Good_Morning",
        display_name="Hanging Bar Good Morning",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.POWERLIFTING,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.ABS, MuscleGroup.GLUTES, MuscleGroup.LOWER_BACK],
        instructions="""['Begin with a bar on a rack at about the same height as your stomach. Suspend the bar using chains or suspension straps.', 'Bend over underneath the bar and rack the bar across the rear of your shoulders as you would a power squat, not on top of your traps. At the proper height, you should be near parallel to the floor when bent over. Keep your back tight, shoulder blades pinched together, and your knees slightly bent. Keep your back arched and your cervical spine in proper alignment.', 'Begin the motion by extending through the hips with your glutes and hamstrings, and you are standing with the weight.', 'Slowly lower the weight back to the starting position, where it is supported by the chains.']""",
        images=['Hanging_Bar_Good_Morning/0.jpg', 'Hanging_Bar_Good_Morning/1.jpg'],
    ),
    "Hurdle_Hops": ExerciseDefinition(
        id="Hurdle_Hops",
        display_name="Hurdle Hops",
        level=LevelType.BEGINNER,
        category=CategoryType.PLYOMETRICS,
        muscle_group=MuscleGroup.HAMSTRINGS,
        major_muscle_group=MajorMuscleGroup.LEGS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.OTHER,
        secondary_muscles=[MuscleGroup.ABDUCTORS, MuscleGroup.ADDUCTORS, MuscleGroup.CALVES, MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS],
        instructions="""['Set up a row of hurdles or other small barriers, placing them a few feet apart.', 'Stand in front of the first hurdle with your feet shoulder width apart. This will be your starting position.', 'Begin by jumping with both feet over the first hurdle, swinging both arms as you jump.', 'Absorb the impact of landing by bending the knees, rebounding out of the first leap by jumping over the next hurdle. Continue until you have jumped over all of the hurdles.']""",
        images=['Hurdle_Hops/0.jpg', 'Hurdle_Hops/1.jpg'],
    ),
}
