from exercises.base import ExerciseDefinition
from enums import MuscleGroup, EquipmentType, MechanicsType, MajorMuscleGroup, ForceType, LevelType, CategoryType

LATS_EXERCISES = {
    "Overhead_Lat": ExerciseDefinition(
        id="Overhead_Lat",
        display_name="Overhead Lat",
        level=LevelType.EXPERT,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.STATIC,
        equipment_type=EquipmentType.OTHER,
        secondary_muscles=[MuscleGroup.TRICEPS],
        instructions="['Sit upright on the floor with your partner behind you. Raise one arm straight up, and flex the elbow, attempting to touch your hand to your back. Your parner should hold your tricep and wrist. This will be your starting position.', 'Attempt to pull your upper arm to your side as your partner prevents you from doing actually doing so.', 'After 10-20 seconds, relax the arm and allow your partner to further stretch the lat by applying gentle pressure to the tricep. Hold for 10-20 seconds, and then switch sides.']",
        images=['Overhead_Lat/0.jpg', 'Overhead_Lat/1.jpg'],
    ),
    "Side-Lying_Floor_Stretch": ExerciseDefinition(
        id="Side-Lying_Floor_Stretch",
        display_name="Side-Lying Floor Stretch",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.STATIC,
        instructions="['First lie on your left side, bending your left knee in front of you to stabilize your torso (use your abdominal muscles as well to hold you upright).', 'Straighten your right leg and rest the right foot on the floor behind your left. Straighten your right arm over your head and gently pull on your right wrist to stretch the entire right side of the body. Switch sides.']",
        images=['Side-Lying_Floor_Stretch/0.jpg', 'Side-Lying_Floor_Stretch/1.jpg'],
    ),
    "Wide-Grip_Pulldown_Behind_The_Neck": ExerciseDefinition(
        id="Wide-Grip_Pulldown_Behind_The_Neck",
        display_name="Wide-Grip Pulldown Behind The Neck",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.CABLE,
        secondary_muscles=[MuscleGroup.BICEPS, MuscleGroup.SHOULDERS],
        instructions="['Sit down on a pull-down machine with a wide bar attached to the top pulley. Make sure that you adjust the knee pad of the machine to fit your height. These pads will prevent your body from being raised by the resistance attached to the bar.', 'Grab the bar with the palms facing forward using the prescribed grip. Note on grips: For a wide grip, your hands need to be spaced out at a distance wider than your shoulder width. For a medium grip, your hands need to be spaced out at a distance equal to your shoulder width and for a close grip at a distance smaller than your shoulder width.', 'As you have both arms extended in front of you holding the bar at the chosen grip width, bring your torso and head forward. Think of an imaginary line from the center of the bar down to the back of your neck. This is your starting position.', 'As you breathe out, bring the bar down until it touches the back of your neck by drawing the shoulders and the upper arms down and back. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. The upper torso should remain stationary and only the arms should move. The forearms should do no other work except for holding the bar; therefore do not try to pull down the bar using the forearms.', 'After a second on the contracted position squeezing your shoulder blades together, slowly raise the bar back to the starting position when your arms are fully extended and the lats are fully stretched. Inhale during this portion of the movement.', 'Repeat this motion for the prescribed amount of repetitions.']",
        images=['Wide-Grip_Pulldown_Behind_The_Neck/0.jpg', 'Wide-Grip_Pulldown_Behind_The_Neck/1.jpg'],
    ),
    "Catch_and_Overhead_Throw": ExerciseDefinition(
        id="Catch_and_Overhead_Throw",
        display_name="Catch and Overhead Throw",
        level=LevelType.BEGINNER,
        category=CategoryType.PLYOMETRICS,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.MEDICINE_BALL,
        secondary_muscles=[MuscleGroup.ABS, MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
        instructions="['Begin standing while facing a wall or a partner.', 'Using both hands, position the ball behind your head, stretching as much as possible, and forcefully throw the ball forward.', 'Ensure that you follow your throw through, being prepared to receive your rebound from your throw. If you are throwing against the wall, make sure that you stand close enough to the wall to receive the rebound, and aim a little higher than you would with a partner.']",
        images=['Catch_and_Overhead_Throw/0.jpg', 'Catch_and_Overhead_Throw/1.jpg'],
    ),
    "Band_Assisted_Pull-Up": ExerciseDefinition(
        id="Band_Assisted_Pull-Up",
        display_name="Band Assisted Pull-Up",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.OTHER,
        secondary_muscles=[MuscleGroup.ABS, MuscleGroup.FOREARMS],
        instructions="""['Choke the band around the center of the pullup bar. You can use different bands to provide varying levels of assistance.', "Pull the end of the band down, and place one bent knee into the loop, ensuring it won't slip out. Take a medium to wide grip on the bar. This will be your starting position.", 'Pull yourself upward by contracting the lats as you flex the elbow. The elbow should be driven to your side. Pull to the front, attempting to get your chin over the bar. Avoid swinging or jerking movements.', 'After a brief pause, return to the starting position.']""",
        images=['Band_Assisted_Pull-Up/0.jpg', 'Band_Assisted_Pull-Up/1.jpg'],
    ),
    "Straight-Arm_Pulldown": ExerciseDefinition(
        id="Straight-Arm_Pulldown",
        display_name="Straight Arm Pulldown",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="['You will start by grabbing the wide bar from the top pulley of a pulldown machine and using a wider than shoulder-width pronated (palms down) grip. Step backwards two feet or so.', 'Bend your torso forward at the waist by around 30-degrees with your arms fully extended in front of you and a slight bend at the elbows. If your arms are not fully extended then you need to step a bit more backwards until they are. Once your arms are fully extended and your torso is slightly bent at the waist, tighten the lats and then you are ready to begin.', 'While keeping the arms straight, pull the bar down by contracting the lats until your hands are next to the side of the thighs. Breathe out as you perform this step.', 'While keeping the arms straight, go back to the starting position while breathing in.', 'Repeat for the recommended amount of repetitions.']",
        images=['Straight-Arm_Pulldown/0.jpg', 'Straight-Arm_Pulldown/1.jpg'],
    ),
    "Shotgun_Row": ExerciseDefinition(
        id="Shotgun_Row",
        display_name="Shotgun Row",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.CABLE,
        secondary_muscles=[MuscleGroup.BICEPS],
        instructions="['Attach a single handle to a low cable.', 'After selecting the correct weight, stand a couple feet back with a wide-split stance. Your arm should be extended and your shoulder forward. This will be your starting position.', 'Perform the movement by retracting the shoulder and flexing the elbow. As you pull, supinate the wrist, turning the palm upward as you go.', 'After a brief pause, return to the starting position.']",
        images=['Shotgun_Row/0.jpg', 'Shotgun_Row/1.jpg'],
    ),
    "Kneeling_Single-Arm_High_Pulley_Row": ExerciseDefinition(
        id="Kneeling_Single-Arm_High_Pulley_Row",
        display_name="Kneeling Single-Arm High Pulley Row",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.CABLE,
        secondary_muscles=[MuscleGroup.BICEPS],
        instructions="['Attach a single handle to a high pulley and make your weight selection.', 'Kneel in front of the cable tower, taking the cable with one hand with your arm extended. This will be your starting position.', 'Starting with your palm facing forward, pull the weight down to your torso by flexing the elbow and retract the shoulder blade. As you do so, rotate the wrist so that at the completion of the movement, your palm is now facing you.', 'After a brief pause, return to the starting position.']",
        images=['Kneeling_Single-Arm_High_Pulley_Row/0.jpg', 'Kneeling_Single-Arm_High_Pulley_Row/1.jpg'],
    ),
    "Side_To_Side_Chins": ExerciseDefinition(
        id="Side_To_Side_Chins",
        display_name="Side To Side Chins",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.OTHER,
        secondary_muscles=[MuscleGroup.BICEPS, MuscleGroup.FOREARMS, MuscleGroup.SHOULDERS],
        instructions="['Grab the pull-up bar with the palms facing forward using a wide grip.', 'As you have both arms extended in front of you holding the bar at a wide grip, bring your torso back around 30 degrees or so while creating a curvature on your lower back and sticking your chest out. This is your starting position.', 'Pull your torso up while leaning to the left hand side until the bar almost touches your upper chest by drawing the shoulders and the upper arms down and back. Exhale as you perform this portion of the movement. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. The upper torso should remain stationary as it moves through space (no swinging) and only the arms should move. The forearms should do no other work other than hold the bar.', 'After a second of contraction, inhale as you go back to the starting position.', 'Now, pull your torso up while leaning to the right hand side until the bar almost touches your upper chest by drawing the shoulders and the upper arms down and back. Exhale as you perform this portion of the movement. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. The upper torso should remain stationary as it moves through space and only the arms should move. The forearms should do no other work other than hold the bar.', 'After a second of contraction, inhale as you go back to the starting position.', 'Repeat steps 3-6 until you have performed the prescribed amount of repetitions for each side.']",
        images=['Side_To_Side_Chins/0.jpg', 'Side_To_Side_Chins/1.jpg'],
    ),
    "One_Handed_Hang": ExerciseDefinition(
        id="One_Handed_Hang",
        display_name="One Handed Hang",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.STATIC,
        equipment_type=EquipmentType.OTHER,
        secondary_muscles=[MuscleGroup.BICEPS],
        instructions="['Grab onto a chinup bar with one hand, using a pronated grip. Keep your feet on the floor or a step. Allow the majority of your weight to hang from that hand, while keeping your feet on the ground. Hold for 10-20 seconds and switch sides.']",
        images=['One_Handed_Hang/0.jpg', 'One_Handed_Hang/1.jpg'],
    ),
    "Gironda_Sternum_Chins": ExerciseDefinition(
        id="Gironda_Sternum_Chins",
        display_name="Gironda Sternum Chins",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.OTHER,
        secondary_muscles=[MuscleGroup.BICEPS],
        instructions="""['Grasp the pull-up bar with a shoulder width underhand grip.', 'Now hang with your arms fully extended and stick your chest out and lean back. Tip: You will be leaning back throughout the entire movement. This will be your starting position.', 'Start pulling yourself towards the bar with your spine arched throughout the movement and your head leaning back as far away from the bar as possible. Exhale as you perform this portion of the movement. Tip: At the upper end of the movement, your hips and legs will be at about a 45-degree angle to the floor.', "Keep pulling until your collarbone passes the bar and your lower chest or sternum area touches it. Hold that contraction for a second. Tip: By the time you've completed this portion of the movement; your head will be parallel to the floor.", 'Slowly start going back to the starting position as you inhale.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Gironda_Sternum_Chins/0.jpg', 'Gironda_Sternum_Chins/1.jpg'],
    ),
    "Close-Grip_Front_Lat_Pulldown": ExerciseDefinition(
        id="Close-Grip_Front_Lat_Pulldown",
        display_name="Close-Grip Front Lat Pulldown",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.CABLE,
        secondary_muscles=[MuscleGroup.BICEPS, MuscleGroup.SHOULDERS],
        instructions="['Sit down on a pull-down machine with a wide bar attached to the top pulley. Make sure that you adjust the knee pad of the machine to fit your height. These pads will prevent your body from being raised by the resistance attached to the bar.', 'Grab the bar with the palms facing forward using the prescribed grip. Note on grips: For a wide grip, your hands need to be spaced out at a distance wider than your shoulder width. For a medium grip, your hands need to be spaced out at a distance equal to your shoulder width and for a close grip at a distance smaller than your shoulder width.', 'As you have both arms extended in front of you - while holding the bar at the chosen grip width - bring your torso back around 30 degrees or so while creating a curvature on your lower back and sticking your chest out. This is your starting position.', 'As you breathe out, bring the bar down until it touches your upper chest by drawing the shoulders and the upper arms down and back. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. The upper torso should remain stationary (only the arms should move). The forearms should do no other work except for holding the bar; therefore do not try to pull the bar down using the forearms.', 'After a second in the contracted position, while squeezing your shoulder blades together, slowly raise the bar back to the starting position when your arms are fully extended and the lats are fully stretched. Inhale during this portion of the movement.', '6. Repeat this motion for the prescribed amount of repetitions.']",
        images=['Close-Grip_Front_Lat_Pulldown/0.jpg', 'Close-Grip_Front_Lat_Pulldown/1.jpg'],
    ),
    "Wide-Grip_Rear_Pull-Up": ExerciseDefinition(
        id="Wide-Grip_Rear_Pull-Up",
        display_name="Wide-Grip Rear Pull-Up",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.BICEPS, MuscleGroup.SHOULDERS],
        instructions="['Grab the pull-up bar with the palms facing forward using a wide grip.', 'As you have both arms extended in front of you holding the bar, bring your torso forward and head so that there is an imaginary line from the pull-up bar to the back of your neck. This is your starting position.', 'Pull your torso up until the bar is near the back of your neck. To do this, draw the shoulders and upper arms down and back while slightly leaning your head forward. Exhale as you perform this portion of the movement. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. The upper torso should remain stationary as it moves through space and only the arms should move. The forearms should do no other work other than hold the bar.', 'After a second on the contracted position, start to inhale and slowly lower your torso back to the starting position when your arms are fully extended and the lats are fully stretched.', 'Repeat this motion for the prescribed amount of repetitions.']",
        images=['Wide-Grip_Rear_Pull-Up/0.jpg', 'Wide-Grip_Rear_Pull-Up/1.jpg'],
    ),
    "Wide-Grip_Lat_Pulldown": ExerciseDefinition(
        id="Wide-Grip_Lat_Pulldown",
        display_name="Wide-Grip Lat Pulldown",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.CABLE,
        secondary_muscles=[MuscleGroup.BICEPS, MuscleGroup.SHOULDERS],
        instructions="['Sit down on a pull-down machine with a wide bar attached to the top pulley. Make sure that you adjust the knee pad of the machine to fit your height. These pads will prevent your body from being raised by the resistance attached to the bar.', 'Grab the bar with the palms facing forward using the prescribed grip. Note on grips: For a wide grip, your hands need to be spaced out at a distance wider than shoulder width. For a medium grip, your hands need to be spaced out at a distance equal to your shoulder width and for a close grip at a distance smaller than your shoulder width.', 'As you have both arms extended in front of you holding the bar at the chosen grip width, bring your torso back around 30 degrees or so while creating a curvature on your lower back and sticking your chest out. This is your starting position.', 'As you breathe out, bring the bar down until it touches your upper chest by drawing the shoulders and the upper arms down and back. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. The upper torso should remain stationary and only the arms should move. The forearms should do no other work except for holding the bar; therefore do not try to pull down the bar using the forearms.', 'After a second at the contracted position squeezing your shoulder blades together, slowly raise the bar back to the starting position when your arms are fully extended and the lats are fully stretched. Inhale during this portion of the movement.', 'Repeat this motion for the prescribed amount of repetitions.']",
        images=['Wide-Grip_Lat_Pulldown/0.jpg', 'Wide-Grip_Lat_Pulldown/1.jpg'],
    ),
    "Cable_Incline_Pushdown": ExerciseDefinition(
        id="Cable_Incline_Pushdown",
        display_name="Cable Incline Pushdown",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="['Lie on incline an bench facing away from a high pulley machine that has a straight bar attachment on it.', 'Grasp the straight bar attachment overhead with a pronated (overhand; palms down) shoulder width grip and extend your arms in front of you. The bar should be around 2 inches away from your upper thighs. This will be your starting position.', 'Keeping the upper arms stationary, lift your arms back in a semi circle until the bar is straight over your head. Breathe in during this portion of the movement.', 'Slowly go back to the starting position using your lats and hold the contraction once you reach the starting position. Breathe out during the execution of this movement.', 'Repeat for the recommended amount of repetitions.']",
        images=['Cable_Incline_Pushdown/0.jpg', 'Cable_Incline_Pushdown/1.jpg'],
    ),
    "Latissimus_Dorsi-SMR": ExerciseDefinition(
        id="Latissimus_Dorsi-SMR",
        display_name="Latissimus Dorsi-SMR",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.STATIC,
        mechanics_type=MechanicsType.ISOLATION,
        instructions="['While lying on the floor, place a foam roll under your back and to one side, just behind your arm pit. This will be your starting position.', 'Keep the arm of the side being stretched behind and to the side of you as you shift your weight onto your lats, keeping your upper body off of the ground. Hold for 10-30 seconds, and switch sides.']",
        images=['Latissimus_Dorsi-SMR/0.jpg', 'Latissimus_Dorsi-SMR/1.jpg'],
    ),
    "Pullups": ExerciseDefinition(
        id="Pullups",
        display_name="Pullups",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.BICEPS],
        instructions="['Grab the pull-up bar with the palms facing forward using the prescribed grip. Note on grips: For a wide grip, your hands need to be spaced out at a distance wider than your shoulder width. For a medium grip, your hands need to be spaced out at a distance equal to your shoulder width and for a close grip at a distance smaller than your shoulder width.', 'As you have both arms extended in front of you holding the bar at the chosen grip width, bring your torso back around 30 degrees or so while creating a curvature on your lower back and sticking your chest out. This is your starting position.', 'Pull your torso up until the bar touches your upper chest by drawing the shoulders and the upper arms down and back. Exhale as you perform this portion of the movement. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. The upper torso should remain stationary as it moves through space and only the arms should move. The forearms should do no other work other than hold the bar.', 'After a second on the contracted position, start to inhale and slowly lower your torso back to the starting position when your arms are fully extended and the lats are fully stretched.', 'Repeat this motion for the prescribed amount of repetitions.']",
        images=['Pullups/0.jpg', 'Pullups/1.jpg'],
    ),
    "Rope_Climb": ExerciseDefinition(
        id="Rope_Climb",
        display_name="Rope Climb",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.OTHER,
        secondary_muscles=[MuscleGroup.BICEPS, MuscleGroup.FOREARMS, MuscleGroup.SHOULDERS],
        instructions="['Grab the rope with both hands above your head. Pull down on the rope as you take a small jump.', 'Wrap the rope around one leg, using your feet to pinch the rope. Reach up as high as possible with your arms, gripping the rope tightly.', 'Release the rope from your feet as you pull yourself up with your arms, bringing your knees towards your chest.', 'Resecure your feet on the rope, and then stand up to take another high hold on the rope. Continue until you reach the top of the rope.', 'To lower yourself, loosen the grip of your feet on the rope as you slide down using a hand over hand motion.']",
        images=['Rope_Climb/0.jpg', 'Rope_Climb/1.jpg'],
    ),
    "V-Bar_Pulldown": ExerciseDefinition(
        id="V-Bar_Pulldown",
        display_name="V-Bar Pulldown",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.CABLE,
        secondary_muscles=[MuscleGroup.BICEPS, MuscleGroup.SHOULDERS],
        instructions="['Sit down on a pull-down machine with a V-Bar attached to the top pulley.', 'Adjust the knee pad of the machine to fit your height. These pads will prevent your body from being raised by the resistance attached to the bar.', 'Grab the V-bar with the palms facing each other (a neutral grip). Stick your chest out and lean yourself back slightly (around 30-degrees) in order to better engage the lats. This will be your starting position.', 'Using your lats, pull the bar down as you squeeze your shoulder blades. Continue until your chest nearly touches the V-bar. Exhale as you execute this motion. Tip: Keep the torso stationary throughout the movement.', 'After a second hold on the contracted position, slowly bring the bar back to the starting position as you breathe in.', 'Repeat for the prescribed number of repetitions.']",
        images=['V-Bar_Pulldown/0.jpg', 'V-Bar_Pulldown/1.jpg'],
    ),
    "Chin-Up": ExerciseDefinition(
        id="Chin-Up",
        display_name="Chin-Up",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.BICEPS, MuscleGroup.FOREARMS],
        instructions="['Grab the pull-up bar with the palms facing your torso and a grip closer than the shoulder width.', 'As you have both arms extended in front of you holding the bar at the chosen grip width, keep your torso as straight as possible while creating a curvature on your lower back and sticking your chest out. This is your starting position. Tip: Keeping the torso as straight as possible maximizes biceps stimulation while minimizing back involvement.', 'As you breathe out, pull your torso up until your head is around the level of the pull-up bar. Concentrate on using the biceps muscles in order to perform the movement. Keep the elbows close to your body. Tip: The upper torso should remain stationary as it moves through space and only the arms should move. The forearms should do no other work other than hold the bar.', 'After a second of squeezing the biceps in the contracted position, slowly lower your torso back to the starting position; when your arms are fully extended. Breathe in as you perform this portion of the movement.', 'Repeat this motion for the prescribed amount of repetitions.']",
        images=['Chin-Up/0.jpg', 'Chin-Up/1.jpg'],
    ),
    "Weighted_Pull_Ups": ExerciseDefinition(
        id="Weighted_Pull_Ups",
        display_name="Weighted Pull Ups",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.OTHER,
        secondary_muscles=[MuscleGroup.BICEPS],
        instructions="""['Attach a weight to a dip belt and secure it around your waist. Grab the pull-up bar with the palms of your hands facing forward. For a medium grip, your hands should be spaced at shoulder width. Both arms should be extended in front of you holding the bar at the chosen grip.', "You'll want to bring your torso back about 30 degrees while creating a curvature in your lower back and sticking your chest out. This will be your starting position.", 'Now, exhale and pull your torso up until your head is above your hands. Concentrate on squeezing yourshoulder blades back and down as you reach the top contracted position.', 'After a brief moment at the top contracted position, inhale and slowly lower your torso back to the starting position with your arms extended and your lats fully stretched.']""",
        images=['Weighted_Pull_Ups/0.jpg', 'Weighted_Pull_Ups/1.jpg'],
    ),
    "V-Bar_Pullup": ExerciseDefinition(
        id="V-Bar_Pullup",
        display_name="V-Bar Pullup",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.BICEPS, MuscleGroup.SHOULDERS],
        instructions="['Start by placing the middle of the V-bar in the middle of the pull-up bar (assuming that the pull-up station you are using does not have neutral grip handles). The V-Bar handles will be facing down so that you can hang from the pull-up bar through the use of the handles.', 'Once you securely place the V-bar, take a hold of the bar from each side and hang from it. Stick your chest out and lean yourself back slightly in order to better engage the lats. This will be your starting position.', 'Using your lats, pull your torso up while leaning your head back slightly so that you do not hit yourself with the chin-up bar. Continue until your chest nearly touches the V-bar. Exhale as you execute this motion.', 'After a second hold on the contracted position, slowly lower your body back to the starting position as you breathe in.', 'Repeat for the prescribed number of repetitions.']",
        images=['V-Bar_Pullup/0.jpg', 'V-Bar_Pullup/1.jpg'],
    ),
    "Kneeling_High_Pulley_Row": ExerciseDefinition(
        id="Kneeling_High_Pulley_Row",
        display_name="Kneeling High Pulley Row",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.CABLE,
        secondary_muscles=[MuscleGroup.BICEPS],
        instructions="['Select the appropriate weight using a pulley that is above your head. Attach a rope to the cable and kneel a couple of feet away, holding the rope out in front of you with both arms extended. This will be your starting position.', 'Initiate the movement by flexing the elbows and fully retracting your shoulders, pulling the rope toward your upper chest with your elbows out.', 'After pausing briefly, slowly return to the starting position.']",
        images=['Kneeling_High_Pulley_Row/0.jpg', 'Kneeling_High_Pulley_Row/1.jpg'],
    ),
    "Overhead_Slam": ExerciseDefinition(
        id="Overhead_Slam",
        display_name="Overhead Slam",
        level=LevelType.BEGINNER,
        category=CategoryType.PLYOMETRICS,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.MEDICINE_BALL,
        instructions="['Hold a medine ball with both hands and stand with your feet at shoulder width. This will be your starting position.', 'Initiate the countermovement by raising the ball above your head and fully extending your body.', 'Reverse the motion, slamming the ball into the ground directly in front of you as hard as you can.', 'Receive the ball with both hands on the bounce and repeat the movement.']",
        images=['Overhead_Slam/0.jpg', 'Overhead_Slam/1.jpg'],
    ),
    "Full_Range-Of-Motion_Lat_Pulldown": ExerciseDefinition(
        id="Full_Range-Of-Motion_Lat_Pulldown",
        display_name="Full Range-Of-Motion Lat Pulldown",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.CABLE,
        secondary_muscles=[MuscleGroup.BICEPS, MuscleGroup.SHOULDERS],
        instructions="['Either standing or seated on a high bench, grasp two stirrup cables that are attached to the high pulleys. Grab with the opposing hand so your arms are crisscrossed about you and your palms are facing forward.', 'Keeping your chest up and maintaining a slight arch in your lower back, pull the handles down as if you were doing a regular pulldown. The range of motion will be more of an arc. During the movement, rotate your hands so that in the bottom position your palms face each other rather than forward. Return slowly to the starting position and repeat.']",
        images=['Full_Range-Of-Motion_Lat_Pulldown/0.jpg', 'Full_Range-Of-Motion_Lat_Pulldown/1.jpg'],
    ),
    "Leverage_Iso_Row": ExerciseDefinition(
        id="Leverage_Iso_Row",
        display_name="Leverage Iso Row",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.MACHINE,
        secondary_muscles=[MuscleGroup.BICEPS],
        instructions="['Load an appropriate weight onto the pins and adjust the seat height so that the handles are at chest level. Grasp the handles with either a neutral or pronated grip. This will be your starting position.', 'Pull the handles towards your torso, retracting your shoulder blades as you flex the elbow.', 'Pause at the bottom of the motion, and then slowly return the handles to the starting position. For multiple repetitions, avoid completely returning the weight to the stops to keep tension on the muscles being worked.']",
        images=['Leverage_Iso_Row/0.jpg', 'Leverage_Iso_Row/1.jpg'],
    ),
    "Bent-Arm_Barbell_Pullover": ExerciseDefinition(
        id="Bent-Arm_Barbell_Pullover",
        display_name="Bent-Arm Barbell Pullover",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.CHEST, MuscleGroup.LATS, MuscleGroup.SHOULDERS, MuscleGroup.TRICEPS],
        instructions="['Lie on a flat bench with a barbell using a shoulder grip width.', 'Hold the bar straight over your chest with a bend in your arms. This will be your starting position.', 'While keeping your arms in the bent arm position, lower the weight slowly in an arc behind your head while breathing in until you feel a stretch on the chest.', 'At that point, bring the barbell back to the starting position using the arc through which the weight was lowered and exhale as you perform this movement.', 'Hold the weight on the initial position for a second and repeat the motion for the prescribed number of repetitions.']",
        images=['Bent-Arm_Barbell_Pullover/0.jpg', 'Bent-Arm_Barbell_Pullover/1.jpg'],
    ),
    "London_Bridges": ExerciseDefinition(
        id="London_Bridges",
        display_name="London Bridges",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.OTHER,
        secondary_muscles=[MuscleGroup.BICEPS, MuscleGroup.FOREARMS],
        instructions="['Attach a climbing rope to a high beam or cross member. Below it, ensure that the smith machine bar is locked in place with the safeties and cannot move. Alternatively, a secure box could also be utilized.', 'Stand on the bar, using the rope to balance yourself. This will be your starting position.', 'Keeping your body straight, lean back and lower your body by slowly going hand over hand with the rope. Continue until you are perpendicular to the ground.', 'Keeping your body straight, reverse the motion, going hand over hand back to the starting position.']",
        images=['London_Bridges/0.jpg', 'London_Bridges/1.jpg'],
    ),
    "Chair_Lower_Back_Stretch": ExerciseDefinition(
        id="Chair_Lower_Back_Stretch",
        display_name="Chair Lower Back Stretch",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.STATIC,
        mechanics_type=MechanicsType.ISOLATION,
        secondary_muscles=[MuscleGroup.LOWER_BACK],
        instructions="['Sit upright on a chair.', 'Bend to one side with your arm over your head. You can hold onto the chair with your free hand.', 'Hold for 10 seconds, and repeat for your other side.']",
        images=['Chair_Lower_Back_Stretch/0.jpg', 'Chair_Lower_Back_Stretch/1.jpg'],
    ),
    "Muscle_Up": ExerciseDefinition(
        id="Muscle_Up",
        display_name="Muscle Up",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.OTHER,
        secondary_muscles=[MuscleGroup.ABS, MuscleGroup.BICEPS, MuscleGroup.FOREARMS, MuscleGroup.SHOULDERS, MuscleGroup.TRAPS, MuscleGroup.TRICEPS],
        instructions="['Grip the rings using a false grip, with the base of your palms on top of the rings. Initiate a pull up by pulling the elbows down to your side, flexing the elbows.', 'As you reach the top position of the pull-up, pull the rings to your armpits as you roll your shoulders forward, allowing your elbows to move straight back behind you. This puts you into the proper position to continue into the dip portion of the movement.', 'Maintaining control and stability, extend through the elbow to complete the motion.', 'Use care when lowering yourself to the ground.']",
        images=['Muscle_Up/0.jpg', 'Muscle_Up/1.jpg'],
    ),
    "One_Arm_Lat_Pulldown": ExerciseDefinition(
        id="One_Arm_Lat_Pulldown",
        display_name="One Arm Lat Pulldown",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.CABLE,
        secondary_muscles=[MuscleGroup.BICEPS],
        instructions="['Select an appropriate weight and adjust the knee pad to help keep you down. Grasp the handle with a pronated grip. This will be your starting position.', 'Pull the handle down, squeezing your elbow to your side as you flex the elbow.', 'Pause at the bottom of the motion, and then slowly return the handle to the starting position.', 'For multiple repetitions, avoid completely returning the weight to keep tension on the muscles being worked.']",
        images=['One_Arm_Lat_Pulldown/0.jpg', 'One_Arm_Lat_Pulldown/1.jpg'],
    ),
    "Rocky_Pull-Ups_Pulldowns": ExerciseDefinition(
        id="Rocky_Pull-Ups_Pulldowns",
        display_name="Rocky Pull-Ups/Pulldowns",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.OTHER,
        secondary_muscles=[MuscleGroup.BICEPS, MuscleGroup.SHOULDERS],
        instructions="['Grab the pull-up bar with the palms facing forward using a wide grip.', 'As you have both arms extended in front of you holding the bar at the chosen grip width, bring your torso back around 30 degrees or so while creating a curvature on your lower back and sticking your chest out. This is your starting position.', 'Pull your torso up until the bar touches your upper chest by drawing the shoulders and the upper arms down and back. Exhale as you perform this portion of the movement. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. The upper torso should remain stationary as it moves through space and only the arms should move. The forearms should do no other work other than hold the bar.', 'After a second on the contracted position, start to inhale and slowly lower your torso back to the starting position when your arms are fully extended and the lats are fully stretched.', 'Now repeat the same movements as described above except this time your torso will remain straight as you go up and the bar will touch the back of the neck instead of the upper chest. Tip: Use the head to lean forward slightly as it will help you properly execute this portion of the exercise.', 'Once you have lowered yourself back down to the starting position, repeat the exercise for the prescribed amount of repetitions in your program.']",
        images=['Rocky_Pull-Ups_Pulldowns/0.jpg', 'Rocky_Pull-Ups_Pulldowns/1.jpg'],
    ),
    "Dynamic_Back_Stretch": ExerciseDefinition(
        id="Dynamic_Back_Stretch",
        display_name="Dynamic Back Stretch",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        instructions="['Stand with your feet shoulder width apart. This will be your starting position.', 'Keeping your arms straight, swing them straight up in front of you 5-10 times, increasing the range of motion each time until your arms are above your head.']",
        images=['Dynamic_Back_Stretch/0.jpg', 'Dynamic_Back_Stretch/1.jpg'],
    ),
    "One_Arm_Against_Wall": ExerciseDefinition(
        id="One_Arm_Against_Wall",
        display_name="One Arm Against Wall",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.STATIC,
        mechanics_type=MechanicsType.ISOLATION,
        instructions="['From a standing position, place a bent arm against a wall or doorway.', 'Slowly lean toward your arm until you feel a stretch in your lats.']",
        images=['One_Arm_Against_Wall/0.jpg', 'One_Arm_Against_Wall/1.jpg'],
    ),
    "Elevated_Cable_Rows": ExerciseDefinition(
        id="Elevated_Cable_Rows",
        display_name="Elevated Cable Rows",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.CABLE,
        secondary_muscles=[MuscleGroup.TRAPS],
        instructions="['Get a platform of some sort (it can be an aerobics or calf raise platform) that is around 4-6 inches in height.', 'Place it on the seat of the cable row machine.', 'Sit down on the machine and place your feet on the front platform or crossbar provided making sure that your knees are slightly bent and not locked.', 'Lean over as you keep the natural alignment of your back and grab the V-bar handles.', 'With your arms extended pull back until your torso is at a 90-degree angle from your legs. Your back should be slightly arched and your chest should be sticking out. You should be feeling a nice stretch on your lats as you hold the bar in front of you. This is the starting position of the exercise.', 'Keeping the torso stationary, pull the handles back towards your torso while keeping the arms close to it until you touch the abdominals. Breathe out as you perform that movement. At that point you should be squeezing your back muscles hard. Hold that contraction for a second and slowly go back to the original position while breathing in.', 'Repeat for the recommended amount of repetitions.']",
        images=['Elevated_Cable_Rows/0.jpg', 'Elevated_Cable_Rows/1.jpg'],
    ),
    "Rope_Straight-Arm_Pulldown": ExerciseDefinition(
        id="Rope_Straight-Arm_Pulldown",
        display_name="Rope Straight Arm Pulldown",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="['Attach a rope to a high pulley and make your weight selection. Stand a couple feet back from the pulley with your feet staggered and take the rope with both hands. Lean forward from the hip, keeping your back straight, with your arms extended up in front of you. This will be your starting position.', 'Keeping your arms straight, extend the shoulder to pull the rope down to your thighs.', 'Pause at the bottom of the motion, squeezing your lats.', 'Return to the starting position without allowing the weight to fully rest on the stack.']",
        images=['Rope_Straight-Arm_Pulldown/0.jpg', 'Rope_Straight-Arm_Pulldown/1.jpg'],
    ),
    "Kipping_Muscle_Up": ExerciseDefinition(
        id="Kipping_Muscle_Up",
        display_name="Kipping Muscle Up",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.OTHER,
        secondary_muscles=[MuscleGroup.ABS, MuscleGroup.BICEPS, MuscleGroup.FOREARMS, MuscleGroup.SHOULDERS, MuscleGroup.TRAPS, MuscleGroup.TRICEPS],
        instructions="['Grip the rings using a false grip, with the base of your palms on top of the rings.', 'Begin with a movement swinging your legs backward slightly.', 'Counter that movement by swinging your legs forward and up, jerking your chin and chest back, pulling yourself up with both arms as you do so. As you reach the top position of the pull-up, pull the rings to your armpits as you roll your shoulders forward, allowing your elbows to move straight back behind you. This puts you into the proper position to continue into the dip portion of the movement.', 'Maintaining control and stability, extend through the elbow to complete the motion.', 'Use care when lowering yourself to the ground.']",
        images=['Kipping_Muscle_Up/0.jpg', 'Kipping_Muscle_Up/1.jpg'],
    ),
    "Underhand_Cable_Pulldowns": ExerciseDefinition(
        id="Underhand_Cable_Pulldowns",
        display_name="Underhand Cable Pulldowns",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.CABLE,
        secondary_muscles=[MuscleGroup.BICEPS, MuscleGroup.SHOULDERS],
        instructions="['Sit down on a pull-down machine with a wide bar attached to the top pulley. Adjust the knee pad of the machine to fit your height. These pads will prevent your body from being raised by the resistance attached to the bar.', 'Grab the pull-down bar with the palms facing your torso (a supinated grip). Make sure that the hands are placed closer than the shoulder width.', 'As you have both arms extended in front of you holding the bar at the chosen grip width, bring your torso back around 30 degrees or so while creating a curvature on your lower back and sticking your chest out. This is your starting position.', 'As you breathe out, pull the bar down until it touches your upper chest by drawing the shoulders and the upper arms down and back. Tip: Concentrate on squeezing the back muscles once you reach the fully contracted position and keep the elbows close to your body. The upper torso should remain stationary as your bring the bar to you and only the arms should move. The forearms should do no other work other than hold the bar.', 'After a second on the contracted position, while breathing in, slowly bring the bar back to the starting position when your arms are fully extended and the lats are fully stretched.', 'Repeat this motion for the prescribed amount of repetitions.']",
        images=['Underhand_Cable_Pulldowns/0.jpg', 'Underhand_Cable_Pulldowns/1.jpg'],
    ),
    "Row": ExerciseDefinition(
        id="Row",
        display_name="Row",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.CABLE,
        secondary_muscles=[],
        instructions="""['A row exercise builds back strength by pulling weight towards your body, engaging lats, rhomboids, traps, and rear delts, with variations like seated cable rows, bent-over barbell rows, and single-arm dumbbell rows targeting these muscles with proper form (hinging hips, squeezing shoulder blades, leading with elbows) for a thicker, stronger back and better posture.']""",
        images=[],
    ),
    "Narrow-Grip_Lat_Pulldown": ExerciseDefinition(
        id="Narrow-Grip_Lat_Pulldown",
        display_name="Narrow-Grip Lat Pulldown",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.CABLE,
        secondary_muscles=[],
        instructions="""['To do a narrow grip lat pulldown, sit securely, grab the bar with palms facing you (underhand) or neutral grip, keep chest up, and pull the bar down towards your upper chest by driving your elbows down and back, squeezing your lats, then slowly control the weight back up for a full stretch. Focus on pulling with your elbows, not just your arms, keeping your torso stable with minimal leaning to effectively target the lats.']""",
        images=[],
    ),
    "Straight-Arm_Pushdown": ExerciseDefinition(
        id="Straight-Arm_Pushdown",
        display_name="Straight Arm Pushdown",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.CABLE,
        secondary_muscles=[],
        instructions="""['To do a straight arm pulldown, set a high pulley, grab a bar/rope with a slightly wider than shoulder-width grip, step back, lean forward slightly with a soft bend in your elbows, engage your core, and pull the attachment down towards your thighs by depressing your shoulder blades and squeezing your lats, controlling the movement both down and up for a full stretch, focusing on lat isolation, not arm bending.']""",
        images=[],
    ),
    "Dumbbell_Pullover_Ladder": ExerciseDefinition(
        id="Dumbbell_Pullover_Ladder",
        display_name="Dumbbell Pullover Ladder",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.CABLE,
        secondary_muscles=[],
        instructions="""['To do a straight arm pulldown, set a high pulley, grab a bar/rope with a slightly wider than shoulder-width grip, step back, lean forward slightly with a soft bend in your elbows, engage your core, and pull the attachment down towards your thighs by depressing your shoulder blades and squeezing your lats, controlling the movement both down and up for a full stretch, focusing on lat isolation, not arm bending.']""",
        images=[],
    ),
    "BodyWeight/Band_Pullover_Ladder": ExerciseDefinition(
        id="BodyWeight/Band_Pullover_Ladder",
        display_name="BodyWeight/Band Pullover Ladder",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.CABLE,
        secondary_muscles=[],
        instructions="""['A Band Pullover Ladder isn't a standard term, but it likely combines Banded Pullovers (targeting lats/chest) with a ladder drill for footwork/stability, or perhaps the "ladder" refers to the band's resistance progression. The basic Banded Pullover involves anchoring a band low, lying on your back, and pulling straight arms from overhead to your thighs, focusing on lat engagement. For a "ladder" aspect, you might do this in a progression, or incorporate Banded Wall Ladders, moving hands up and down a wall for shoulder stability.']""",
        images=[],
    ),
    "Inverted_Row": ExerciseDefinition(
        id="Inverted_Row",
        display_name="Inverted Row",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.CABLE,
        secondary_muscles=[],
        instructions="""['To do an inverted row, set a bar (like on a squat rack, Smith machine, or TRX) at waist height, lie underneath it, grab it slightly wider than shoulder-width with an overhand grip, keep your body in a straight line (hips and shoulders aligned), and pull your chest to the bar while squeezing your shoulder blades, then lower with control. Adjust bar height or foot position to change difficulty—higher bar/feet forward is easier, lower bar/feet elevated is harder, keeping your core and glutes tight throughout.']""",
        images=[],
    ),
    "Barbell_Row": ExerciseDefinition(
        id="Barbell_Row",
        display_name="Barbell Row",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[],
        instructions="""['To do a barbell row, start standing with feet hip-width apart, knees slightly bent, and hinge at your hips with a flat back to grab the bar just outside your knees (overhand grip). Pull the bar towards your lower abdomen/hips by driving your elbows back, squeezing your shoulder blades together, then control the weight back down to a full stretch, keeping your torso stable at about a 30-45 degree angle throughout.']""",
        images=[],
    ),
    "Dumbbell_High_Pull": ExerciseDefinition(
        id="Dumbbell_High_Pull",
        display_name="Dumbbell High Pull",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.DUMBBELL,
        secondary_muscles=[],
        instructions="""['The dumbbell high pull is an explosive, full-body lift where you hinge at the hips, then explosively stand and thrust your hips forward to pull dumbbells up to shoulder height, leading with your elbows, focusing on hip power, not arm strength, and controlling the weight back down.']""",
        images=[],
    ),
    "Scap_Pulldown": ExerciseDefinition(
        id="Scap_Pulldown",
        display_name="Scap Pulldown",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.CABLE,
        secondary_muscles=[],
        instructions="""['A scap pulldown (or scapular pull-up) strengthens your back and prepares for pull-ups by focusing on shoulder blade movement: hang from a bar with straight arms, then pull your shoulder blades down and together (depress and retract) to lift your body a few inches, keeping arms locked, then slowly lower back down, engaging your traps and lats, not your biceps. It's great for beginners as a warm-up, building mind-muscle connection for real pull-ups.']""",
        images=[],
    ),
    "Seated_Cable_Row": ExerciseDefinition(
        id="Seated_Cable_Row",
        display_name="Seated Cable Row",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.CABLE,
        secondary_muscles=[],
        instructions="""['To do a seated cable row, sit with feet on the platform, knees slightly bent, and a straight back; grab the handle, pull it to your midsection by squeezing your shoulder blades together (keeping elbows in), pause, then slowly extend back to start, focusing on back muscles, not momentum, for a strong upper-back workout.']""",
        images=[],
    ),
    "BodyWeight/Band_Pullup": ExerciseDefinition(
        id="BodyWeight/Band_Pullup",
        display_name="BodyWeight/Band Pullup",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.CABLE,
        secondary_muscles=[],
        instructions="""['To do a bodyweight/banded pull-up, loop a resistance band around the bar, step into the loop (foot or knee), grab the bar with a wide grip, and pull your chin up by driving elbows down, engaging your back, then lower slowly; use thicker bands for more help and thinner bands as you get stronger to progress from assisted to unassisted pull-ups. Focus on engaging shoulder blades back and down (scapular retraction) and controlling the entire movement.']""",
        images=[],
    ),
    "High_Cable_Row_Ladder": ExerciseDefinition(
        id="High_Cable_Row_Ladder",
        display_name="High Cable Row Ladder",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LATS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.CABLE,
        secondary_muscles=[],
        instructions="""['The high cable row ladder is performed by attaching a rope or handles to a high pulley set around shoulder or head height, then standing facing the machine with your feet about hip-width apart and stepping back slightly to create tension in the cable. Brace your core, keep your chest up, and maintain a neutral spine. Begin the movement by pulling your shoulder blades down and together, then bend your elbows and pull the handles down and back toward your upper chest, allowing your elbows to move slightly out to the sides. At the end of the pull, squeeze your upper back and rear shoulders briefly, then slowly extend your arms back to the starting position under control, keeping your shoulders from rolling forward. Throughout the exercise, focus on controlled motion rather than momentum, emphasizing scapular retraction and steady tension in the upper back muscles.']""",
        images=[],
    ),
}
