from exercises.base import ExerciseDefinition
from enums import MuscleGroup, EquipmentType, MechanicsType, MajorMuscleGroup, ForceType, LevelType, CategoryType

LOWER_BACK_EXERCISES = {
    "Rack_Pull_with_Bands": ExerciseDefinition(
        id="Rack_Pull_with_Bands",
        display_name="Rack Pull with Bands",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.POWERLIFTING,
        muscle_group=MuscleGroup.LOWER_BACK,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.FOREARMS, MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS, MuscleGroup.QUADS, MuscleGroup.TRAPS],
        instructions="""['Set up in a power rack with the bar on the pins. The pins should be set to the desired point; just below the knees, just above, or in the mid thigh position. Attach bands to the base of the rack, or secure them with dumbbells. Attach the other end to the bar. You may need to choke the bands to provide tension.', 'Position yourself against the bar in proper deadlifting position. Your feet should be under your hips, your grip shoulder width, back arched, and hips back to engage the hamstrings. Since the weight is typically heavy, you may use a mixed grip, a hook grip, or use straps to aid in holding the weight.', 'With your head looking forward, extend through the hips and knees, pulling the weight up and back until lockout. Be sure to pull your shoulders back as you complete the movement. Return the weight to the pins and repeat.']""",
        images=['Rack_Pull_with_Bands/0.jpg', 'Rack_Pull_with_Bands/1.jpg'],
    ),
    "Cat_Stretch": ExerciseDefinition(
        id="Cat_Stretch",
        display_name="Cat Stretch",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.LOWER_BACK,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.STATIC,
        secondary_muscles=[MuscleGroup.TRAPS],
        instructions="""['Position yourself on the floor on your hands and knees.', 'Pull your belly in and round your spine, lower back, shoulders, and neck, letting your head drop.', 'Hold for 15 seconds.']""",
        images=['Cat_Stretch/0.jpg', 'Cat_Stretch/1.jpg'],
    ),
    "Standing_Pelvic_Tilt": ExerciseDefinition(
        id="Standing_Pelvic_Tilt",
        display_name="Standing Pelvic Tilt",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.LOWER_BACK,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.STATIC,
        mechanics_type=MechanicsType.ISOLATION,
        secondary_muscles=[MuscleGroup.GLUTES],
        instructions="""['Start off with your feet hip-distance apart.', 'Bend your knees slightly to keep them soft and springy.', 'You may want to move your pelvis forward and backward and back few times before holding the tailbone forward in this stretch.']""",
        images=['Standing_Pelvic_Tilt/0.jpg', 'Standing_Pelvic_Tilt/1.jpg'],
    ),
    "Deadlift_with_Chains": ExerciseDefinition(
        id="Deadlift_with_Chains",
        display_name="Deadlift with Chains",
        level=LevelType.EXPERT,
        category=CategoryType.POWERLIFTING,
        muscle_group=MuscleGroup.LOWER_BACK,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.FOREARMS, MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS, MuscleGroup.QUADS, MuscleGroup.TRAPS],
        instructions="""['You can attach the chains to the sleeves of the bar, or just drape the middle over the bar so there is a greater weight increase as you lift.', 'Approach the bar so that it is centered over your feet. You feet should be about hip width apart. Bend at the hip to grip the bar at shoulder width, allowing your shoulder blades to protract. Typically, you would use an overhand grip or an over/under grip on heavier sets. With your feet, and your grip set, take a big breath and then lower your hips and bend the knees until your shins contact the bar.', 'Look forward with your head, keep your chest up and your back arched, and begin driving through the heels to move the weight upward. After the bar passes the knees, aggressively pull the bar back, pulling your shoulder blades together as you drive your hips forward into the bar.', 'Lower the bar by bending at the hips and guiding it to the floor.']""",
        images=['Deadlift_with_Chains/0.jpg', 'Deadlift_with_Chains/1.jpg'],
    ),
    "Atlas_Stones": ExerciseDefinition(
        id="Atlas_Stones",
        display_name="Atlas Stones",
        level=LevelType.EXPERT,
        category=CategoryType.STRONGMAN,
        muscle_group=MuscleGroup.LOWER_BACK,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.OTHER,
        secondary_muscles=[MuscleGroup.ABS, MuscleGroup.ADDUCTORS, MuscleGroup.BICEPS, MuscleGroup.CALVES, MuscleGroup.FOREARMS, MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS, MuscleGroup.QUADS, MuscleGroup.TRAPS],
        instructions="""['Begin with the atlas stone between your feet. Bend at the hips to wrap your arms vertically around the Atlas Stone, attempting to get your fingers underneath the stone. Many stones will have a small flat portion on the bottom, which will make the stone easier to hold.', 'Pulling the stone into your torso, drive through the back half of your feet to pull the stone from the ground.', 'As the stone passes the knees, lap it by sitting backward, pulling the stone on top of your thighs.', 'Sit low, getting the stone high onto your chest as you change your grip to reach over the stone. Stand, driving through with your hips. Close distance to the loading platform, and lean back, extending the hips to get the stone as high as possible.']""",
        images=['Atlas_Stones/0.jpg', 'Atlas_Stones/1.jpg'],
    ),
    "Superman": ExerciseDefinition(
        id="Superman",
        display_name="Superman",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.LOWER_BACK,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.STATIC,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS],
        instructions="""['To begin, lie straight and face down on the floor or exercise mat. Your arms should be fully extended in front of you. This is the starting position.', 'Simultaneously raise your arms, legs, and chest off of the floor and hold this contraction for 2 seconds. Tip: Squeeze your lower back to get the best results from this exercise. Remember to exhale during this movement. Note: When holding the contracted position, you should look like superman when he is flying.', 'Slowly begin to lower your arms, legs and chest back down to the starting position while inhaling.', 'Repeat for the recommended amount of repetitions prescribed in your program.']""",
        images=['Superman/0.jpg', 'Superman/1.jpg'],
    ),
    "Reverse_Band_Deadlift": ExerciseDefinition(
        id="Reverse_Band_Deadlift",
        display_name="Reverse Band Deadlift",
        level=LevelType.EXPERT,
        category=CategoryType.POWERLIFTING,
        muscle_group=MuscleGroup.LOWER_BACK,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.ABDUCTORS, MuscleGroup.ADDUCTORS, MuscleGroup.CALVES, MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS, MuscleGroup.QUADS],
        instructions="""['Set the bar up in a power rack. Attach bands to the top of the rack, using either bands pegs or the frame itself. Attach the other end of the bands to the bar.', 'Approach the bar so that it is centered over your feet. You feet should be about hip width apart. Bend at the hip to grip the bar at shoulder width, allowing your shoulder blades to protract. Typically, you would use an overhand grip or an over/under grip on heavier sets.', 'With your feet, and your grip set, take a big breath and then lower your hips and bend the knees until your shins contact the bar. Look forward with your head, keep your chest up and your back arched, and begin driving through the heels to move the weight upward.', 'After the bar passes the knees, aggressively pull the bar back, pulling your shoulder blades together as you drive your hips forward into the bar.', 'Lower the bar by bending at the hips and guiding it to the floor.']""",
        images=['Reverse_Band_Deadlift/0.jpg', 'Reverse_Band_Deadlift/1.jpg'],
    ),
    "Pelvic_Tilt_Into_Bridge": ExerciseDefinition(
        id="Pelvic_Tilt_Into_Bridge",
        display_name="Pelvic Tilt Into Bridge",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.LOWER_BACK,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.STATIC,
        mechanics_type=MechanicsType.COMPOUND,
        instructions="""['Lie down with your feet on the floor, heels directly under your knees.', "Lift only your tailbone to the ceiling to stretch your lower back. (Don't lift the entire spine yet.) Pull in your stomach.", 'To go into a bridge, lift the entire spine except the neck.']""",
        images=['Pelvic_Tilt_Into_Bridge/0.jpg', 'Pelvic_Tilt_Into_Bridge/1.jpg'],
    ),
    "Hug_Knees_To_Chest": ExerciseDefinition(
        id="Hug_Knees_To_Chest",
        display_name="Hug Knees To Chest",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.LOWER_BACK,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.STATIC,
        secondary_muscles=[MuscleGroup.GLUTES],
        instructions="""['Lie down on your back and pull both knees up to your chest.', 'Hold your arms under the knees, not over (that would put to much pressure on your knee joints).', 'Slowly pull the knees toward your shoulders. This also stretches your buttocks muscles.']""",
        images=['Hug_Knees_To_Chest/0.jpg', 'Hug_Knees_To_Chest/1.jpg'],
    ),
    "Hyperextensions_Back_Extensions": ExerciseDefinition(
        id="Hyperextensions_Back_Extensions",
        display_name="Hyperextensions (Back Extensions)",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LOWER_BACK,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.OTHER,
        secondary_muscles=[MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS],
        instructions="""['Lie face down on a hyperextension bench, tucking your ankles securely under the footpads.', 'Adjust the upper pad if possible so your upper thighs lie flat across the wide pad, leaving enough room for you to bend at the waist without any restriction.', 'With your body straight, cross your arms in front of you (my preference) or behind your head. This will be your starting position. Tip: You can also hold a weight plate for extra resistance in front of you under your crossed arms.', 'Start bending forward slowly at the waist as far as you can while keeping your back flat. Inhale as you perform this movement. Keep moving forward until you feel a nice stretch on the hamstrings and you can no longer keep going without a rounding of the back. Tip: Never round the back as you perform this exercise. Also, some people can go farther than others. The key thing is that you go as far as your body allows you to without rounding the back.', 'Slowly raise your torso back to the initial position as you inhale. Tip: Avoid the temptation to arch your back past a straight line. Also, do not swing the torso at any time in order to protect the back from injury.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Hyperextensions_Back_Extensions/0.jpg', 'Hyperextensions_Back_Extensions/1.jpg'],
    ),
    "Seated_Good_Mornings": ExerciseDefinition(
        id="Seated_Good_Mornings",
        display_name="Seated Good Mornings",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.POWERLIFTING,
        muscle_group=MuscleGroup.LOWER_BACK,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.GLUTES],
        instructions="""['Set up a box in a power rack. The pins should be set at an appropriate height. Begin by stepping under the bar and placing it across the back of the shoulders, not on top of your traps. Squeeze your shoulder blades together and rotate your elbows forward, attempting to bend the bar across your shoulders.', 'Remove the bar from the rack, creating a tight arch in your lower back. Keep your head facing forward. With your back, shoulders, and core tight, push your knees and butt out and you begin your descent. Sit back with your hips until you are seated on the box. This will be your starting position.', 'Keeping the bar tight, bend forward at the hips as much as possible. If you set the pins to what would be parallel, you not only have a safety if you fail, but know when to stop.', 'Pause just above the pins and reverse the motion until your torso it upright.']""",
        images=['Seated_Good_Mornings/0.jpg', 'Seated_Good_Mornings/1.jpg'],
    ),
    "Childs_Pose": ExerciseDefinition(
        id="Childs_Pose",
        display_name="Child's Pose",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.LOWER_BACK,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.STATIC,
        secondary_muscles=[MuscleGroup.GLUTES],
        instructions="""['Get on your hands and knees, walk your hands in front of you.', 'Lower your buttocks down to sit on your heels. Let your arms drag along the floor as you sit back to stretch your entire spine.', 'Once you settle onto your heels, bring your hands next to your feet and relax. "breathe" into your back. Rest your forehead on the floor. Avoid this position if you have knee problems.']""",
        images=['Childs_Pose/0.jpg', 'Childs_Pose/1.jpg'],
    ),
    "Hug_A_Ball": ExerciseDefinition(
        id="Hug_A_Ball",
        display_name="Hug A Ball",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.LOWER_BACK,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.STATIC,
        mechanics_type=MechanicsType.ISOLATION,
        secondary_muscles=[MuscleGroup.CALVES, MuscleGroup.GLUTES],
        instructions="""['Seat yourself on the floor.', 'Straddle an exercise ball between both legs and lower your hips down toward the floor.', "Hug your arms around the ball to support your body. Adjust your legs so that your feet are flat on the floor and your knees line up over your ankles. Keep a good grip on the ball so it doesn't roll away from you and send you back onto your buttocks."']""",
        images=['Hug_A_Ball/0.jpg', 'Hug_A_Ball/1.jpg'],
    ),
    "Atlas_Stone_Trainer": ExerciseDefinition(
        id="Atlas_Stone_Trainer",
        display_name="Atlas Stone Trainer",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRONGMAN,
        muscle_group=MuscleGroup.LOWER_BACK,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.OTHER,
        secondary_muscles=[MuscleGroup.BICEPS, MuscleGroup.FOREARMS, MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS, MuscleGroup.QUADS],
        instructions="""["This trainer is effective for developing Atlas Stone strength for those who don't have access to stones, and are typically made from bar ends or heavy pipe.", 'Begin by loading the desired weight onto the bar. Straddle the weight, wrapping your arms around the implement, bending at the hips.', 'Begin by pulling the weight up past the knees, extending through the hips. As the weight clears the knees, it can be lapped by resting it on your thighs and sitting back, hugging it tightly to your chest.', 'Finish the movement by extending through your hips and knees to raise the weight as high as possible. The weight can be returned to the lap or to the ground for successive repetitions.']""",
        images=['Atlas_Stone_Trainer/0.jpg', 'Atlas_Stone_Trainer/1.jpg'],
    ),
    "Stiff_Leg_Barbell_Good_Morning": ExerciseDefinition(
        id="Stiff_Leg_Barbell_Good_Morning",
        display_name="Stiff Leg Barbell Good Morning",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LOWER_BACK,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS],
        instructions="""['This exercise is best performed inside a squat rack for safety purposes. To begin, first set the bar on a rack that best matches your height. Once the correct height is chosen and the bar is loaded, step under the bar and place the back of your shoulders (slightly below the neck) across it.', 'Hold on to the bar using both arms at each side and lift it off the rack by first pushing with your legs and at the same time straightening your torso.', 'Step away from the rack and position your legs using a shoulder width medium stance. Keep your head up at all times as looking down will get you off balance and also maintain a straight back. This will be your starting position.', 'Keeping your legs stationary, move your torso forward by bending at the hips while inhaling. Lower your torso until it is parallel with the floor.', 'Begin to raise the bar as you exhale by elevating your torso back to the starting position.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Stiff_Leg_Barbell_Good_Morning/0.jpg', 'Stiff_Leg_Barbell_Good_Morning/1.jpg'],
    ),
    "Deficit_Deadlift": ExerciseDefinition(
        id="Deficit_Deadlift",
        display_name="Deficit Deadlift",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.POWERLIFTING,
        muscle_group=MuscleGroup.LOWER_BACK,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.FOREARMS, MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS, MuscleGroup.QUADS, MuscleGroup.TRAPS],
        instructions="""['Begin by having a platform or weight plates that you can stand on, usually 1-3 inches in height. Approach the bar so that it is centered over your feet. You feet should be about hip width apart. Bend at the hip to grip the bar at shoulder width, allowing your shoulder blades to protract. Typically, you would use an overhand grip or an over/under grip on heavier sets.', 'With your feet, and your grip set, take a big breath and then lower your hips and bend the knees until your shins contact the bar. Look forward with your head, keep your chest up and your back arched, and begin driving through the heels to move the weight upward. After the bar passes the knees, aggressively pull the bar back, pulling your shoulder blades together as you drive your hips forward into the bar.', 'Lower the bar by bending at the hips and guiding it to the floor.']""",
        images=['Deficit_Deadlift/0.jpg', 'Deficit_Deadlift/1.jpg'],
    ),
    "Hyperextensions_With_No_Hyperextension_Bench": ExerciseDefinition(
        id="Hyperextensions_With_No_Hyperextension_Bench",
        display_name="Hyperextensions With No Hyperextension Bench",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LOWER_BACK,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS],
        instructions="""['With someone holding down your legs, slide yourself down to the edge a flat bench until your hips hang off the end of the bench. Tip: Your entire upper body should be hanging down towards the floor. Also, you will be in the same position as if you were on a hyperextension bench but the range of motion will be shorter due to the height of the flat bench vs. that of the hyperextension bench.', 'With your body straight, cross your arms in front of you (my preference) or behind your head. This will be your starting position. Tip: You can also hold a weight plate for extra resistance in front of you under your crossed arms.', 'Start bending forward slowly at the waist as far as you can while keeping your back flat. Inhale as you perform this movement. Keep moving forward until you almost touch the floor or you feel a nice stretch on the hamstrings (whichever comes first). Tip: Never round the back as you perform this exercise.', 'Slowly raise your torso back to the initial position as you exhale. Tip: Avoid the temptation to arch your back past a straight line. Also, do not swing the torso at any time in order to protect the back from injury.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Hyperextensions_With_No_Hyperextension_Bench/0.jpg', 'Hyperextensions_With_No_Hyperextension_Bench/1.jpg'],
    ),
    "Rack_Pulls": ExerciseDefinition(
        id="Rack_Pulls",
        display_name="Rack Pulls",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.POWERLIFTING,
        muscle_group=MuscleGroup.LOWER_BACK,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.FOREARMS, MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS, MuscleGroup.TRAPS],
        instructions="""['Set up in a power rack with the bar on the pins. The pins should be set to the desired point; just below the knees, just above, or in the mid thigh position. Position yourself against the bar in proper deadlifting position. Your feet should be under your hips, your grip shoulder width, back arched, and hips back to engage the hamstrings. Since the weight is typically heavy, you may use a mixed grip, a hook grip, or use straps to aid in holding the weight.', 'With your head looking forward, extend through the hips and knees, pulling the weight up and back until lockout. Be sure to pull your shoulders back as you complete the movement.', 'Return the weight to the pins and repeat.']""",
        images=['Rack_Pulls/0.jpg', 'Rack_Pulls/1.jpg'],
    ),
    "Deadlift_with_Bands": ExerciseDefinition(
        id="Deadlift_with_Bands",
        display_name="Deadlift with Bands",
        level=LevelType.EXPERT,
        category=CategoryType.POWERLIFTING,
        muscle_group=MuscleGroup.LOWER_BACK,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.FOREARMS, MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS, MuscleGroup.QUADS, MuscleGroup.TRAPS],
        instructions="""['To deadlift with short bands, simply loop them over the bar before you start, and step into them to set up. For long bands, they will need to be anchored to a secure base, such as heavy dumbbells or a rack.', 'With your feet, and your grip set, take a big breath and then lower your hips and bend the knees until your shins contact the bar. Look forward with your head, keep your chest up and your back arched, and begin driving through the heels to move the weight upward. After the bar passes the knees, aggressively pull the bar back, pulling your shoulder blades together as you drive your hips forward into the bar.', 'Lower the bar by bending at the hips and guiding it to the floor.']""",
        images=['Deadlift_with_Bands/0.jpg', 'Deadlift_with_Bands/1.jpg'],
    ),
    "Dancers_Stretch": ExerciseDefinition(
        id="Dancers_Stretch",
        display_name="Dancer's Stretch",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.LOWER_BACK,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.STATIC,
        secondary_muscles=[MuscleGroup.ABDUCTORS, MuscleGroup.GLUTES],
        instructions="""['Sit up on the floor.', 'Cross your right leg over your left, keeping the knee bent. Your left leg is straight and down on the floor.', 'Place your left arm on your right leg and your right hand on the floor.', 'Rotate your upper body to the right, and hold for 10-20 seconds. Switch sides.']""",
        images=['Dancers_Stretch/0.jpg', 'Dancers_Stretch/1.jpg'],
    ),
    "Keg_Load": ExerciseDefinition(
        id="Keg_Load",
        display_name="Keg Load",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRONGMAN,
        muscle_group=MuscleGroup.LOWER_BACK,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.OTHER,
        secondary_muscles=[MuscleGroup.ABS, MuscleGroup.BICEPS, MuscleGroup.CALVES, MuscleGroup.FOREARMS, MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS, MuscleGroup.QUADS, MuscleGroup.SHOULDERS, MuscleGroup.TRAPS],
        instructions="""['To load kegs, place the desired number a distance from the loading platform, typically 30-50 feet.', 'Begin by grabbing the close handle of the first keg, tilting it onto its side to grab the opposite edge of the bottom of the keg. Lift the keg up to your chest.', 'The higher you can place the keg, the faster you should be able to move to the platform. Shouldering is usually not allowed. Be sure to keep a firm hold on the keg. Move as quickly as possible to the platform, and load it, extending through your hips, knees, and ankles to get it as high as possible.', 'Return to the starting position to retrieve the next keg, and repeat until the event is completed.']""",
        images=['Keg_Load/0.jpg', 'Keg_Load/1.jpg'],
    ),
    "Lower_Back-SMR": ExerciseDefinition(
        id="Lower_Back-SMR",
        display_name="Lower Back-SMR",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.LOWER_BACK,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.STATIC,
        instructions="""['In a seated position, place a foam roll under your lower back. Cross your arms in front of you and protract your shoulders. This will be your starting position.', 'Raise your hips off of the floor and lean back, keeping your weight on your lower back. Now shift your weight slightly to one side, keeping your weight off of the spine and on the muscles to the side of it. Roll over your lower back, holding points of tension for 10-30 seconds. Repeat on the other side.']""",
        images=['Lower_Back-SMR/0.jpg', 'Lower_Back-SMR/1.jpg'],
    ),
    "Barbell_Deadlift": ExerciseDefinition(
        id="Barbell_Deadlift",
        display_name="Barbell Deadlift",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LOWER_BACK,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.CALVES, MuscleGroup.FOREARMS, MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS, MuscleGroup.LATS, MuscleGroup.QUADS, MuscleGroup.TRAPS],
        instructions="""['Stand in front of a loaded barbell.', 'While keeping the back as straight as possible, bend your knees, bend forward and grasp the bar using a medium (shoulder width) overhand grip. This will be the starting position of the exercise. Tip: If it is difficult to hold on to the bar with this grip, alternate your grip or use wrist straps.', 'While holding the bar, start the lift by pushing with your legs while simultaneously getting your torso to the upright position as you breathe out. In the upright position, stick your chest out and contract the back by bringing the shoulder blades back. Think of how the soldiers in the military look when they are in standing in attention.', 'Go back to the starting position by bending at the knees while simultaneously leaning the torso forward at the waist while keeping the back straight. When the weights on the bar touch the floor you are back at the starting position and ready to perform another repetition.', 'Perform the amount of repetitions prescribed in the program.']""",
        images=['Barbell_Deadlift/0.jpg', 'Barbell_Deadlift/1.jpg'],
    ),
    "Pyramid": ExerciseDefinition(
        id="Pyramid",
        display_name="Pyramid",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.LOWER_BACK,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.STATIC,
        secondary_muscles=[MuscleGroup.SHOULDERS],
        instructions="""['Start off by rolling your torso forward onto the ball so your hips rest on top of the ball and become the highest point of your body.', 'Rest your hands and feet on the floor. Your arms and legs can be slightly bent or straight, depending on the size of the ball, your flexibility, and the length of your limbs. This also helps develop stabilizing strength in your torso and shoulders.']""",
        images=['Pyramid/0.jpg', 'Pyramid/1.jpg'],
    ),
    "Axle_Deadlift": ExerciseDefinition(
        id="Axle_Deadlift",
        display_name="Axle Deadlift",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRONGMAN,
        muscle_group=MuscleGroup.LOWER_BACK,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.OTHER,
        secondary_muscles=[MuscleGroup.FOREARMS, MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS, MuscleGroup.QUADS, MuscleGroup.TRAPS],
        instructions="""['Approach the bar so that it is centered over your feet. You feet should be about hip width apart. Bend at the hip to grip the bar at shoulder width, allowing your shoulder blades to protract. Typically, you would use an over/under grip.', 'With your feet and your grip set, take a big breath and then lower your hips and flex the knees until your shins contact the bar. Look forward with your head, keep your chest up and your back arched, and begin driving through the heels to move the weight upward.', 'After the bar passes the knees, aggressively pull the bar back, pulling your shoulder blades together as you drive your hips forward into the bar.', 'Lower the bar by bending at the hips and guiding it to the floor.']""",
        images=['Axle_Deadlift/0.jpg', 'Axle_Deadlift/1.jpg'],
    ),
    "Crossover_Reverse_Lunge": ExerciseDefinition(
        id="Crossover_Reverse_Lunge",
        display_name="Crossover Reverse Lunge",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.LOWER_BACK,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        secondary_muscles=[MuscleGroup.ABS, MuscleGroup.ABDUCTORS, MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS, MuscleGroup.QUADS],
        instructions="""['Stand with your feet shoulder width apart. This will be your starting position.', 'Perform a rear lunge by stepping back with one foot and flexing the hips and front knee. As you do so, rotate your torso across the front leg.', 'After a brief pause, return to the starting position and repeat on the other side, continuing in an alternating fashion.']""",
        images=['Crossover_Reverse_Lunge/0.jpg', 'Crossover_Reverse_Lunge/1.jpg'],
    ),
    "Weighted_Ball_Hyperextension": ExerciseDefinition(
        id="Weighted_Ball_Hyperextension",
        display_name="Weighted Ball Hyperextension",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.LOWER_BACK,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS],
        instructions="""['To begin, lie down on an exercise ball with your torso pressing against the ball and parallel to the floor. The ball of your feet should be pressed against the floor to help keep you balanced. Place a weighted plate under your chin or behind your neck. This is the starting position.', 'Slowly raise your torso up by bending at the waist and lower back. Remember to exhale during this movement.', 'Hold the contraction on your lower back for a second and lower your torso back down to the starting position while inhaling.', 'Repeat for the recommended amount of repetitions prescribed in your program.']""",
        images=['Weighted_Ball_Hyperextension/0.jpg', 'Weighted_Ball_Hyperextension/1.jpg'],
    ),
}
