from exercises.base import ExerciseDefinition
from enums import MuscleGroup, EquipmentType, MechanicsType, MajorMuscleGroup, ForceType, LevelType, CategoryType

NECK_EXERCISES = {
    "Seated_Head_Harness_Neck_Resistance": ExerciseDefinition(
        id="Seated_Head_Harness_Neck_Resistance",
        display_name="Seated Head Harness Neck Resistance",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.NECK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.OTHER,
        instructions="""['Place a neck strap on the floor at the end of a flat bench. Once you have selected the weights, sit at the end of the flat bench with your feet wider than shoulder width apart from each other. Your toes should be pointed out.', 'Slowly move your torso forward until it is almost parallel with the floor. Using both hands, securely position the neck strap around your head. Tip: Make sure the weights are still lying on the floor to prevent any strain on the neck. Now grab the weight with both hands while elevating your torso back until it is almost perpendicular to the floor. Note: Your head and torso needs to be slightly tilted forward to perform this exercise.', 'Now place both hands on top of your knees. This is the starting position.', 'Slowly lower your neck down until your chin touches the upper part of your chest while breathing in.', 'While exhaling, bring your neck back to the starting position.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Seated_Head_Harness_Neck_Resistance/0.jpg', 'Seated_Head_Harness_Neck_Resistance/1.jpg'],
    ),
    "Isometric_Neck_Exercise_-_Sides": ExerciseDefinition(
        id="Isometric_Neck_Exercise_-_Sides",
        display_name="Isometric Neck Exercise - Sides",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.NECK,
        force=ForceType.STATIC,
        mechanics_type=MechanicsType.ISOLATION,
        instructions="""['With your head and neck in a neutral position (normal position with head erect facing forward), place your left hand on the left side of your head.', 'Now gently push towards the left as you contract the left neck muscles but resisting any movement of your head. Start with slow tension and increase slowly. Keep breathing normally as you execute this contraction.', 'Hold for the recommended number of seconds.', 'Now release the tension slowly.', 'Rest for the recommended amount of time and repeat with your right hand placed on the right side of your head.']""",
        images=['Isometric_Neck_Exercise_-_Sides/0.jpg', 'Isometric_Neck_Exercise_-_Sides/1.jpg'],
    ),
    "Chin_To_Chest_Stretch": ExerciseDefinition(
        id="Chin_To_Chest_Stretch",
        display_name="Chin To Chest Stretch",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.NECK,
        force=ForceType.STATIC,
        secondary_muscles=[MuscleGroup.TRAPS],
        instructions="""['Get into a seated position on the floor.', 'Place both hands at the rear of your head, fingers interlocked, thumbs pointing down and elbows pointing straight ahead. Slowly pull your head down to your chest. Hold for 20-30 seconds.']""",
        images=['Chin_To_Chest_Stretch/0.jpg', 'Chin_To_Chest_Stretch/1.jpg'],
    ),
    "Lying_Face_Down_Plate_Neck_Resistance": ExerciseDefinition(
        id="Lying_Face_Down_Plate_Neck_Resistance",
        display_name="Lying Face Down Plate Neck Resistance",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.NECK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.OTHER,
        instructions="""['Lie face down with your whole body straight on a flat bench while holding a weight plate behind your head. Tip: You will need to position yourself so that your shoulders are slightly above the end of a flat bench in order for the upper chest, neck and face to be off the bench. This will be your starting position.', 'While keeping the plate secure on the back of your head slowly lower your head (as in saying "yes") as you breathe in.', 'Raise your head back up to the starting position in a semi-circular motion as you breathe out. Hold the contraction for a second.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Lying_Face_Down_Plate_Neck_Resistance/0.jpg', 'Lying_Face_Down_Plate_Neck_Resistance/1.jpg'],
    ),
    "Neck-SMR": ExerciseDefinition(
        id="Neck-SMR",
        display_name="Neck-SMR",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.NECK,
        force=ForceType.STATIC,
        equipment_type=EquipmentType.OTHER,
        instructions="""['Using a muscle roller or a rolling pin, place the roller behind your head and against your neck. Make sure that you do not place the roller directly against the spine, but turned slightly so that the roller is pressed against the muscles to either side of the spine. This will be your starting position.', 'Starting at the top of your neck, slowly roll down the muscles of your neck, pausing at points of tension for 10-30 seconds.']""",
        images=['Neck-SMR/0.jpg', 'Neck-SMR/1.jpg'],
    ),
    "Isometric_Neck_Exercise_-_Front_And_Back": ExerciseDefinition(
        id="Isometric_Neck_Exercise_-_Front_And_Back",
        display_name="Isometric Neck Exercise - Front And Back",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.NECK,
        force=ForceType.STATIC,
        mechanics_type=MechanicsType.ISOLATION,
        instructions="""['With your head and neck in a neutral position (normal position with head erect facing forward), place both of your hands on the front side of your head.', 'Now gently push forward as you contract the neck muscles but resisting any movement of your head. Start with slow tension and increase slowly. Keep breathing normally as you execute this contraction.', 'Hold for the recommended number of seconds.', 'Now release the tension slowly.', 'Rest for the recommended amount of time and repeat with your hands placed on the back side of your head.']""",
        images=['Isometric_Neck_Exercise_-_Front_And_Back/0.jpg', 'Isometric_Neck_Exercise_-_Front_And_Back/1.jpg'],
    ),
    "Lying_Face_Up_Plate_Neck_Resistance": ExerciseDefinition(
        id="Lying_Face_Up_Plate_Neck_Resistance",
        display_name="Lying Face Up Plate Neck Resistance",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.NECK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.OTHER,
        instructions="""['Lie face up with your whole body straight on a flat bench while holding a weight plate on top of your forehead. Tip: You will need to position yourself so that your shoulders are slightly above the end of a flat bench in order for the traps, neck and head to be off the bench. This will be your starting position.', 'While keeping the plate secure on your forehead slowly lower your head back in a semi-circular motion as you breathe in.', 'Raise your head back up to the starting position in a semi-circular motion as you breathe out. Hold the contraction for a second.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Lying_Face_Up_Plate_Neck_Resistance/0.jpg', 'Lying_Face_Up_Plate_Neck_Resistance/1.jpg'],
    ),
    "Side_Neck_Stretch": ExerciseDefinition(
        id="Side_Neck_Stretch",
        display_name="Side Neck Stretch",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.NECK,
        force=ForceType.STATIC,
        mechanics_type=MechanicsType.ISOLATION,
        instructions="""['Start with your shoulders relaxed, gently tilt your head towards your shoulder.', 'Assist stretch with a gentle pull on the side of the head.']""",
        images=['Side_Neck_Stretch/0.jpg', 'Side_Neck_Stretch/1.jpg'],
    ),
}
