from exercises.base import ExerciseDefinition
from enums import MuscleGroup, EquipmentType, MechanicsType, MajorMuscleGroup, ForceType, LevelType, CategoryType

TOP_ROPING_EXERCISES = {
    "top_rope_5.2": ExerciseDefinition(
        id="top_rope_5.2",
        display_name="Top Rope 5.2",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TOP_ROPING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['top rope climbing']""",
        images=[],
    ),
    "top_rope_5.3": ExerciseDefinition(
        id="top_rope_5.3",
        display_name="Top Rope 5.3",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TOP_ROPING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['top rope climbing']""",
        images=[],
    ),
    "top_rope_5.4": ExerciseDefinition(
        id="top_rope_5.4",
        display_name="Top Rope 5.4",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TOP_ROPING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['top rope climbing']""",
        images=[],
    ),
    "top_rope_5.5": ExerciseDefinition(
        id="top_rope_5.5",
        display_name="Top Rope 5.5",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TOP_ROPING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['top rope climbing']""",
        images=[],
    ),
    "top_rope_5.6": ExerciseDefinition(
        id="top_rope_5.6",
        display_name="Top Rope 5.6",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TOP_ROPING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['top rope climbing']""",
        images=[],
    ),
    "top_rope_5.7": ExerciseDefinition(
        id="top_rope_5.7",
        display_name="Top Rope 5.7",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TOP_ROPING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['top rope climbing']""",
        images=[],
    ),
    "top_rope_5.8": ExerciseDefinition(
        id="top_rope_5.8",
        display_name="Top Rope 5.8",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TOP_ROPING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['top rope climbing']""",
        images=[],
    ),
    "top_rope_5.9": ExerciseDefinition(
        id="top_rope_5.9",
        display_name="Top Rope 5.9",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TOP_ROPING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['top rope climbing']""",
        images=[],
    ),
    "top_rope_5.10a": ExerciseDefinition(
        id="top_rope_5.10a",
        display_name="Top Rope 5.10a",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TOP_ROPING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['top rope climbing']""",
        images=[],
    ),
    "top_rope_5.10b": ExerciseDefinition(
        id="top_rope_5.10b",
        display_name="Top Rope 5.10b",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TOP_ROPING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['top rope climbing']""",
        images=[],
    ),
    "top_rope_5.10c": ExerciseDefinition(
        id="top_rope_5.10c",
        display_name="Top Rope 5.10c",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TOP_ROPING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['top rope climbing']""",
        images=[],
    ),
    "top_rope_5.10d": ExerciseDefinition(
        id="top_rope_5.10d",
        display_name="Top Rope 5.10d",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TOP_ROPING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['top rope climbing']""",
        images=[],
    ),
    "top_rope_5.11a": ExerciseDefinition(
        id="top_rope_5.11a",
        display_name="Top Rope 5.11a",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TOP_ROPING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['top rope climbing']""",
        images=[],
    ),
    "top_rope_5.11b": ExerciseDefinition(
        id="top_rope_5.11b",
        display_name="Top Rope 5.11b",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TOP_ROPING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['top rope climbing']""",
        images=[],
    ),
    "top_rope_5.11c": ExerciseDefinition(
        id="top_rope_5.11c",
        display_name="Top Rope 5.11c",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TOP_ROPING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['top rope climbing']""",
        images=[],
    ),
    "top_rope_5.11d": ExerciseDefinition(
        id="top_rope_5.11d",
        display_name="Top Rope 5.11d",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TOP_ROPING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['top rope climbing']""",
        images=[],
    ),
    "top_rope_5.12a": ExerciseDefinition(
        id="top_rope_5.12a",
        display_name="Top Rope 5.12a",
        level=LevelType.ADVANCED,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TOP_ROPING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['top rope climbing']""",
        images=[],
    ),
    "top_rope_5.12b": ExerciseDefinition(
        id="top_rope_5.12b",
        display_name="Top Rope 5.12b",
        level=LevelType.ADVANCED,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TOP_ROPING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['top rope climbing']""",
        images=[],
    ),
    "top_rope_5.12c": ExerciseDefinition(
        id="top_rope_5.12c",
        display_name="Top Rope 5.12c",
        level=LevelType.ADVANCED,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TOP_ROPING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['top rope climbing']""",
        images=[],
    ),
    "top_rope_5.12d": ExerciseDefinition(
        id="top_rope_5.12d",
        display_name="Top Rope 5.12d",
        level=LevelType.ADVANCED,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TOP_ROPING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['top rope climbing']""",
        images=[],
    ),
    "top_rope_5.13a": ExerciseDefinition(
        id="top_rope_5.13a",
        display_name="Top Rope 5.13a",
        level=LevelType.ADVANCED,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TOP_ROPING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['top rope climbing']""",
        images=[],
    ),
    "top_rope_5.13b": ExerciseDefinition(
        id="top_rope_5.13b",
        display_name="Top Rope 5.13b",
        level=LevelType.ADVANCED,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TOP_ROPING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['top rope climbing']""",
        images=[],
    ),
    "top_rope_5.13c": ExerciseDefinition(
        id="top_rope_5.13c",
        display_name="Top Rope 5.13c",
        level=LevelType.ADVANCED,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TOP_ROPING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['top rope climbing']""",
        images=[],
    ),
    "top_rope_5.13d": ExerciseDefinition(
        id="top_rope_5.13d",
        display_name="Top Rope 5.13d",
        level=LevelType.ADVANCED,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TOP_ROPING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['top rope climbing']""",
        images=[],
    ),
    "top_rope_5.14a": ExerciseDefinition(
        id="top_rope_5.14a",
        display_name="Top Rope 5.14a",
        level=LevelType.PRO,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TOP_ROPING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['top rope climbing']""",
        images=[],
    ),
    "top_rope_5.14b": ExerciseDefinition(
        id="top_rope_5.14b",
        display_name="Top Rope 5.14b",
        level=LevelType.PRO,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TOP_ROPING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['top rope climbing']""",
        images=[],
    ),
    "top_rope_5.14c": ExerciseDefinition(
        id="top_rope_5.14c",
        display_name="Top Rope 5.14c",
        level=LevelType.PRO,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TOP_ROPING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['top rope climbing']""",
        images=[],
    ),
    "top_rope_5.14d": ExerciseDefinition(
        id="top_rope_5.14d",
        display_name="Top Rope 5.14d",
        level=LevelType.PRO,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TOP_ROPING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['top rope climbing']""",
        images=[],
    ),
    "top_rope_5.15a": ExerciseDefinition(
        id="top_rope_5.15a",
        display_name="Top Rope 5.15a",
        level=LevelType.PRO,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TOP_ROPING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['top rope climbing']""",
        images=[],
    ),
    "top_rope_5.15b": ExerciseDefinition(
        id="top_rope_5.15b",
        display_name="Top Rope 5.15b",
        level=LevelType.PRO,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TOP_ROPING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['top rope climbing']""",
        images=[],
    ),
    "top_rope_5.15c": ExerciseDefinition(
        id="top_rope_5.15c",
        display_name="Top Rope 5.15c",
        level=LevelType.PRO,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TOP_ROPING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['top rope climbing']""",
        images=[],
    ),
    "top_rope_5.15d": ExerciseDefinition(
        id="top_rope_5.15d",
        display_name="Top Rope 5.15d",
        level=LevelType.PRO,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TOP_ROPING,
        major_muscle_group=MajorMuscleGroup.CLIMBING,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['top rope climbing']""",
        images=[],
    ),
}
