from exercises.base import ExerciseDefinition
from enums import MuscleGroup, EquipmentType, MechanicsType, MajorMuscleGroup, ForceType, LevelType, CategoryType

TRAPS_EXERCISES = {
    "Scapular_Pull-Up": ExerciseDefinition(
        id="Scapular_Pull-Up",
        display_name="Scapular Pull-Up",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRAPS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        secondary_muscles=[MuscleGroup.LATS],
        instructions="['Take a pronated grip on a pull-up bar.', 'From a hanging position, raise yourself a few inches without using your arms. Do this by depressing your shoulder girdle in a reverse shrugging motion.', 'Pause at the completion of the movement, and then slowly return to the starting position before performing more repetitions.']",
        images=['Scapular_Pull-Up/0.jpg', 'Scapular_Pull-Up/1.jpg'],
    ),
    "Cable_Shrugs": ExerciseDefinition(
        id="Cable_Shrugs",
        display_name="Cable Shrugs",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRAPS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="['Grasp a cable bar attachment that is attached to a low pulley with a shoulder width or slightly wider overhand (palms facing down) grip.', 'Stand erect close to the pulley with your arms extended in front of you holding the bar. This will be your starting position.', 'Lift the bar by elevating the shoulders as high as possible as you exhale. Hold the contraction at the top for a second. Tip: The arms should remain extended at all times. Refrain from using the biceps to help lift the bar. Only the shoulders should be moving up and down.', 'Lower the bar back to the original position.', 'Repeat for the recommended amount of repetitions.']",
        images=['Cable_Shrugs/0.jpg', 'Cable_Shrugs/1.jpg'],
    ),
    "Clean_Shrug": ExerciseDefinition(
        id="Clean_Shrug",
        display_name="Clean Shrug",
        level=LevelType.BEGINNER,
        category=CategoryType.OLYMPIC_WEIGHTLIFTING,
        muscle_group=MuscleGroup.TRAPS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.FOREARMS, MuscleGroup.SHOULDERS],
        instructions="['Begin with a shoulder width, double overhand or hook grip, with the bar hanging at the mid thigh position. Your back should be straight and inclined slightly forward.', 'Shrug your shoulders towards your ears. While this exercise can usually by loaded with heavier weight than a clean, avoid overloading to the point that the execution slows down.']",
        images=['Clean_Shrug/0.jpg', 'Clean_Shrug/1.jpg'],
    ),
    "Smith_Machine_Upright_Row": ExerciseDefinition(
        id="Smith_Machine_Upright_Row",
        display_name="Smith Machine Upright Row",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRAPS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.MACHINE,
        secondary_muscles=[MuscleGroup.BICEPS, MuscleGroup.SHOULDERS],
        instructions="['To begin, set the bar on the smith machine to a height that is around the middle of your thighs. Once the correct height is chosen and the bar is loaded, grasp the bar using a pronated (palms forward) grip that is shoulder width apart. You may need some wrist wraps if using a significant amount of weight.', 'Lift the barbell up and fully extend your arms with your back straight. There should be a slight bend at the elbows. This is the starting position.', 'Use your side shoulders to lift the bar as you exhale. The bar should be close to the body as you move it up. Continue to lift it until it nearly touches your chin. Tip: Your elbows should drive the motion. As you lift the bar, your elbows should always be higher than your forearms. Also, keep your torso stationary and pause for a second at the top of the movement.', 'Lower the bar back down slowly to the starting position. Inhale as you perform this portion of the movement.', 'Repeat for the recommended amount of repetitions.']",
        images=['Smith_Machine_Upright_Row/0.jpg', 'Smith_Machine_Upright_Row/1.jpg'],
    ),
    "Barbell_Shrug_Behind_The_Back": ExerciseDefinition(
        id="Barbell_Shrug_Behind_The_Back",
        display_name="Barbell Shrug Behind The Back",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRAPS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.FOREARMS],
        instructions="['Stand up straight with your feet at shoulder width as you hold a barbell with both hands behind your back using a pronated grip (palms facing back). Tip: Your hands should be a little wider than shoulder width apart. You can use wrist wraps for this exercise for better grip. This will be your starting position.', 'Raise your shoulders up as far as you can go as you breathe out and hold the contraction for a second. Tip: Refrain from trying to lift the barbell by using your biceps. The arms should remain stretched out at all times.', 'Slowly return to the starting position as you breathe in.', 'Repeat for the recommended amount of repetitions.']",
        images=['Barbell_Shrug_Behind_The_Back/0.jpg', 'Barbell_Shrug_Behind_The_Back/1.jpg'],
    ),
    "Standing_Dumbbell_Upright_Row": ExerciseDefinition(
        id="Standing_Dumbbell_Upright_Row",
        display_name="Standing Dumbbell Upright Row",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRAPS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.DUMBBELL,
        secondary_muscles=[MuscleGroup.BICEPS, MuscleGroup.SHOULDERS],
        instructions="['Grasp a dumbbell in each hand with a pronated (palms forward) grip that is slightly less than shoulder width. The dumbbells should be resting on top of your thighs. Your arms should be extended with a slight bend at the elbows and your back should be straight. This will be your starting position.', 'Use your side shoulders to lift the dumbbells as you exhale. The dumbbells should be close to the body as you move it up and the elbows should drive the motion. Continue to lift them until they nearly touch your chin. Tip: Your elbows should drive the motion. As you lift the dumbbells, your elbows should always be higher than your forearms. Also, keep your torso stationary and pause for a second at the top of the movement.', 'Lower the dumbbells back down slowly to the starting position. Inhale as you perform this portion of the movement.', 'Repeat for the recommended amount of repetitions.']",
        images=['Standing_Dumbbell_Upright_Row/0.jpg', 'Standing_Dumbbell_Upright_Row/1.jpg'],
    ),
    "Upright_Cable_Row": ExerciseDefinition(
        id="Upright_Cable_Row",
        display_name="Upright Cable Row",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRAPS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.CABLE,
        secondary_muscles=[MuscleGroup.SHOULDERS],
        instructions="['Grasp a straight bar cable attachment that is attached to a low pulley with a pronated (palms facing your thighs) grip that is slightly less than shoulder width. The bar should be resting on top of your thighs. Your arms should be extended with a slight bend at the elbows and your back should be straight. This will be your starting position.', 'Use your side shoulders to lift the cable bar as you exhale. The bar should be close to the body as you move it up. Continue to lift it until it nearly touches your chin. Tip: Your elbows should drive the motion. As you lift the bar, your elbows should always be higher than your forearms. Also, keep your torso stationary and pause for a second at the top of the movement.', 'Lower the bar back down slowly to the starting position. Inhale as you perform this portion of the movement.', 'Repeat for the recommended amount of repetitions.']",
        images=['Upright_Cable_Row/0.jpg', 'Upright_Cable_Row/1.jpg'],
    ),
    "Smith_Machine_Behind_the_Back_Shrug": ExerciseDefinition(
        id="Smith_Machine_Behind_the_Back_Shrug",
        display_name="Smith Machine Behind the Back Shrug",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRAPS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.MACHINE,
        secondary_muscles=[MuscleGroup.SHOULDERS],
        instructions="['With the bar at thigh level, load an appropriate weight.', 'Stand with the bar behind you, taking a shoulder-width, pronated grip on the bar and unhook the weight. You should be standing up straight with your head and chest up and your arms extended. This will be your starting position.', 'Initiate the movement by shrugging your shoulders straight up. Do not flex the arms or wrist during the movement.', 'After a brief pause return the weight to the starting position.', 'Repeat for the desired number of repetitions before engaging the hooks to rack the weight.']",
        images=['Smith_Machine_Behind_the_Back_Shrug/0.jpg', 'Smith_Machine_Behind_the_Back_Shrug/1.jpg'],
    ),
    "Calf-Machine_Shoulder_Shrug": ExerciseDefinition(
        id="Calf-Machine_Shoulder_Shrug",
        display_name="Calf-Machine Shoulder Shrug",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRAPS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.MACHINE,
        instructions="['Position yourself on the calf machine so that the shoulder pads are above your shoulders. Your torso should be straight with the arms extended normally by your side. This will be your starting position.', 'Raise your shoulders up towards your ears as you exhale and hold the contraction for a full second.', 'Slowly return to the starting position as you inhale.', 'Repeat for the recommended amount of repetitions.']",
        images=['Calf-Machine_Shoulder_Shrug/0.jpg', 'Calf-Machine_Shoulder_Shrug/1.jpg'],
    ),
    "Upright_Row_-_With_Bands": ExerciseDefinition(
        id="Upright_Row_-_With_Bands",
        display_name="Upright Row - With Bands",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRAPS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.SHOULDERS],
        instructions="""["To begin, stand on an exercise band so that tension begins at arm's length. Grasp the handles using a pronated (palms facing your thighs) grip that is slightly less than shoulder width. The handles should be resting on top of your thighs. Your arms should be extended with a slight bend at the elbows and your back should be straight. This will be your starting position.", 'Use your side shoulders to lift the handles as you exhale. The handles should be close to the body as you move them up. Continue to lift the handles until they nearly touches your chin. Tip: Your elbows should drive the motion. As you lift the handles, your elbows should always be higher than your forearms. Also, keep your torso stationary and pause for a second at the top of the movement.', 'Lower the handles back down slowly to the starting position. Inhale as you perform this portion of the movement.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Upright_Row_-_With_Bands/0.jpg', 'Upright_Row_-_With_Bands/1.jpg'],
    ),
    "Leverage_Shrug": ExerciseDefinition(
        id="Leverage_Shrug",
        display_name="Leverage Shrug",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRAPS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.MACHINE,
        secondary_muscles=[MuscleGroup.FOREARMS],
        instructions="['Load the pins to an appropriate weight. Position yourself directly between the handles.', 'Grasp the top handles with a comfortable grip, and then lower your hips as you take a breath. Look forward with your head and keep your chest up.', 'Drive through the floor with your heels, extending your hips and knees as you rise to a standing position. Keep your arms straight throughout the movement, finishing with your shoulders back. This will be your starting position.', 'Raise the weight by shrugging the shoulders towards your ears, moving straight up and down.', 'Pause at the top of the motion, and then return the weight to the starting position.']",
        images=['Leverage_Shrug/0.jpg', 'Leverage_Shrug/1.jpg'],
    ),
    "Dumbbell_Shrug": ExerciseDefinition(
        id="Dumbbell_Shrug",
        display_name="Dumbbell Shrug",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRAPS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        instructions="['Stand erect with a dumbbell on each hand (palms facing your torso), arms extended on the sides.', 'Lift the dumbbells by elevating the shoulders as high as possible while you exhale. Hold the contraction at the top for a second. Tip: The arms should remain extended at all times. Refrain from using the biceps to help lift the dumbbells. Only the shoulders should be moving up and down.', 'Lower the dumbbells back to the original position.', 'Repeat for the recommended amount of repetitions.']",
        images=['Dumbbell_Shrug/0.jpg', 'Dumbbell_Shrug/1.jpg'],
    ),
    "Barbell_Shrug": ExerciseDefinition(
        id="Barbell_Shrug",
        display_name="Barbell Shrug",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRAPS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.BARBELL,
        instructions="['Stand up straight with your feet at shoulder width as you hold a barbell with both hands in front of you using a pronated grip (palms facing the thighs). Tip: Your hands should be a little wider than shoulder width apart. You can use wrist wraps for this exercise for a better grip. This will be your starting position.', 'Raise your shoulders up as far as you can go as you breathe out and hold the contraction for a second. Tip: Refrain from trying to lift the barbell by using your biceps.', 'Slowly return to the starting position as you breathe in.', 'Repeat for the recommended amount of repetitions.']",
        images=['Barbell_Shrug/0.jpg', 'Barbell_Shrug/1.jpg'],
    ),
    "Snatch_Shrug": ExerciseDefinition(
        id="Snatch_Shrug",
        display_name="Snatch Shrug",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.OLYMPIC_WEIGHTLIFTING,
        muscle_group=MuscleGroup.TRAPS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.FOREARMS, MuscleGroup.SHOULDERS],
        instructions="['Begin with a wide grip, with the bar hanging at the mid thigh position. You can use a hook or overhand grip. Your back should be straight and inclined slightly forward.', 'Shrug your shoulders towards your ears. While this exercise can usually by loaded with heavier weight than a snatch, avoid overloading to the point that the execution slows down.']",
        images=['Snatch_Shrug/0.jpg', 'Snatch_Shrug/1.jpg'],
    ),
    "Kettlebell_Sumo_High_Pull": ExerciseDefinition(
        id="Kettlebell_Sumo_High_Pull",
        display_name="Kettlebell Sumo High Pull",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRAPS,
        major_muscle_group=MajorMuscleGroup.BACK,
        force=ForceType.PULL,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.ADDUCTORS, MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS, MuscleGroup.QUADS, MuscleGroup.SHOULDERS],
        instructions="['Place a kettlebell on the ground between your feet. Position your feet in a wide stance, and grasp the kettlebell with two hands. Set your hips back as far as possible, with your knees bent. Keep your chest and head up. This will be your starting position.', 'Begin by extending the hips and knees, simultaneously pulling the kettlebell to your shoulders, raising your elbows as you do so. Reverse the motion to return to the starting position.']",
        images=['Kettlebell_Sumo_High_Pull/0.jpg', 'Kettlebell_Sumo_High_Pull/1.jpg'],
    ),
}
