from exercises.base import ExerciseDefinition
from enums import MuscleGroup, EquipmentType, MechanicsType, MajorMuscleGroup, ForceType, LevelType, CategoryType

TRICEPS_EXERCISES = {
    "Cable_Rope_Overhead_Triceps_Extension": ExerciseDefinition(
        id="Cable_Rope_Overhead_Triceps_Extension",
        display_name="Cable Rope Overhead Triceps Extension",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['Attach a rope to the bottom pulley of the pulley machine.', 'Grasping the rope with both hands, extend your arms with your hands directly above your head using a neutral grip (palms facing each other). Your elbows should be in close to your head and the arms should be perpendicular to the floor with the knuckles aimed at the ceiling. This will be your starting position.', 'Slowly lower the rope behind your head as you hold the upper arms stationary. Inhale as you perform this movement and pause when your triceps are fully stretched.', 'Return to the starting position by flexing your triceps as you breathe out.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Cable_Rope_Overhead_Triceps_Extension/0.jpg', 'Cable_Rope_Overhead_Triceps_Extension/1.jpg'],
    ),
    "Triceps_Pushdown_-_Rope_Attachment": ExerciseDefinition(
        id="Triceps_Pushdown_-_Rope_Attachment",
        display_name="Triceps Pushdown - Rope Attachment",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['Attach a rope attachment to a high pulley and grab with a neutral grip (palms facing each other).', 'Standing upright with the torso straight and a very small inclination forward, bring the upper arms close to your body and perpendicular to the floor. The forearms should be pointing up towards the pulley as they hold the rope with the palms facing each other. This is your starting position.', 'Using the triceps, bring the rope down as you bring each side of the rope to the side of your thighs. At the end of the movement the arms are fully extended and perpendicular to the floor. The upper arms should always remain stationary next to your torso and only the forearms should move. Exhale as you perform this movement.', 'After holding for a second, at the contracted position, bring the rope slowly up to the starting point. Breathe in as you perform this step.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Triceps_Pushdown_-_Rope_Attachment/0.jpg', 'Triceps_Pushdown_-_Rope_Attachment/1.jpg'],
    ),
    "Overhead_Triceps": ExerciseDefinition(
        id="Overhead_Triceps",
        display_name="Overhead Triceps",
        level=LevelType.EXPERT,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.STATIC,
        secondary_muscles=[MuscleGroup.LATS],
        instructions="""['Sit upright on the floor with your partner behind you. Raise one arm straight up, and flex the elbow, attempting to touch your hand to your back. Your parner should hold your elbow and wrist. This will be your starting position.', 'Attempt to extend the arm straight into the air as your partner prevents you from doing actually doing so.', 'After 10-20 seconds, relax the arm and allow your partner to further stretch the tricep by applying gentle pressure to the wrist. Hold for 10-20 seconds, and then switch sides.']""",
        images=['Overhead_Triceps/0.jpg', 'Overhead_Triceps/1.jpg'],
    ),
    "Close-Grip_Barbell_Bench_Press": ExerciseDefinition(
        id="Close-Grip_Barbell_Bench_Press",
        display_name="Close-Grip Barbell Bench Press",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
        instructions="""['Lie back on a flat bench. Using a close grip (around shoulder width), lift the bar from the rack and hold it straight over you with your arms locked. This will be your starting position.', 'As you breathe in, come down slowly until you feel the bar on your middle chest. Tip: Make sure that - as opposed to a regular bench press - you keep the elbows close to the torso at all times in order to maximize triceps involvement.', 'After a second pause, bring the bar back to the starting position as you breathe out and push the bar using your triceps muscles. Lock your arms in the contracted position, hold for a second and then start coming down slowly again. Tip: It should take at least twice as long to go down than to come up.', 'Repeat the movement for the prescribed amount of repetitions.', 'When you are done, place the bar back in the rack.']""",
        images=['Close-Grip_Barbell_Bench_Press/0.jpg', 'Close-Grip_Barbell_Bench_Press/1.jpg'],
    ),
    "Decline_EZ_Bar_Triceps_Extension": ExerciseDefinition(
        id="Decline_EZ_Bar_Triceps_Extension",
        display_name="Decline EZ Bar Triceps Extension",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.BARBELL,
        instructions="""['Secure your legs at the end of the decline bench and slowly lay down on the bench.', 'Using a close grip (a grip that is slightly less than shoulder width), lift the EZ bar from the rack and hold it straight over you with your arms locked and elbows in. The arms should be perpendicular to the floor. This will be your starting position. Tip: In order to protect your rotator cuff, it is best if you have a spotter help you lift the barbell off the rack.', 'As you breathe in and you keep the upper arms stationary, bring the bar down slowly by moving your forearms in a semicircular motion towards you until you feel the bar slightly touch your forehead. Breathe in as you perform this portion of the movement.', 'Lift the bar back to the starting position by contracting the triceps and exhaling.', 'Repeat until the recommended amount of repetitions is performed.']""",
        images=['Decline_EZ_Bar_Triceps_Extension/0.jpg', 'Decline_EZ_Bar_Triceps_Extension/1.jpg'],
    ),
    "Supine_Chest_Throw": ExerciseDefinition(
        id="Supine_Chest_Throw",
        display_name="Supine Chest Throw",
        level=LevelType.BEGINNER,
        category=CategoryType.PLYOMETRICS,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.MEDICINE_BALL,
        secondary_muscles=[MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
        instructions="""['This drill is great for chest passes when you lack a partner or a wall of sufficient strength. Lay on the ground on your back with your knees bent.', 'Begin with the ball on your chest, held with both hands on the bottom.', 'Explode up, extending through the elbow to throw the ball directly above you as high as possible.', 'Catch the ball with both hands as it comes down.']""",
        images=['Supine_Chest_Throw/0.jpg', 'Supine_Chest_Throw/1.jpg'],
    ),
    "Kneeling_Cable_Triceps_Extension": ExerciseDefinition(
        id="Kneeling_Cable_Triceps_Extension",
        display_name="Kneeling Cable Triceps Extension",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['Place a bench sideways in front of a high pulley machine.', 'Hold a straight bar attachment above your head with your hands about 6 inches apart with your palms facing down.', 'Face away from the machine and kneel.', 'Place your head and the back of your upper arms on the bench. Your elbows should be bent with the forearms pointing towards the high pulley. This will be your starting position.', 'While keeping your upper arms close to your head at all times with the elbows in, press the bar out in a semicircular motion until the elbows are locked and your arms are parallel to the floor. Contract the triceps hard and keep this position for a second. Exhale as you perform this movement.', 'Slowly return to the starting position as you breathe in.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Kneeling_Cable_Triceps_Extension/0.jpg', 'Kneeling_Cable_Triceps_Extension/1.jpg'],
    ),
    "Seated_Triceps_Press": ExerciseDefinition(
        id="Seated_Triceps_Press",
        display_name="Seated Triceps Press",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        instructions="""["Sit down on a bench with back support and grasp a dumbbell with both hands and hold it overhead at arm's length. Tip: a better way is to have somebody hand it to you especially if it is very heavy. The resistance should be resting in the palms of your hands with your thumbs around it. The palm of the hand should be facing inward. This will be your starting position.", 'Keeping your upper arms close to your head (elbows in) and perpendicular to the floor, lower the resistance in a semi-circular motion behind your head until your forearms touch your biceps. Tip: The upper arms should remain stationary and only the forearms should move. Breathe in as you perform this step.', 'Go back to the starting position by using the triceps to raise the dumbbell. Breathe out as you perform this step.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Seated_Triceps_Press/0.jpg', 'Seated_Triceps_Press/1.jpg'],
    ),
    "Reverse_Grip_Triceps_Pushdown": ExerciseDefinition(
        id="Reverse_Grip_Triceps_Pushdown",
        display_name="Reverse Grip Triceps Pushdown",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['Start by setting a bar attachment (straight or e-z) on a high pulley machine.', 'Facing the bar attachment, grab it with the palms facing up (supinated grip) at shoulder width. Lower the bar by using your lats until your arms are fully extended by your sides. Tip: Elbows should be in by your sides and your feet should be shoulder width apart from each other. This is the starting position.', 'Slowly elevate the bar attachment up as you inhale so it is aligned with your chest. Only the forearms should move and the elbows/upper arms should be stationary by your side at all times.', 'Then begin to lower the cable bar back down to the original staring position while exhaling and contracting the triceps hard.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Reverse_Grip_Triceps_Pushdown/0.jpg', 'Reverse_Grip_Triceps_Pushdown/1.jpg'],
    ),
    "Dumbbell_Floor_Press": ExerciseDefinition(
        id="Dumbbell_Floor_Press",
        display_name="Dumbbell Floor Press",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.POWERLIFTING,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.DUMBBELL,
        secondary_muscles=[MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
        instructions="""['Lay on the floor holding dumbbells in your hands. Your knees can be bent. Begin with the weights fully extended above you.', 'Lower the weights until your upper arm comes in contact with the floor. You can tuck your elbows to emphasize triceps size and strength, or to focus on your chest angle your arms to the side.', 'Pause at the bottom, and then bring the weight together at the top by extending through the elbows.']""",
        images=['Dumbbell_Floor_Press/0.jpg', 'Dumbbell_Floor_Press/1.jpg'],
    ),
    "Sled_Overhead_Triceps_Extension": ExerciseDefinition(
        id="Sled_Overhead_Triceps_Extension",
        display_name="Sled Overhead Triceps Extension",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.OTHER,
        instructions="""['Attach dual handles to a sled using a chain or rope. Load the sled to an appropriate load.', 'Facing away from the sled, step away until there is tension in the line. Raise your hands above your head, keeping them together, palms facing each other. Your elbows should be pointed upward with the elbows flexed. This will be your starting position.', 'Extend through the elbow to straighten the arm. Ensure that your upper arm stays in position to isolate the triceps.', 'Upon full extension, step forward to take the slack out of the line. You may keep your feet staggered for more stability.']""",
        images=['Sled_Overhead_Triceps_Extension/0.jpg', 'Sled_Overhead_Triceps_Extension/1.jpg'],
    ),
    "Cable_One_Arm_Tricep_Extension": ExerciseDefinition(
        id="Cable_One_Arm_Tricep_Extension",
        display_name="Cable One Arm Tricep Extension",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['With your right hand, grasp a single handle attached to the high-cable pulley using a supinated (underhand; palms facing up) grip. You should be standing directly in front of the weight stack.', 'Now pull the handle down so that your upper arm and elbow are locked in to the side of your body. Your upper arm and forearm should form an acute angle (less than 90-degrees). You can keep the other arm by the waist and you can have one leg in front of you and the other one back for better balance. This will be your starting position.', 'As you contract the triceps, move the single handle attachment down to your side until your arm is straight. Breathe out as you perform this movement. Tip: Only the forearms should move. Your upper arms should remain stationary at all times.', 'Squeeze the triceps and hold for a second in this contracted position.', 'Slowly return the handle to the starting position.', 'Repeat for the recommended amount of repetitions and then perform the same movement with the other arm.']""",
        images=['Cable_One_Arm_Tricep_Extension/0.jpg', 'Cable_One_Arm_Tricep_Extension/1.jpg'],
    ),
    "Standing_Towel_Triceps_Extension": ExerciseDefinition(
        id="Standing_Towel_Triceps_Extension",
        display_name="Standing Towel Triceps Extension",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        instructions="""['To begin, stand up with both arms fully extended above the head holding one end of a towel with both hands. Your elbows should be in and the arms perpendicular to the floor with the palms facing each other while your feet should be shoulder width apart from each other. This is the starting position.', 'Now communicate with your partner so that he/she can grip the other side of the towel to apply resistance. Keeping your upper arms close to your head (elbows in) and perpendicular to the floor, lower the resistance in a semicircular motion behind your head until your forearms touch your biceps. Tip: The upper arms should remain stationary and only the forearms should move. Breathe in as you perform this step.', 'Go back to the starting position by using the triceps to raise the towel. Breathe out as you perform this step.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Standing_Towel_Triceps_Extension/0.jpg', 'Standing_Towel_Triceps_Extension/1.jpg'],
    ),
    "Triceps_Stretch": ExerciseDefinition(
        id="Triceps_Stretch",
        display_name="Triceps Stretch",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.STATIC,
        mechanics_type=MechanicsType.ISOLATION,
        secondary_muscles=[MuscleGroup.LATS],
        instructions="""['Reach your hand behind your head, grasp your elbow and gently pull. Hold for 10 to 20 seconds, then switch sides.']""",
        images=['Triceps_Stretch/0.jpg', 'Triceps_Stretch/1.jpg'],
    ),
    "Standing_Bent-Over_One-Arm_Dumbbell_Triceps_Extension": ExerciseDefinition(
        id="Standing_Bent-Over_One-Arm_Dumbbell_Triceps_Extension",
        display_name="Standing Bent-Over One-Arm Dumbbell Triceps Extension",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        secondary_muscles=[MuscleGroup.SHOULDERS],
        instructions="""['With a dumbbell in one hand and the palm facing your torso, bend your knees slightly and bring your torso forward, by bending at the waist, while keeping the back straight until it is almost parallel to the floor. Make sure that you keep the head up.', 'The upper arm should be close to the torso and parallel to the floor while the forearm is pointing towards the floor as the hand holds the weight. Tip: There should be a 90-degree angle between the forearm and the upper arm. This is your starting position.', 'Keeping the upper arms stationary, use the triceps to lift the weights as you exhale until the forearms are parallel to the floor and the whole arm is extended. Like many other arm exercises, only the forearm moves.', 'After a second contraction at the top, slowly lower the dumbbell back to the starting position as you inhale.', 'Repeat the movement for the prescribed amount of repetitions.', 'Switch arms and repeat the exercise.']""",
        images=['Standing_Bent-Over_One-Arm_Dumbbell_Triceps_Extension/0.jpg', 'Standing_Bent-Over_One-Arm_Dumbbell_Triceps_Extension/1.jpg'],
    ),
    "Lying_Triceps_Press": ExerciseDefinition(
        id="Lying_Triceps_Press",
        display_name="Lying Triceps Press",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        instructions="""['Lie on a flat bench with either an e-z bar (my preference) or a straight bar placed on the floor behind your head and your feet on the floor.', 'Grab the bar behind you, using a medium overhand (pronated) grip, and raise the bar in front of you at arms length. Tip: The arms should be perpendicular to the torso and the floor. The elbows should be tucked in. This is the starting position.', 'As you breathe in, slowly lower the weight until the bar lightly touches your forehead while keeping the upper arms and elbows stationary.', 'At that point, use the triceps to bring the weight back up to the starting position as you breathe out.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Lying_Triceps_Press/0.jpg', 'Lying_Triceps_Press/1.jpg'],
    ),
    "One_Arm_Supinated_Dumbbell_Triceps_Extension": ExerciseDefinition(
        id="One_Arm_Supinated_Dumbbell_Triceps_Extension",
        display_name="One Arm Supinated Dumbbell Triceps Extension",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        instructions="""['Lie flat on a bench while holding a dumbbell at arms length. Your arm should be perpendicular to your body. The palm of your hand should be facing towards your face as a supinated grip is required to perform this exercise.', 'Place your non lifting hand on your bicep for support.', 'Slowly begin to lower the dumbbell down as you breathe in.', 'Then, begin lifting the dumbbell upward as you contract the triceps. Remember to breathe out during the concentric (lifting part of the exercise).', 'Repeat until you have performed your set repetitions.', 'Switch arms and repeat the movement.', 'Switch arms again and repeat the movement.']""",
        images=['One_Arm_Supinated_Dumbbell_Triceps_Extension/0.jpg', 'One_Arm_Supinated_Dumbbell_Triceps_Extension/1.jpg'],
    ),
    "Reverse_Band_Bench_Press": ExerciseDefinition(
        id="Reverse_Band_Bench_Press",
        display_name="Reverse Band Bench Press",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.POWERLIFTING,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.CHEST, MuscleGroup.FOREARMS, MuscleGroup.LATS, MuscleGroup.SHOULDERS],
        instructions="""['Position a bench inside a power rack, with the bar set to the correct height. Begin by anchoring bands either to band pegs or to the top of the rack. Ensure that you will be position properly under the bands. Attach the other end to the barbell.', 'Lie on the bench, tuck your feet underneath you and arch your back. Using the bar to help support your weight, lift your shoulder off the bench and retract them, squeezing the shoulder blades together. Use your feet to drive your traps into the bench. Maintain this tight body position throughout the movement. However wide your grip, it should cover the ring on the bar.', 'Pull the bar out of the rack without protracting your shoulders. Focus on squeezing the bar and trying to pull it apart. Lower the bar to your lower chest or upper stomach. The bar, wrist, and elbow should stay in line at all times.', 'Pause when the barbell touches your torso, and then drive the bar up with as much force as possible. The elbows should be tucked in until lockout.']""",
        images=['Reverse_Band_Bench_Press/0.jpg', 'Reverse_Band_Bench_Press/1.jpg'],
    ),
    "Parallel_Bar_Dip": ExerciseDefinition(
        id="Parallel_Bar_Dip",
        display_name="Parallel Bar Dip",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.OTHER,
        secondary_muscles=[MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
        instructions="""['Stand between a set of parallel bars. Place a hand on each bar, and then take a small jump to help you get into the starting position with your arms locked out.', 'Begin by flexing the elbow, lowering your body until your arms break 90 degrees. Avoid swinging, and maintain good posture throughout the descent.', 'Reverse the motion by extending the elbow, pushing yourself back up into the starting position.', 'Repeat for the desired number of repetitions.']""",
        images=['Parallel_Bar_Dip/0.jpg', 'Parallel_Bar_Dip/1.jpg'],
    ),
    "Standing_Bent-Over_Two-Arm_Dumbbell_Triceps_Extension": ExerciseDefinition(
        id="Standing_Bent-Over_Two-Arm_Dumbbell_Triceps_Extension",
        display_name="Standing Bent-Over Two-Arm Dumbbell Triceps Extension",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        instructions="""['With a dumbbell in each hand and the palms facing your torso, bend your knees slightly and bring your torso forward, by bending at the waist, while keeping the back straight until it is almost parallel to the floor. Make sure that you keep the head up. The upper arms should be close to the torso and parallel to the floor while the forearms are pointing towards the floor as the hands hold the weights. Tip: There should be a 90-degree angle between the forearms and the upper arm. This is your starting position.', 'Keeping the upper arms stationary, use the triceps to lift the weights as you exhale until the forearms are parallel to the floor and the whole arms are extended. Like many other arm exercises, only the forearm moves.', 'After a second contraction at the top, slowly lower the dumbbells back to their starting position as you inhale.', 'Repeat the movement for the prescribed amount of repetitions.']""",
        images=['Standing_Bent-Over_Two-Arm_Dumbbell_Triceps_Extension/0.jpg', 'Standing_Bent-Over_Two-Arm_Dumbbell_Triceps_Extension/1.jpg'],
    ),
    "Standing_Overhead_Barbell_Triceps_Extension": ExerciseDefinition(
        id="Standing_Overhead_Barbell_Triceps_Extension",
        display_name="Standing Overhead Barbell Triceps Extension",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.SHOULDERS],
        instructions="""['To begin, stand up holding a barbell or e-z bar using a pronated grip (palms facing forward) with your hands closer than shoulder width apart from each other. Your feet should be about shoulder width apart.', 'Now elevate the barbell above your head until your arms are fully extended. Keep your elbows in. This will be your starting position.', 'Keeping your upper arms close to your head and elbows in, perpendicular to the floor, lower the resistance in a semicircular motion behind your head until your forearms touch your biceps. Tip: The upper arms should remain stationary and only the forearms should move. Breathe in as you perform this step.', 'Go back to the starting position by using the triceps to raise the barbell. Breathe out as you perform this step.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Standing_Overhead_Barbell_Triceps_Extension/0.jpg', 'Standing_Overhead_Barbell_Triceps_Extension/1.jpg'],
    ),
    "Standing_Low-Pulley_One-Arm_Triceps_Extension": ExerciseDefinition(
        id="Standing_Low-Pulley_One-Arm_Triceps_Extension",
        display_name="Standing Low-Pulley One-Arm Triceps Extension",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        secondary_muscles=[MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
        instructions="""['Grab a single handle with your left arm next to the low pulley machine. Turn away from the machine keeping the handle to the side of your body with your arm fully extended. Now use both hands to elevate the single handle directly above the head with the palm facing forward. Keep your upper arm completely vertical (perpendicular to the floor) and put your right hand on your left elbow to help keep it steady. This is the starting position.', 'Keeping your upper arms close to your head (elbows in) and perpendicular to the floor, lower the resistance in a semicircular motion behind your head until your forearms touch your biceps. Tip: The upper arms should remain stationary and only the forearms should move. Breathe in as you perform this step.', 'Go back to the starting position by using the triceps to raise the single handle. Breathe out as you perform this step.', 'Repeat for the recommended amount of repetitions.', 'Switch arms and repeat the exercise.']""",
        images=['Standing_Low-Pulley_One-Arm_Triceps_Extension/0.jpg', 'Standing_Low-Pulley_One-Arm_Triceps_Extension/1.jpg'],
    ),
    "Floor_Press_with_Chains": ExerciseDefinition(
        id="Floor_Press_with_Chains",
        display_name="Floor Press with Chains",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.POWERLIFTING,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
        instructions="""['Adjust the j-hooks so they are at the appropriate height to rack the bar. For this exercise, drape the chains directly over the end of the bar, trying to keep the ends away from the plates.', 'Begin lying on the floor with your head near the end of a power rack. Keeping your shoulder blades pulled together, pull the bar off of the hooks.', 'Lower the bar towards the bottom of your chest or upper stomach, squeezing the bar and attempting to pull it apart as you do so. Ensure that you tuck your elbows throughout the movement. Lower the bar until your upper arm contacts the ground and pause, preventing any slamming or bouncing of the weight.', 'Press the bar back up as fast as you can, keeping the bar, your wrists, and elbows in line as you do so.']""",
        images=['Floor_Press_with_Chains/0.jpg', 'Floor_Press_with_Chains/1.jpg'],
    ),
    "Bench_Dips": ExerciseDefinition(
        id="Bench_Dips",
        display_name="Bench Dips",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
        instructions="""['For this exercise you will need to place a bench behind your back. With the bench perpendicular to your body, and while looking away from it, hold on to the bench on its edge with the hands fully extended, separated at shoulder width. The legs will be extended forward, bent at the waist and perpendicular to your torso. This will be your starting position.', 'Slowly lower your body as you inhale by bending at the elbows until you lower yourself far enough to where there is an angle slightly smaller than 90 degrees between the upper arm and the forearm. Tip: Keep the elbows as close as possible throughout the movement. Forearms should always be pointing down.', 'Using your triceps to bring your torso up again, lift yourself back to the starting position.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Bench_Dips/0.jpg', 'Bench_Dips/1.jpg'],
    ),
    "Dumbbell_Tricep_Extension_-Pronated_Grip": ExerciseDefinition(
        id="Dumbbell_Tricep_Extension_-Pronated_Grip",
        display_name="Dumbbell Tricep Extension -Pronated Grip",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        instructions="""['Lie down on a flat bench holding two dumbbells directly above your shoulders. Your arms should be fully extended and form a 90 degree angle from your torso and the floor.', 'The palms of your hands should be facing forward, and your elbows should be tucked in. This will be your starting position.', 'Now, inhale and slowly lower the dumbbells until they are near your ears. Be sure to keep your upper arms stationary and your elbows tucked in.', 'Then, exhale and use your triceps to return the weight to the starting position.']""",
        images=['Dumbbell_Tricep_Extension_-Pronated_Grip/0.jpg', 'Dumbbell_Tricep_Extension_-Pronated_Grip/1.jpg'],
    ),
    "Lying_Close-Grip_Barbell_Triceps_Press_To_Chin": ExerciseDefinition(
        id="Lying_Close-Grip_Barbell_Triceps_Press_To_Chin",
        display_name="Lying Close-Grip Barbell Triceps Press To Chin",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        instructions="""['While holding a barbell or EZ Curl bar with a pronated grip (palms facing forward), lie on your back on a flat bench with your head off the end of the bench. Tip: If you are holding a barbell grab it using a shoulder-width grip and if you are using an E-Z Bar grab it on the inner handles.', 'Extend your arms in front of you as you hold the barbell over your chest. The arms should be perpendicular to your torso (90-degree angle). This will be your starting position.', 'As you inhale, lower the bar in a semi-circular motion by bending at the elbows and while keeping the upper arm stationary and elbows in. Keep lowering the bar until it lightly touches your chin.', 'As you exhale bring the bar back up to the starting position by pushing the bar up in a semi-circular motion. Contract the triceps hard at the top of the movement for a second. Tip: Again, only the forearms should move. The upper arms should remain stationary at all times.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Lying_Close-Grip_Barbell_Triceps_Press_To_Chin/0.jpg', 'Lying_Close-Grip_Barbell_Triceps_Press_To_Chin/1.jpg'],
    ),
    "Standing_One-Arm_Dumbbell_Triceps_Extension": ExerciseDefinition(
        id="Standing_One-Arm_Dumbbell_Triceps_Extension",
        display_name="Standing One-Arm Dumbbell Triceps Extension",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        secondary_muscles=[MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
        instructions="""['To begin, stand up with a dumbbell held in one hand. Your feet should be about shoulder width apart from each other. Now fully extend the arm with the dumbbell over your head. Tip: The small finger of your hand should be facing the ceiling and the palm of your hand should be facing forward. The dumbbell should be above your head.', 'This will be your starting position.', 'Keeping your upper arm close to your head (elbows in) and perpendicular to the floor, lower the resistance in a semicircular motion behind your head until your forearm touch your bicep. Tip: The upper arm should remain stationary and only the forearm should move. Breathe in as you perform this step.', 'Go back to the starting position by using the triceps to raise the dumbbell. Breathe out as you perform this step.', 'Repeat for the recommended amount of repetitions.', 'Switch arms and repeat the exercise.']""",
        images=['Standing_One-Arm_Dumbbell_Triceps_Extension/0.jpg', 'Standing_One-Arm_Dumbbell_Triceps_Extension/1.jpg'],
    ),
    "Incline_Barbell_Triceps_Extension": ExerciseDefinition(
        id="Incline_Barbell_Triceps_Extension",
        display_name="Incline Barbell Triceps Extension",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.FOREARMS],
        instructions="""['Hold a barbell with an overhand grip (palms down) that is a little closer together than shoulder width.', 'Lie back on an incline bench set at any angle between 45-75-degrees.', 'Bring the bar overhead with your arms extended and elbows in. The arms should be in line with the torso above the head. This will be your starting position.', 'Now lower the bar in a semicircular motion behind your head until your forearms touch your biceps. Inhale as you perform this movement. Tip: Keep your upper arms stationary and close to your head at all times. Only the forearms should move.', 'Return to the starting position as you breathe out and you contract the triceps. Hold the contraction for a second.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Incline_Barbell_Triceps_Extension/0.jpg', 'Incline_Barbell_Triceps_Extension/1.jpg'],
    ),
    "Body-Up": ExerciseDefinition(
        id="Body-Up",
        display_name="Body-Up",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        secondary_muscles=[MuscleGroup.ABS, MuscleGroup.FOREARMS],
        instructions="""['Assume a plank position on the ground. You should be supporting your bodyweight on your toes and forearms, keeping your torso straight. Your forearms should be shoulder-width apart. This will be your starting position.', 'Pressing your palms firmly into the ground, extend through the elbows to raise your body from the ground. Keep your torso rigid as you perform the movement.', 'Slowly lower your forearms back to the ground by allowing the elbows to flex.', 'Repeat.']""",
        images=['Body-Up/0.jpg', 'Body-Up/1.jpg'],
    ),
    "Board_Press": ExerciseDefinition(
        id="Board_Press",
        display_name="Board Press",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.POWERLIFTING,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.CHEST, MuscleGroup.FOREARMS, MuscleGroup.LATS, MuscleGroup.SHOULDERS],
        instructions="""["Begin by lying on the bench, getting your head beyond the bar if possible. One to five boards, made out of 2x6's, can be screwed together and held in place by a training partner, bands, or just tucked under your shirt.", 'Tuck your feet underneath you and arch your back. Using the bar to help support your weight, lift your shoulder off the bench and retract them, squeezing the shoulder blades together. Use your feet to drive your traps into the bench. Maintain this tight body position throughout the movement.', 'You can take a standard bench grip, or shoulder width to focus on the triceps. Pull the bar out of the rack without protracting your shoulders. The bar, wrist, and elbow should stay in line at all times. Focus on squeezing the bar and trying to pull it apart.', 'Lower the bar to the boards, and then drive the bar up with as much force as possible. The elbows should be tucked in until lockout.']""",
        images=['Board_Press/0.jpg', 'Board_Press/1.jpg'],
    ),
    "One_Arm_Floor_Press": ExerciseDefinition(
        id="One_Arm_Floor_Press",
        display_name="One Arm Floor Press",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
        instructions="""['Lie down on a flat surface with your back pressing against the floor or an exercise mat. Make sure your knees are bent.', 'Have a partner hand you the bar on one hand. When starting, your arm should be just about fully extended, similar to the starting position of a barbell bench press. However, this time your grip will be neutral (palms facing your torso).', 'Make sure the hand you are not using to lift the weight is placed by your side.', 'Begin the exercise by lowering the barbell until your elbow touches the ground. Make sure to breathe in as this is the eccentric (lowering part of the exercise).', 'Then start lifting the barbell back up to the original starting position. Remember to breathe out during the concentric (lifting part of the exercise).', 'Repeat until you have performed your recommended repetitions.', 'Switch arms and repeat the movement.']""",
        images=['One_Arm_Floor_Press/0.jpg', 'One_Arm_Floor_Press/1.jpg'],
    ),
    "Cable_Lying_Triceps_Extension": ExerciseDefinition(
        id="Cable_Lying_Triceps_Extension",
        display_name="Cable Lying Triceps Extension",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['Lie on a flat bench and grasp the straight bar attachment of a low pulley with a narrow overhand grip. Tip: The easiest way to do this is to have someone hand you the bar as you lay down.', 'With your arms extended, position the bar over your torso. Your arms and your torso should create a 90-degree angle. This will be your starting position.', 'Lower the bar by bending at the elbow while keeping the upper arms stationary and elbows in. Go down until the bar lightly touches your forehead. Breathe in as you perform this portion of the movement.', 'Flex the triceps as you lift the bar back to its starting position. Exhale as you perform this portion of the movement.', 'Hold for a second at the contracted position and repeat for the recommended amount of repetitions.']""",
        images=['Cable_Lying_Triceps_Extension/0.jpg', 'Cable_Lying_Triceps_Extension/1.jpg'],
    ),
    "Seated_Bent-Over_Two-Arm_Dumbbell_Triceps_Extension": ExerciseDefinition(
        id="Seated_Bent-Over_Two-Arm_Dumbbell_Triceps_Extension",
        display_name="Seated Bent-Over Two-Arm Dumbbell Triceps Extension",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        instructions="""['Sit down at the end of a flat bench with a dumbbell in both arms using a neutral grip (palms of the hand facing you).', 'Bend your knees slightly and bring your torso forward, by bending at the waist, while keeping the back straight until it is almost parallel to the floor. Make sure that you keep the head up.', 'The upper arms with the dumbbells should be close to the torso and aligned with it (lifted up until they are parallel to the floor while the forearms are pointing towards the floor as the hands hold the weights). Tip: There should be a 90-degree angle between the forearms and the upper arm. This is your starting position.', 'Keeping the upper arms stationary, use the triceps to lift the weight as you exhale until the forearms are parallel to the floor and the whole arm is extended. Like many other arm exercises, only the forearm moves.', 'After a second contraction at the top, slowly lower the dumbbells back to the starting position as you inhale.', 'Repeat the movement for the prescribed amount of repetitions.']""",
        images=['Seated_Bent-Over_Two-Arm_Dumbbell_Triceps_Extension/0.jpg', 'Seated_Bent-Over_Two-Arm_Dumbbell_Triceps_Extension/1.jpg'],
    ),
    "Weighted_Bench_Dip": ExerciseDefinition(
        id="Weighted_Bench_Dip",
        display_name="Weighted Bench Dip",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.OTHER,
        secondary_muscles=[MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
        instructions="""['For this exercise you will need to place a bench behind your back and another one in front of you. With the benches perpendicular to your body, hold on to one bench on its edge with the hands close to your body, separated at shoulder width. Your arms should be fully extended.', 'The legs will be extended forward on top of the other bench. Your legs should be parallel to the floor while your torso is to be perpendicular to the floor. Have your partner place the dumbbell on your lap. Note: This exercise is best performed with a partner as placing the weight on your lap can be challenging and cause injury without assistance. This will be your starting position.', 'Slowly lower your body as you inhale by bending at the elbows until you lower yourself far enough to where there is an angle slightly smaller than 90 degrees between the upper arm and the forearm. Tip: Keep the elbows as close as possible throughout the movement. Forearms should always be pointing down.', 'Using your triceps to bring your torso up again, lift yourself back to the starting position while exhaling.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Weighted_Bench_Dip/0.jpg', 'Weighted_Bench_Dip/1.jpg'],
    ),
    "Low_Cable_Triceps_Extension": ExerciseDefinition(
        id="Low_Cable_Triceps_Extension",
        display_name="Low Cable Triceps Extension",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['Select the desired weight and lay down face up on the bench of a seated row machine that has a rope attached to it. Your head should be pointing towards the attachment.', 'Grab the outside of the rope ends with your palms facing each other (neutral grip).', 'Position your elbows so that they are bent at a 90 degree angle and your upper arms are perpendicular (90 degree angle) to your torso. Tip: Keep the elbows in and make sure that the upper arms point to the ceiling while your forearms point towards the pulley above your head. This will be your starting position.', 'As you breathe out, extend your lower arms until they are straight and vertical. The upper arms and elbows remain stationary throughout the movement. Only the forearms should move. Contract the triceps hard for a second.', 'As you breathe in slowly return to the starting position.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Low_Cable_Triceps_Extension/0.jpg', 'Low_Cable_Triceps_Extension/1.jpg'],
    ),
    "Push-Ups_-_Close_Triceps_Position": ExerciseDefinition(
        id="Push-Ups_-_Close_Triceps_Position",
        display_name="Push-Ups - Close Triceps Position",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
        instructions="""["Lie on the floor face down and place your hands closer than shoulder width for a close hand position. Make sure that you are holding your torso up at arms' length.", 'Lower yourself until your chest almost touches the floor as you inhale.', 'Using your triceps and some of your pectoral muscles, press your upper body back up to the starting position and squeeze your chest. Breathe out as you perform this step.', 'After a second pause at the contracted position, repeat the movement for the prescribed amount of repetitions.']""",
        images=['Push-Ups_-_Close_Triceps_Position/0.jpg', 'Push-Ups_-_Close_Triceps_Position/1.jpg'],
    ),
    "Lying_Dumbbell_Tricep_Extension": ExerciseDefinition(
        id="Lying_Dumbbell_Tricep_Extension",
        display_name="Lying Dumbbell Tricep Extension",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        secondary_muscles=[MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
        instructions="""['Lie on a flat bench while holding two dumbbells directly in front of you. Your arms should be fully extended at a 90-degree angle from your torso and the floor. The palms should be facing in and the elbows should be tucked in. This is the starting position.', 'As you breathe in and you keep the upper arms stationary with the elbows in, slowly lower the weight until the dumbbells are near your ears.', 'At that point, while keeping the elbows in and the upper arms stationary, use the triceps to bring the weight back up to the starting position as you breathe out.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Lying_Dumbbell_Tricep_Extension/0.jpg', 'Lying_Dumbbell_Tricep_Extension/1.jpg'],
    ),
    "Floor_Press": ExerciseDefinition(
        id="Floor_Press",
        display_name="Floor Press",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.POWERLIFTING,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
        instructions="""['Adjust the j-hooks so they are at the appropriate height to rack the bar. Begin lying on the floor with your head near the end of a power rack. Keeping your shoulder blades pulled together; pull the bar off of the hooks.', 'Lower the bar towards the bottom of your chest or upper stomach, squeezing the bar and attempting to pull it apart as you do so. Ensure that you tuck your elbows throughout the movement. Lower the bar until your upper arm contacts the ground and pause, preventing any slamming or bouncing of the weight.', 'Press the bar back up as fast as you can, keeping the bar, your wrists, and elbows in line as you do so.']""",
        images=['Floor_Press/0.jpg', 'Floor_Press/1.jpg'],
    ),
    "Chain_Handle_Extension": ExerciseDefinition(
        id="Chain_Handle_Extension",
        display_name="Chain Handle Extension",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.POWERLIFTING,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.OTHER,
        instructions="""['You will need two cable handle attachments and a flat bench, as well as chains, for this exercise. Clip the middle of the chains to the handles, and position yourself on the flat bench. Your elbows should be pointing straight up.', 'Begin by extending through the elbow, keeping your upper arm still, with your wrists pronated.', 'Pause at the lockout, and reverse the motion to return to the starting position.']""",
        images=['Chain_Handle_Extension/0.jpg', 'Chain_Handle_Extension/1.jpg'],
    ),
    "Triceps_Pushdown": ExerciseDefinition(
        id="Triceps_Pushdown",
        display_name="Triceps Pushdown",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['Attach a straight or angled bar to a high pulley and grab with an overhand grip (palms facing down) at shoulder width.', 'Standing upright with the torso straight and a very small inclination forward, bring the upper arms close to your body and perpendicular to the floor. The forearms should be pointing up towards the pulley as they hold the bar. This is your starting position.', 'Using the triceps, bring the bar down until it touches the front of your thighs and the arms are fully extended perpendicular to the floor. The upper arms should always remain stationary next to your torso and only the forearms should move. Exhale as you perform this movement.', 'After a second hold at the contracted position, bring the bar slowly up to the starting point. Breathe in as you perform this step.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Triceps_Pushdown/0.jpg', 'Triceps_Pushdown/1.jpg'],
    ),
    "Close-Grip_EZ-Bar_Press": ExerciseDefinition(
        id="Close-Grip_EZ-Bar_Press",
        display_name="Close-Grip EZ-Bar Press",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
        instructions="""['Lie on a flat bench with an EZ bar loaded to an appropriate weight.', 'Using a narrow grip lift the bar and hold it straight over your torso with your elbows in. The arms should be perpendicular to the floor. This will be your starting position.', 'Now lower the bar down to your lower chest as you breathe in. Keep the elbows in as you perform this movement.', 'Using the triceps to push the bar back up, press it back to the starting position by extending the elbows as you exhale.', 'Repeat.']""",
        images=['Close-Grip_EZ-Bar_Press/0.jpg', 'Close-Grip_EZ-Bar_Press/1.jpg'],
    ),
    "Tricep_Dumbbell_Kickback": ExerciseDefinition(
        id="Tricep_Dumbbell_Kickback",
        display_name="Tricep Dumbbell Kickback",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        instructions="""['Start with a dumbbell in each hand and your palms facing your torso. Keep your back straight with a slight bend in the knees and bend forward at the waist. Your torso should be almost parallel to the floor. Make sure to keep your head up. Your upper arms should be close to your torso and parallel to the floor. Your forearms should be pointed towards the floor as you hold the weights. There should be a 90-degree angle formed between your forearm and upper arm. This is your starting position.', 'Now, while keeping your upper arms stationary, exhale and use your triceps to lift the weights until the arm is fully extended. Focus on moving the forearm.', 'After a brief pause at the top contraction, inhale and slowly lower the dumbbells back down to the starting position.', 'Repeat the movement for the prescribed amount of repetitions.']""",
        images=['Tricep_Dumbbell_Kickback/0.jpg', 'Tricep_Dumbbell_Kickback/1.jpg'],
    ),
    "Ring_Dips": ExerciseDefinition(
        id="Ring_Dips",
        display_name="Ring Dips",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.OTHER,
        secondary_muscles=[MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
        instructions="""['Grip a ring in each hand, and then take a small jump to help you get into the starting position with your arms locked out.', 'Begin by flexing the elbow, lowering your body until your arms break 90 degrees. Avoid swinging, and maintain good posture throughout the descent.', 'Reverse the motion by extending the elbow, pushing yourself back up into the starting position.', 'Repeat for the desired number of repetitions.']""",
        images=['Ring_Dips/0.jpg', 'Ring_Dips/1.jpg'],
    ),
    "Close-Grip_Dumbbell_Press": ExerciseDefinition(
        id="Close-Grip_Dumbbell_Press",
        display_name="Close-Grip Dumbbell Press",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.DUMBBELL,
        secondary_muscles=[MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
        instructions="""['Place a dumbbell standing up on a flat bench.', 'Ensuring that the dumbbell stays securely placed at the top of the bench, lie perpendicular to the bench with only your shoulders lying on the surface. Hips should be below the bench and your legs bent with your feet firmly on the floor.', "Grasp the dumbbell with both hands and hold it straight over your chest at arm's length. Both palms should be pressing against the underside of the sides of the dumbbell. This will be your starting position.", 'Initiate the movement by lowering the dumbbell to your chest.', 'Return to the starting position by extending the elbows.']""",
        images=['Close-Grip_Dumbbell_Press/0.jpg', 'Close-Grip_Dumbbell_Press/1.jpg'],
    ),
    "Incline_Push-Up_Close-Grip": ExerciseDefinition(
        id="Incline_Push-Up_Close-Grip",
        display_name="Incline Push-Up Close-Grip",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
        instructions="""['Stand facing a Smith machine bar or sturdy elevated platform at an appropriate height.', 'Place your hands next to one another on the bar.', 'Position your feet back from the bar with arms and body straight. This will be your starting position.', 'Keeping your body straight, lower your chest to the bar by bending the arms.', 'Return to the starting position by extending the elbows, pressing yourself back up.']""",
        images=['Incline_Push-Up_Close-Grip/0.jpg', 'Incline_Push-Up_Close-Grip/1.jpg'],
    ),
    "Body_Tricep_Press": ExerciseDefinition(
        id="Body_Tricep_Press",
        display_name="Body Tricep Press",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        instructions="""['Position a bar in a rack at chest height.', 'Standing, take a shoulder width grip on the bar and step a yard or two back, feet together and arms extended so that you are leaning on the bar. This will be your starting position.', 'Begin by flexing the elbow, lowering yourself towards the bar.', 'Pause, and then reverse the motion by extending the elbows.', 'Progress from bodyweight by adding chains over your shoulders.']""",
        images=['Body_Tricep_Press/0.jpg', 'Body_Tricep_Press/1.jpg'],
    ),
    "Bench_Press_with_Chains": ExerciseDefinition(
        id="Bench_Press_with_Chains",
        display_name="Bench Press with Chains",
        level=LevelType.EXPERT,
        category=CategoryType.POWERLIFTING,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.CHEST, MuscleGroup.LATS, MuscleGroup.SHOULDERS],
        instructions="""['Adjust the leader chain, shortening it to the desired length.Place the chains on the sleeves of the bar.', 'Lying on the bench, get your head beyond the bar if possible. Tuck your feet underneath you and arch your back. Using the bar to help support your weight, lift your shoulder off the bench and retract them, squeezing the shoulder blades together. Use your feet to drive your traps into the bench. Maintain this tight body position throughout the movement. However wide your grip, it should cover the ring on the bar.', 'Pull the bar out of the rack without protracting your shoulders. Focus on squeezing the bar and trying to pull it apart. Lower the bar to your lower chest or upper stomach. The bar, wrist, and elbow should stay in line at all times.', 'Pause when the barbell touches your torso, and then drive the bar up with as much force as possible. The elbows should be tucked in until lockout.']""",
        images=['Bench_Press_with_Chains/0.jpg', 'Bench_Press_with_Chains/1.jpg'],
    ),
    "Seated_Bent-Over_One-Arm_Dumbbell_Triceps_Extension": ExerciseDefinition(
        id="Seated_Bent-Over_One-Arm_Dumbbell_Triceps_Extension",
        display_name="Seated Bent-Over One-Arm Dumbbell Triceps Extension",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        instructions="""['Sit down at the end of a flat bench with a dumbbell in one arm using a neutral grip (palms of the hand facing you).', 'Bend your knees slightly and bring your torso forward, by bending at the waist, while keeping the back straight until it is almost parallel to the floor. Make sure that you keep the head up.', 'The upper arm with the dumbbell should be close to the torso and aligned with it (lifted up until it is parallel to the floor while the forearms are pointing towards the floor as the hands hold the weights). Tip: There should be a 90-degree angle between the forearms and the upper arm. This is your starting position.', 'Keeping the upper arm stationary, use the triceps to lift the weight as you exhale until the forearm is parallel to the floor and the whole arm is extended. Like many other arm exercises, only the forearm moves.', 'After a second contraction at the top, slowly lower the dumbbell back to the starting position as you inhale.', 'Repeat the movement for the prescribed amount of repetitions.', 'Switch arms and repeat the exercise.']""",
        images=['Seated_Bent-Over_One-Arm_Dumbbell_Triceps_Extension/0.jpg', 'Seated_Bent-Over_One-Arm_Dumbbell_Triceps_Extension/1.jpg'],
    ),
    "Speed_Band_Overhead_Triceps": ExerciseDefinition(
        id="Speed_Band_Overhead_Triceps",
        display_name="Speed Band Overhead Triceps",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        instructions="""['For this exercise anchor a band to the ground. We used an incline bench and anchored the band to the base, standing over the bench. Alternatively, this could be performed standing on the band.', 'To begin, pull the band behind your head, holding it with a pronated grip and your elbows up. This will be your starting position.', 'To perform the movement, extend through the elbow to to straighten your arms, ensuring that you keep your upper arm in place.', 'Pause, and then return to the starting position.']""",
        images=['Speed_Band_Overhead_Triceps/0.jpg', 'Speed_Band_Overhead_Triceps/1.jpg'],
    ),
    "Tricep_Side_Stretch": ExerciseDefinition(
        id="Tricep_Side_Stretch",
        display_name="Tricep Side Stretch",
        level=LevelType.BEGINNER,
        category=CategoryType.STRETCHING,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.STATIC,
        secondary_muscles=[MuscleGroup.SHOULDERS],
        instructions="""['Bring right arm across your body and over your left shoulder, holding your elbow with your left hand, until you feel a stretch in your tricep. Then repeat for your other arm.']""",
        images=['Tricep_Side_Stretch/0.jpg', 'Tricep_Side_Stretch/1.jpg'],
    ),
    "JM_Press": ExerciseDefinition(
        id="JM_Press",
        display_name="JM Press",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
        instructions="""['Start the exercise the same way you would a close grip bench press. You will lie on a flat bench while holding a barbell at arms length (fully extended) with the elbows in. However, instead of having the arms perpendicular to the torso, make sure the bar is set in a direct line above the upper chest. This will be your starting position.', 'Now beginning from a fully extended position lower the bar down as if performing a lying triceps extension. Inhale as you perform this movement. When you reach the half way point, let the bar roll back about one inch by moving the upper arms towards your legs until they are perpendicular to the torso. Tip: Keep the bend at the elbows constant as you bring the upper arms forward.', 'As you exhale, press the bar back up by using the triceps to perform a close grip bench press.', 'Now go back to the starting position and start over.', 'Repeat for the recommended amount of repetitions.']""",
        images=['JM_Press/0.jpg', 'JM_Press/1.jpg'],
    ),
    "Pin_Presses": ExerciseDefinition(
        id="Pin_Presses",
        display_name="Pin Presses",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.POWERLIFTING,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.CHEST, MuscleGroup.FOREARMS, MuscleGroup.LATS, MuscleGroup.SHOULDERS],
        instructions="""['Pin presses remove the eccentric phase of the bench press, developing starting strength. They also allow you to train a desired range of motion.', 'The bench should be set up in a power rack. Set the pins to the desired point in your range of motion, whether it just be lockout or an inch off of your chest. The bar should be moved to the pins and prepared for lifting.', 'Begin by lying on the bench, with the bar directly above the contact point during your regular bench. Tuck your feet underneath you and arch your back. Using the bar to help support your weight, lift your shoulder off the bench and retract them, squeezing the shoulder blades together. Use your feet to drive your traps into the bench. Maintain this tight body position throughout the movement.', 'You can take a standard bench grip, or shoulder width to focus on the triceps. The bar, wrist, and elbow should stay in line at all times. Focus on squeezing the bar and trying to pull it apart.', 'Drive the bar up with as much force as possible. The elbows should be tucked in until lockout.', 'Return the bar to the pins, pausing before beginning the next repetition.']""",
        images=['Pin_Presses/0.jpg', 'Pin_Presses/1.jpg'],
    ),
    "Lying_Close-Grip_Barbell_Triceps_Extension_Behind_The_Head": ExerciseDefinition(
        id="Lying_Close-Grip_Barbell_Triceps_Extension_Behind_The_Head",
        display_name="Lying Close-Grip Barbell Triceps Extension Behind The Head",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.BARBELL,
        instructions="""['While holding a barbell or EZ Curl bar with a pronated grip (palms facing forward), lie on your back on a flat bench with your head close to the end of the bench. Tip: If you are holding a barbell grab it using a shoulder-width grip and if you are using an E-Z Bar grab it on the inner handles.', 'Extend your arms in front of you and slowly bring the bar back in a semi circular motion (while keeping the arms extended) to a position over your head. At the end of this step your arms should be overhead and parallel to the floor. This will be your starting position. Tip: Keep your elbows in at all times.', 'As you inhale, lower the bar by bending at the elbows and while keeping the upper arm stationary. Keep lowering the bar until your forearms are perpendicular to the floor.', 'As you exhale bring the bar back up to the starting position by pushing the bar up in a semi-circular motion until the lower arms are also parallel to the floor. Contract the triceps hard at the top of the movement for a second. Tip: Again, only the forearms should move. The upper arms should remain stationary at all times.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Lying_Close-Grip_Barbell_Triceps_Extension_Behind_The_Head/0.jpg', 'Lying_Close-Grip_Barbell_Triceps_Extension_Behind_The_Head/1.jpg'],
    ),
    "Dips_-_Triceps_Version": ExerciseDefinition(
        id="Dips_-_Triceps_Version",
        display_name="Dips - Triceps Version",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
        instructions="""["To get into the starting position, hold your body at arm's length with your arms nearly locked above the bars.", 'Now, inhale and slowly lower yourself downward. Your torso should remain upright and your elbows should stay close to your body. This helps to better focus on tricep involvement. Lower yourself until there is a 90 degree angle formed between the upper arm and forearm.', 'Then, exhale and push your torso back up using your triceps to bring your body back to the starting position.', 'Repeat the movement for the prescribed amount of repetitions.']""",
        images=['Dips_-_Triceps_Version/0.jpg', 'Dips_-_Triceps_Version/1.jpg'],
    ),
    "Triceps_Pushdown_-_V-Bar_Attachment": ExerciseDefinition(
        id="Triceps_Pushdown_-_V-Bar_Attachment",
        display_name="Triceps Pushdown - V-Bar Attachment",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['Attach a V-Bar to a high pulley and grab with an overhand grip (palms facing down) at shoulder width.', 'Standing upright with the torso straight and a very small inclination forward, bring the upper arms close to your body and perpendicular to the floor. The forearms should be pointing up towards the pulley as they hold the bar. The thumbs should be higher than the small finger. This is your starting position.', 'Using the triceps, bring the bar down until it touches the front of your thighs and the arms are fully extended perpendicular to the floor. The upper arms should always remain stationary next to your torso and only the forearms should move. Exhale as you perform this movement.', 'After a second hold at the contracted position, bring the V-Bar slowly up to the starting point. Breathe in as you perform this step.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Triceps_Pushdown_-_V-Bar_Attachment/0.jpg', 'Triceps_Pushdown_-_V-Bar_Attachment/1.jpg'],
    ),
    "Close-Grip_Push-Up_off_of_a_Dumbbell": ExerciseDefinition(
        id="Close-Grip_Push-Up_off_of_a_Dumbbell",
        display_name="Close-Grip Push-Up off of a Dumbbell",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.ABS, MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
        instructions="""['Lie on the floor and place your hands on an upright dumbbell. Supporting your weight on your toes and hands, keep your torso rigid and your elbows in with your arms straight. This will be your starting position.', 'Lower your body, allowing the elbows to flex while you inhale. Keep your body straight, not allowing your hips to rise or sag.', 'Press yourself back up to the starting position by extending the elbows. Breathe out as you perform this step.', 'After a pause at the contracted position, repeat the movement for the prescribed amount of repetitions.']""",
        images=['Close-Grip_Push-Up_off_of_a_Dumbbell/0.jpg', 'Close-Grip_Push-Up_off_of_a_Dumbbell/1.jpg'],
    ),
    "Dip_Machine": ExerciseDefinition(
        id="Dip_Machine",
        display_name="Dip Machine",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.MACHINE,
        secondary_muscles=[MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
        instructions="""['Sit securely in a dip machine, select the weight and firmly grasp the handles.', 'Now keep your elbows in at your sides in order to place emphasis on the triceps. The elbows should be bent at a 90 degree angle.', 'As you contract the triceps, extend your arms downwards as you exhale. Tip: At the bottom of the movement, focus on keeping a little bend in your arms to keep tension on the triceps muscle.', 'Now slowly let your arms come back up to the starting position as you inhale.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Dip_Machine/0.jpg', 'Dip_Machine/1.jpg'],
    ),
    "Tate_Press": ExerciseDefinition(
        id="Tate_Press",
        display_name="Tate Press",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        secondary_muscles=[MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
        instructions="""['Lie down on a flat bench with a dumbbell in each hand on top of your thighs. The palms of your hand will be facing each other.', 'By using your thighs to help you get the dumbbells up, clean the dumbbells one arm at a time so that you can hold them in front of you at shoulder width. Note: when holding the dumbbells in front of you, make sure your arms are wider than shoulder width apart from each other using a pronated (palms forward) grip. Allow your elbows to point out. This is your starting position.', 'Keeping the upper arms stationary, slowly move the dumbbells in and down in a semi circular motion until they touch the upper chest while inhaling. Keep full control of the dumbbells at all times and do not move the upper arms nor rest the dumbbells on the chest.', 'As you breathe out, move the dumbbells up using your triceps and the same semi-circular motion but in reverse. Attempt to keep the dumbbells together as they move up. Lock your arms in the contracted position, hold for a second and then start coming down again slowly again. Tip: It should take at least twice as long to go down than to come up.', 'Repeat the movement for the prescribed amount of repetitions of your training program.']""",
        images=['Tate_Press/0.jpg', 'Tate_Press/1.jpg'],
    ),
    "Machine_Triceps_Extension": ExerciseDefinition(
        id="Machine_Triceps_Extension",
        display_name="Machine Triceps Extension",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.MACHINE,
        instructions="""['Adjust the seat to the appropriate height and make your weight selection. Place your upper arms against the pads and grasp the handles. This will be your starting position.', 'Perform the movement by extending the elbow, pulling your lower arm away from your upper arm.', 'Pause at the completion of the movement, and then slowly return the weight to the starting position.', 'Avoid returning the weight all the way to the stops until the set is complete to keep tension on the muscles being worked.']""",
        images=['Machine_Triceps_Extension/0.jpg', 'Machine_Triceps_Extension/1.jpg'],
    ),
    "Band_Skull_Crusher": ExerciseDefinition(
        id="Band_Skull_Crusher",
        display_name="Band Skull Crusher",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        instructions="""['Secure a band to the base of a rack or the bench. Lay on the bench so that the band is lined up with your head.', 'Take hold of the band, raising your elbows so that the upper arm is perpendicular to the floor. With the elbow flexed, the band should be above your head. This will be your starting position.', 'Extend through the elbow to straighten your arm, keeping your upper arm in place.', 'Pause at the top of the motion, and return to the starting position.']""",
        images=['Band_Skull_Crusher/0.jpg', 'Band_Skull_Crusher/1.jpg'],
    ),
    "Smith_Machine_Close-Grip_Bench_Press": ExerciseDefinition(
        id="Smith_Machine_Close-Grip_Bench_Press",
        display_name="Smith Machine Close-Grip Bench Press",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.MACHINE,
        secondary_muscles=[MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
        instructions="""['Place a flat bench underneath the smith machine. Place the barbell at a height that you can reach when lying down and your arms are almost fully extended. Once the weight you need is selected, lie down on the flat bench. Using a close and pronated grip (palms facing forward) that is around shoulder width, unlock the bar from the rack and hold it straight over you with your arms locked. This will be your starting position.', 'As you breathe in, come down slowly until you feel the bar on your middle chest. Tip: Make sure that as opposed to a regular bench press, you keep the elbows close to the torso at all times in order to maximize triceps involvement.', 'After a second pause, bring the bar back to the starting position as you breathe out and push the bar using your triceps muscles. Lock your arms in the contracted position, hold for a second and then start coming down slowly again. Tip: It should take at least twice as long to go down than to come up.', 'Repeat the movement for the prescribed amount of repetitions.', 'When you are done, lock the bar back in the rack.']""",
        images=['Smith_Machine_Close-Grip_Bench_Press/0.jpg', 'Smith_Machine_Close-Grip_Bench_Press/1.jpg'],
    ),
    "One_Arm_Pronated_Dumbbell_Triceps_Extension": ExerciseDefinition(
        id="One_Arm_Pronated_Dumbbell_Triceps_Extension",
        display_name="One Arm Pronated Dumbbell Triceps Extension",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        instructions="""['Lie flat on a bench while holding a dumbbell at arms length. Your arm should be perpendicular to your body. The palm of your hand should be facing towards your feet as a pronated grip is required to perform this exercise.', 'Place your non lifting hand on your bicep for support.', 'Slowly begin to lower the dumbbell down as you breathe in.', 'Then, begin lifting the dumbbell upward as you contract the triceps. Remember to breathe out during the concentric (lifting part of the exercise).', 'Repeat until you have performed your set repetitions.', 'Switch arms and repeat the movement.']""",
        images=['One_Arm_Pronated_Dumbbell_Triceps_Extension/0.jpg', 'One_Arm_Pronated_Dumbbell_Triceps_Extension/1.jpg'],
    ),
    "Bench_Press_-_Powerlifting": ExerciseDefinition(
        id="Bench_Press_-_Powerlifting",
        display_name="Bench Press - Powerlifting",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.POWERLIFTING,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.CHEST, MuscleGroup.FOREARMS, MuscleGroup.LATS, MuscleGroup.SHOULDERS],
        instructions="""['Begin by lying on the bench, getting your head beyond the bar if possible. Tuck your feet underneath you and arch your back. Using the bar to help support your weight, lift your shoulder off the bench and retract them, squeezing the shoulder blades together. Use your feet to drive your traps into the bench. Maintain this tight body position throughout the movement.', 'However wide your grip, it should cover the ring on the bar. Pull the bar out of the rack without protracting your shoulders. Focus on squeezing the bar and trying to pull it apart.', 'Lower the bar to your lower chest or upper stomach. The bar, wrist, and elbow should stay in line at all times.', 'Pause when the barbell touches your torso, and then drive the bar up with as much force as possible. The elbows should be tucked in until lockout.']""",
        images=['Bench_Press_-_Powerlifting/0.jpg', 'Bench_Press_-_Powerlifting/1.jpg'],
    ),
    "EZ-Bar_Skullcrusher": ExerciseDefinition(
        id="EZ-Bar_Skullcrusher",
        display_name="EZ-Bar Skullcrusher",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        secondary_muscles=[MuscleGroup.FOREARMS],
        instructions="""['Using a close grip, lift the EZ bar and hold it with your elbows in as you lie on the bench. Your arms should be perpendicular to the floor. This will be your starting position.', 'Keeping the upper arms stationary, lower the bar by allowing the elbows to flex. Inhale as you perform this portion of the movement. Pause once the bar is directly above the forehead.', 'Lift the bar back to the starting position by extending the elbow and exhaling.', 'Repeat.']""",
        images=['EZ-Bar_Skullcrusher/0.jpg', 'EZ-Bar_Skullcrusher/1.jpg'],
    ),
    "Decline_Dumbbell_Triceps_Extension": ExerciseDefinition(
        id="Decline_Dumbbell_Triceps_Extension",
        display_name="Decline Dumbbell Triceps Extension",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        instructions="""['Secure your legs at the end of the decline bench and lie down with a dumbbell on each hand on top of your thighs. The palms of your hand will be facing each other.', 'Once you are laying down, move the dumbbells in front of you at shoulder width. The palms of the hands should be facing each other and the arms should be perpendicular to the floor and fully extended. This will be your starting position.', 'As you breathe in and you keep the upper arms stationary (and elbows in), bring the dumbbells down slowly by moving your forearms in a semicircular motion towards you until your thumbs are next to your ears. Breathe in as you perform this portion of the movement.', 'Lift the dumbbells back to the starting position by contracting the triceps and exhaling.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Decline_Dumbbell_Triceps_Extension/0.jpg', 'Decline_Dumbbell_Triceps_Extension/1.jpg'],
    ),
    "Triceps_Overhead_Extension_with_Rope": ExerciseDefinition(
        id="Triceps_Overhead_Extension_with_Rope",
        display_name="Triceps Overhead Extension with Rope",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['Attach a rope to a low pulley. After selecting an appropriate weight, grasp the rope with both hands and face away from the cable.', 'Position your hands behind your head with your elbows point straight up. Your elbows should start out flexed, and you can stagger your stance and lean gently away from the machine to create greater stability. This will be your starting position.', 'To perform the movement, extend through the elbow while keeping the upper arm in position, raising your hands above your head.', 'Squeeze your triceps at the top of the movement, and slowly lower the weight back to the start position.']""",
        images=['Triceps_Overhead_Extension_with_Rope/0.jpg', 'Triceps_Overhead_Extension_with_Rope/1.jpg'],
    ),
    "Decline_Close-Grip_Bench_To_Skull_Crusher": ExerciseDefinition(
        id="Decline_Close-Grip_Bench_To_Skull_Crusher",
        display_name="Decline Close-Grip Bench To Skull Crusher",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
        instructions="""['Secure your legs at the end of the decline bench and slowly lay down on the bench.', 'Using a close grip (a grip that is slightly less than shoulder width), lift the bar from the rack and hold it straight over you with your arms locked and elbows in. The arms should be perpendicular to the floor. This will be your starting position. Tip: In order to protect your rotator cuff, it is best if you have a spotter help you lift the barbell off the rack.', 'Now lower the bar down to your lower chest as you breathe in. Keep the elbows in as you perform this movement.', 'Using the triceps to push the bar back up, press it back to the starting position as you exhale.', 'As you breathe in and you keep the upper arms stationary, bring the bar down slowly by moving your forearms in a semicircular motion towards you until you feel the bar slightly touch your forehead. Breathe in as you perform this portion of the movement.', 'Lift the bar back to the starting position by contracting the triceps and exhaling.', 'Repeat steps 3-6 until the recommended amount of repetitions is performed.']""",
        images=['Decline_Close-Grip_Bench_To_Skull_Crusher/0.jpg', 'Decline_Close-Grip_Bench_To_Skull_Crusher/1.jpg'],
    ),
    "Dumbbell_One-Arm_Triceps_Extension": ExerciseDefinition(
        id="Dumbbell_One-Arm_Triceps_Extension",
        display_name="Dumbbell One-Arm Triceps Extension",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        instructions="""['Grab a dumbbell and either sit on a military press bench or a utility bench that has a back support on it as you place the dumbbells upright on top of your thighs or stand up straight.', 'Clean the dumbbell up to bring it to shoulder height and then extend the arm over your head so that the whole arm is perpendicular to the floor and next to your head. The dumbbell should be on top of you. The other hand can be kept fully extended to the side, by the waist, supporting the upper arm that has the dumbbell or grabbing a fixed surface.', 'Rotate the wrist so that the palm of your hand is facing forward and the pinkie is facing the ceiling. This will be your starting position.', 'Slowly lower the dumbbell behind your head as you hold the upper arm stationary. Inhale as you perform this movement and pause when your triceps are fully stretched.', 'Return to the starting position by flexing your triceps as you breathe out. Tip: It is imperative that only the forearm moves. The upper arm should remain at all times stationary next to your head.', 'Repeat for the recommended amount of repetitions and switch arms.']""",
        images=['Dumbbell_One-Arm_Triceps_Extension/0.jpg', 'Dumbbell_One-Arm_Triceps_Extension/1.jpg'],
    ),
    "Standing_Dumbbell_Triceps_Extension": ExerciseDefinition(
        id="Standing_Dumbbell_Triceps_Extension",
        display_name="Standing Dumbbell Triceps Extension",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.DUMBBELL,
        instructions="""['To begin, stand up with a dumbbell held by both hands. Your feet should be about shoulder width apart from each other. Slowly use both hands to grab the dumbbell and lift it over your head until both arms are fully extended.', 'The resistance should be resting in the palms of your hands with your thumbs around it. The palm of the hands should be facing up towards the ceiling. This will be your starting position.', 'Keeping your upper arms close to your head with elbows in and perpendicular to the floor, lower the resistance in a semicircular motion behind your head until your forearms touch your biceps. Tip: The upper arms should remain stationary and only the forearms should move. Breathe in as you perform this step.', 'Go back to the starting position by using the triceps to raise the dumbbell. Breathe out as you perform this step.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Standing_Dumbbell_Triceps_Extension/0.jpg', 'Standing_Dumbbell_Triceps_Extension/1.jpg'],
    ),
    "Cable_Incline_Triceps_Extension": ExerciseDefinition(
        id="Cable_Incline_Triceps_Extension",
        display_name="Cable Incline Triceps Extension",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.ISOLATION,
        equipment_type=EquipmentType.CABLE,
        instructions="""['Lie on incline an bench facing away from a high pulley machine that has a straight bar attachment on it.', 'Grasp the straight bar attachment overhead with a pronated (overhand; palms down) narrow grip (less than shoulder width) and keep your elbows tucked in to your sides. Your upper arms should create around a 25 degree angle when measured from the floor.', 'Keeping the upper arms stationary, extend the arms as you flex the triceps. Breathe out during this portion of the movement and hold the contraction for a second.', 'Slowly go back to the starting position.', 'Repeat for the recommended amount of repetitions.']""",
        images=['Cable_Incline_Triceps_Extension/0.jpg', 'Cable_Incline_Triceps_Extension/1.jpg'],
    ),
    "Reverse_Triceps_Bench_Press": ExerciseDefinition(
        id="Reverse_Triceps_Bench_Press",
        display_name="Reverse Triceps Bench Press",
        level=LevelType.INTERMEDIATE,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        equipment_type=EquipmentType.BARBELL,
        secondary_muscles=[MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
        instructions="""['Lie back on a flat bench. Using a close, supinated grip (around shoulder width), lift the bar from the rack and hold it straight over you with your arms locked extended in front of you and perpendicular to the floor. This will be your starting position.', 'As you breathe in, come down slowly until you feel the bar on your middle chest. Tip: Make sure that as opposed to a regular bench press, you keep the elbows close to the torso at all times in order to maximize triceps involvement.', 'After a second pause, bring the bar back to the starting position as you breathe out and push the bar using your triceps muscles. Lock your arms in the contracted position, hold for a second and then start coming down slowly again. Tip: It should take at least twice as long to go down than to come up.', 'Repeat the movement for the prescribed amount of repetitions.', 'When you are done, place the bar back in the rack.']""",
        images=['Reverse_Triceps_Bench_Press/0.jpg', 'Reverse_Triceps_Bench_Press/1.jpg'],
    ),
    "Bodyweight_Dips": ExerciseDefinition(
        id="Bodyweight_Dips",
        display_name="Bodyweight Dips",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
        instructions="""["Bodyweight dips build chest, shoulders, and triceps by lowering your body between parallel bars, keeping elbows tucked, leaning slightly forward (more for chest, upright for triceps), going to 90 degrees or comfortable depth, then pushing back up while keeping shoulders down and back straight. Beginners can use bands, knee push-ups, or toe-assisted dips to master the form before progressing.']""",
        images=[],
    ),
    "Pushup_Ladder": ExerciseDefinition(
        id="Pushup_Ladder",
        display_name="Pushup Ladder",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
        instructions="""['A push-up ladder is a progressive workout where you increase reps/intensity across sets, often using an agility ladder for lateral moves or a power rack for height changes, with common formats including ascending reps (1, 2, 3...) or decreasing reps (10, 9, 8...) until failure, focusing on core engagement and maintaining good form as you work up or down the "rungs" of intensity/reps to build strength and challenge fatigue.']""",
        images=[],
    ),
    "Weight_Upright_Dips": ExerciseDefinition(
        id="Weight_Upright_Dips",
        display_name="Weight Upright Dips",
        level=LevelType.BEGINNER,
        category=CategoryType.STRENGTH,
        muscle_group=MuscleGroup.TRICEPS,
        major_muscle_group=MajorMuscleGroup.ARMS,
        force=ForceType.PUSH,
        mechanics_type=MechanicsType.COMPOUND,
        secondary_muscles=[MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
        instructions="""["To do weighted upright dips, secure weight (belt/vest/dumbbell), grip bars with straight arms, lower slowly (elbows tucked) until shoulders are below elbows, keeping body vertical, then press up powerfully to full arm extension, focusing on triceps and maintaining core tension to build strength safely.']""",
        images=[],
    ),
}
